-- Aggregate fail-closed postflight for NSMQ remediation 267-270.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS _nsmq_post_expected(q TEXT PRIMARY KEY,s TEXT NOT NULL,r TEXT NOT NULL,t TEXT NOT NULL,m INTEGER NOT NULL);
DELETE FROM _nsmq_post_expected;
INSERT INTO _nsmq_post_expected VALUES
  ('nsmq_math_rid_012','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','267'),
  ('nsmq_phy_rid_012','subj_nsmq_physics','riddles','topic_thermodynamics','267'),
  ('nsmq_bio_pod_001','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_002','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_003','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_004','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_005','subj_nsmq_biology','problem_of_day','topic_physiology','267'),
  ('nsmq_bio_pod_006','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_007','subj_nsmq_biology','problem_of_day','topic_biochemistry','267'),
  ('nsmq_bio_pod_008','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_009','subj_nsmq_biology','problem_of_day','topic_ecology','267'),
  ('nsmq_bio_pod_010','subj_nsmq_biology','problem_of_day','topic_cells','267'),
  ('nsmq_bio_pod_011','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_012','subj_nsmq_biology','problem_of_day','topic_physiology','267'),
  ('nsmq_bio_pod_013','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_014','subj_nsmq_biology','problem_of_day','topic_physiology','267'),
  ('nsmq_bio_pod_015','subj_nsmq_biology','problem_of_day','topic_genetics','267'),
  ('nsmq_bio_pod_016','subj_nsmq_biology','problem_of_day','topic_physiology','267'),
  ('nsmq_bio_pod_017','subj_nsmq_biology','problem_of_day','topic_cells','267'),
  ('nsmq_bio_pod_018','subj_nsmq_biology','problem_of_day','topic_biochemistry','267'),
  ('nsmq_bio_pod_019','subj_nsmq_biology','problem_of_day','topic_ecology','267'),
  ('nsmq_bio_pod_020','subj_nsmq_biology','problem_of_day','topic_physiology','267'),
  ('nsmq_bio_rid_001','subj_nsmq_biology','riddles','topic_genetics','267'),
  ('nsmq_bio_rid_002','subj_nsmq_biology','riddles','topic_cells','267'),
  ('nsmq_bio_rid_003','subj_nsmq_biology','riddles','topic_genetics','267'),
  ('nsmq_bio_rid_004','subj_nsmq_biology','riddles','topic_physiology','267'),
  ('nsmq_bio_rid_005','subj_nsmq_biology','riddles','topic_cells','267'),
  ('nsmq_bio_rid_006','subj_nsmq_biology','riddles','topic_physiology','267'),
  ('nsmq_bio_rid_007','subj_nsmq_biology','riddles','topic_biochemistry','267'),
  ('nsmq_bio_rid_008','subj_nsmq_biology','riddles','topic_ecology','267'),
  ('nsmq_bio_rid_009','subj_nsmq_biology','riddles','topic_physiology','267'),
  ('nsmq_bio_rid_010','subj_nsmq_biology','riddles','topic_genetics','267'),
  ('nsmq_bio_rid_011','subj_nsmq_biology','riddles','topic_genetics','267'),
  ('nsmq_bio_rid_012','subj_nsmq_biology','riddles','topic_physiology','267'),
  ('nsmq_bio_rid_013','subj_nsmq_biology','riddles','topic_physiology','267'),
  ('nsmq_bio_rid_014','subj_nsmq_biology','riddles','topic_physiology','267'),
  ('nsmq_bio_rid_015','subj_nsmq_biology','riddles','topic_cells','267'),
  ('nsmq_bio_r1_001','subj_nsmq_biology','round_one','topic_cells','267'),
  ('nsmq_bio_r1_002','subj_nsmq_biology','round_one','topic_biochemistry','267'),
  ('nsmq_bio_r1_003','subj_nsmq_biology','round_one','topic_genetics','267'),
  ('nsmq_bio_r1_004','subj_nsmq_biology','round_one','topic_cells','267'),
  ('nsmq_bio_r1_005','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_006','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_007','subj_nsmq_biology','round_one','topic_genetics','267'),
  ('nsmq_bio_r1_008','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_009','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_010','subj_nsmq_biology','round_one','topic_cells','267'),
  ('nsmq_bio_r1_011','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_012','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_013','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_014','subj_nsmq_biology','round_one','topic_genetics','267'),
  ('nsmq_bio_r1_015','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_016','subj_nsmq_biology','round_one','topic_ecology','267'),
  ('nsmq_bio_r1_017','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_018','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_019','subj_nsmq_biology','round_one','topic_cells','267'),
  ('nsmq_bio_r1_020','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_021','subj_nsmq_biology','round_one','topic_biochemistry','267'),
  ('nsmq_bio_r1_022','subj_nsmq_biology','round_one','topic_cells','267'),
  ('nsmq_bio_r1_023','subj_nsmq_biology','round_one','topic_ecology','267'),
  ('nsmq_bio_r1_024','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_025','subj_nsmq_biology','round_one','topic_physiology','267'),
  ('nsmq_bio_r1_026','subj_nsmq_biology','round_one','topic_genetics','267'),
  ('nsmq_bio_r1_027','subj_nsmq_biology','round_one','topic_ecology','267'),
  ('nsmq_bio_r1_028','subj_nsmq_biology','round_one','topic_biochemistry','267'),
  ('nsmq_bio_r1_029','subj_nsmq_biology','round_one','topic_ecology','267'),
  ('nsmq_bio_r1_030','subj_nsmq_biology','round_one','topic_cells','267'),
  ('q_speed_005','subj_nsmq_biology','speed_race','topic_cells','267'),
  ('nsmq_bio_tf_001','subj_nsmq_biology','true_false','topic_cells','267'),
  ('nsmq_bio_tf_002','subj_nsmq_biology','true_false','topic_genetics','267'),
  ('nsmq_bio_tf_003','subj_nsmq_biology','true_false','topic_physiology','267'),
  ('nsmq_bio_tf_004','subj_nsmq_biology','true_false','topic_biochemistry','267'),
  ('nsmq_bio_tf_005','subj_nsmq_biology','true_false','topic_biochemistry','267'),
  ('nsmq_bio_tf_006','subj_nsmq_biology','true_false','topic_cells','267'),
  ('nsmq_bio_tf_007','subj_nsmq_biology','true_false','topic_genetics','267'),
  ('nsmq_bio_tf_008','subj_nsmq_biology','true_false','topic_physiology','267'),
  ('nsmq_bio_tf_009','subj_nsmq_biology','true_false','topic_cells','267'),
  ('nsmq_bio_tf_010','subj_nsmq_biology','true_false','topic_biochemistry','267'),
  ('nsmq_bio_tf_011','subj_nsmq_biology','true_false','topic_physiology','267'),
  ('nsmq_bio_tf_012','subj_nsmq_biology','true_false','topic_genetics','267'),
  ('nsmq_bio_tf_013','subj_nsmq_biology','true_false','topic_physiology','267'),
  ('nsmq_bio_tf_014','subj_nsmq_biology','true_false','topic_ecology','267'),
  ('nsmq_bio_tf_015','subj_nsmq_biology','true_false','topic_biochemistry','267'),
  ('nsmq_bio_tf_016','subj_nsmq_biology','true_false','topic_physiology','267'),
  ('nsmq_bio_tf_017','subj_nsmq_biology','true_false','topic_physiology','267'),
  ('nsmq_bio_tf_018','subj_nsmq_biology','true_false','topic_genetics','267'),
  ('nsmq_bio_tf_019','subj_nsmq_biology','true_false','topic_genetics','267'),
  ('nsmq_bio_tf_020','subj_nsmq_biology','true_false','topic_physiology','267'),
  ('nsmq_chem_pod_001','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_002','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_003','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_004','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_005','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_006','subj_nsmq_chemistry','problem_of_day','topic_equilibrium','267'),
  ('nsmq_chem_pod_007','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_008','subj_nsmq_chemistry','problem_of_day','topic_organic','267'),
  ('nsmq_chem_pod_009','subj_nsmq_chemistry','problem_of_day','topic_electrochemistry','267'),
  ('nsmq_chem_pod_010','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_011','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_012','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','267'),
  ('nsmq_chem_pod_013','subj_nsmq_chemistry','problem_of_day','topic_atomic','268'),
  ('nsmq_chem_pod_014','subj_nsmq_chemistry','problem_of_day','topic_stoichiometry','268'),
  ('nsmq_chem_pod_015','subj_nsmq_chemistry','problem_of_day','topic_equilibrium','268'),
  ('nsmq_chem_pod_016','subj_nsmq_chemistry','problem_of_day','topic_equilibrium','268'),
  ('nsmq_chem_pod_017','subj_nsmq_chemistry','problem_of_day','topic_atomic','268'),
  ('nsmq_chem_pod_018','subj_nsmq_chemistry','problem_of_day','topic_equilibrium','268'),
  ('nsmq_chem_pod_019','subj_nsmq_chemistry','problem_of_day','topic_organic','268'),
  ('nsmq_chem_pod_020','subj_nsmq_chemistry','problem_of_day','topic_bonding','268'),
  ('nsmq_chem_rid_001','subj_nsmq_chemistry','riddles','topic_electrochemistry','268'),
  ('nsmq_chem_rid_002','subj_nsmq_chemistry','riddles','topic_organic','268'),
  ('nsmq_chem_rid_003','subj_nsmq_chemistry','riddles','topic_atomic','268'),
  ('nsmq_chem_rid_004','subj_nsmq_chemistry','riddles','topic_atomic','268'),
  ('nsmq_chem_rid_005','subj_nsmq_chemistry','riddles','topic_atomic','268'),
  ('nsmq_chem_rid_006','subj_nsmq_chemistry','riddles','topic_stoichiometry','268'),
  ('nsmq_chem_rid_007','subj_nsmq_chemistry','riddles','topic_bonding','268'),
  ('nsmq_chem_rid_008','subj_nsmq_chemistry','riddles','topic_atomic','268'),
  ('nsmq_chem_rid_009','subj_nsmq_chemistry','riddles','topic_atomic','268'),
  ('nsmq_chem_rid_010','subj_nsmq_chemistry','riddles','topic_bonding','268'),
  ('nsmq_chem_rid_011','subj_nsmq_chemistry','riddles','topic_equilibrium','268'),
  ('nsmq_chem_rid_012','subj_nsmq_chemistry','riddles','topic_atomic','268'),
  ('nsmq_chem_rid_013','subj_nsmq_chemistry','riddles','topic_equilibrium','268'),
  ('nsmq_chem_rid_014','subj_nsmq_chemistry','riddles','topic_bonding','268'),
  ('nsmq_chem_rid_015','subj_nsmq_chemistry','riddles','topic_atomic','268'),
  ('nsmq_chem_r1_001','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_002','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('nsmq_chem_r1_003','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_004','subj_nsmq_chemistry','round_one','topic_equilibrium','268'),
  ('nsmq_chem_r1_005','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_006','subj_nsmq_chemistry','round_one','topic_bonding','268'),
  ('nsmq_chem_r1_007','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('nsmq_chem_r1_008','subj_nsmq_chemistry','round_one','topic_bonding','268'),
  ('nsmq_chem_r1_009','subj_nsmq_chemistry','round_one','topic_bonding','268'),
  ('nsmq_chem_r1_010','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('nsmq_chem_r1_011','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('nsmq_chem_r1_012','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_013','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('nsmq_chem_r1_014','subj_nsmq_chemistry','round_one','topic_bonding','268'),
  ('nsmq_chem_r1_015','subj_nsmq_chemistry','round_one','topic_equilibrium','268'),
  ('nsmq_chem_r1_016','subj_nsmq_chemistry','round_one','topic_organic','268'),
  ('nsmq_chem_r1_017','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_018','subj_nsmq_chemistry','round_one','topic_electrochemistry','268'),
  ('nsmq_chem_r1_019','subj_nsmq_chemistry','round_one','topic_nsmq_chem_environmental','268'),
  ('nsmq_chem_r1_020','subj_nsmq_chemistry','round_one','topic_equilibrium','268'),
  ('nsmq_chem_r1_021','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_022','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_023','subj_nsmq_chemistry','round_one','topic_organic','268'),
  ('nsmq_chem_r1_024','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('nsmq_chem_r1_025','subj_nsmq_chemistry','round_one','topic_equilibrium','268'),
  ('nsmq_chem_r1_026','subj_nsmq_chemistry','round_one','topic_bonding','268'),
  ('nsmq_chem_r1_027','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_028','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('nsmq_chem_r1_029','subj_nsmq_chemistry','round_one','topic_atomic','268'),
  ('nsmq_chem_r1_030','subj_nsmq_chemistry','round_one','topic_stoichiometry','268'),
  ('q_speed_004','subj_nsmq_chemistry','speed_race','topic_atomic','268'),
  ('nsmq_chem_tf_001','subj_nsmq_chemistry','true_false','topic_atomic','268'),
  ('nsmq_chem_tf_002','subj_nsmq_chemistry','true_false','topic_atomic','268'),
  ('nsmq_chem_tf_003','subj_nsmq_chemistry','true_false','topic_equilibrium','268'),
  ('nsmq_chem_tf_004','subj_nsmq_chemistry','true_false','topic_bonding','268'),
  ('nsmq_chem_tf_005','subj_nsmq_chemistry','true_false','topic_atomic','268'),
  ('nsmq_chem_tf_006','subj_nsmq_chemistry','true_false','topic_equilibrium','268'),
  ('nsmq_chem_tf_007','subj_nsmq_chemistry','true_false','topic_atomic','268'),
  ('nsmq_chem_tf_008','subj_nsmq_chemistry','true_false','topic_electrochemistry','268'),
  ('nsmq_chem_tf_009','subj_nsmq_chemistry','true_false','topic_equilibrium','268'),
  ('nsmq_chem_tf_010','subj_nsmq_chemistry','true_false','topic_atomic','268'),
  ('nsmq_chem_tf_011','subj_nsmq_chemistry','true_false','topic_atomic','268'),
  ('nsmq_chem_tf_012','subj_nsmq_chemistry','true_false','topic_equilibrium','268'),
  ('nsmq_chem_tf_013','subj_nsmq_chemistry','true_false','topic_equilibrium','268'),
  ('nsmq_chem_tf_014','subj_nsmq_chemistry','true_false','topic_organic','268'),
  ('nsmq_chem_tf_015','subj_nsmq_chemistry','true_false','topic_equilibrium','268'),
  ('nsmq_chem_tf_016','subj_nsmq_chemistry','true_false','topic_bonding','268'),
  ('nsmq_chem_tf_017','subj_nsmq_chemistry','true_false','topic_stoichiometry','268'),
  ('nsmq_chem_tf_018','subj_nsmq_chemistry','true_false','topic_bonding','268'),
  ('nsmq_chem_tf_019','subj_nsmq_chemistry','true_false','topic_electrochemistry','268'),
  ('nsmq_chem_tf_020','subj_nsmq_chemistry','true_false','topic_equilibrium','268'),
  ('nsmq_math_pod_001','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_002','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_003','subj_nsmq_math','problem_of_day','topic_geometry','268'),
  ('nsmq_math_pod_004','subj_nsmq_math','problem_of_day','topic_statistics','268'),
  ('nsmq_math_pod_005','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_006','subj_nsmq_math','problem_of_day','topic_geometry','268'),
  ('nsmq_math_pod_007','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_008','subj_nsmq_math','problem_of_day','topic_statistics','268'),
  ('nsmq_math_pod_009','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_010','subj_nsmq_math','problem_of_day','topic_geometry','268'),
  ('nsmq_math_pod_011','subj_nsmq_math','problem_of_day','topic_quadratic','268'),
  ('nsmq_math_pod_012','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_013','subj_nsmq_math','problem_of_day','topic_geometry','268'),
  ('nsmq_math_pod_014','subj_nsmq_math','problem_of_day','topic_calculus','268'),
  ('nsmq_math_pod_015','subj_nsmq_math','problem_of_day','topic_geometry','268'),
  ('nsmq_math_pod_016','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_017','subj_nsmq_math','problem_of_day','topic_statistics','268'),
  ('nsmq_math_pod_018','subj_nsmq_math','problem_of_day','topic_algebra','268'),
  ('nsmq_math_pod_019','subj_nsmq_math','problem_of_day','topic_geometry','268'),
  ('nsmq_math_pod_020','subj_nsmq_math','problem_of_day','topic_statistics','268'),
  ('nsmq_math_rid_001','subj_nsmq_math','riddles','topic_algebra','268'),
  ('nsmq_math_rid_002','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','268'),
  ('nsmq_math_rid_003','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','268'),
  ('nsmq_math_rid_004','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','268'),
  ('nsmq_math_rid_005','subj_nsmq_math','riddles','topic_algebra','268'),
  ('nsmq_math_rid_006','subj_nsmq_math','riddles','topic_geometry','268'),
  ('nsmq_math_rid_007','subj_nsmq_math','riddles','topic_algebra','269'),
  ('nsmq_math_rid_008','subj_nsmq_math','riddles','topic_algebra','269'),
  ('nsmq_math_rid_009','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','269'),
  ('nsmq_math_rid_010','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','269'),
  ('nsmq_math_rid_011','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','269'),
  ('nsmq_math_rid_013','subj_nsmq_math','riddles','topic_nsmq_math_general_reasoning','269'),
  ('nsmq_math_rid_014','subj_nsmq_math','riddles','topic_algebra','269'),
  ('nsmq_math_rid_015','subj_nsmq_math','riddles','topic_nsmq_math_numeration','269'),
  ('nsmq_math_r1_001','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_002','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_003','subj_nsmq_math','round_one','topic_geometry','269'),
  ('nsmq_math_r1_004','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_005','subj_nsmq_math','round_one','topic_calculus','269'),
  ('nsmq_math_r1_006','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_007','subj_nsmq_math','round_one','topic_geometry','269'),
  ('nsmq_math_r1_008','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_009','subj_nsmq_math','round_one','topic_statistics','269'),
  ('nsmq_math_r1_010','subj_nsmq_math','round_one','topic_trigonometry','269'),
  ('nsmq_math_r1_011','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_012','subj_nsmq_math','round_one','topic_statistics','269'),
  ('nsmq_math_r1_013','subj_nsmq_math','round_one','topic_geometry','269'),
  ('nsmq_math_r1_014','subj_nsmq_math','round_one','topic_calculus','269'),
  ('nsmq_math_r1_015','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_016','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_017','subj_nsmq_math','round_one','topic_statistics','269'),
  ('nsmq_math_r1_018','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_019','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_020','subj_nsmq_math','round_one','topic_trigonometry','269'),
  ('nsmq_math_r1_021','subj_nsmq_math','round_one','topic_geometry','269'),
  ('nsmq_math_r1_022','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_023','subj_nsmq_math','round_one','topic_quadratic','269'),
  ('nsmq_math_r1_024','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_025','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_026','subj_nsmq_math','round_one','topic_geometry','269'),
  ('nsmq_math_r1_027','subj_nsmq_math','round_one','topic_geometry','269'),
  ('nsmq_math_r1_028','subj_nsmq_math','round_one','topic_statistics','269'),
  ('nsmq_math_r1_029','subj_nsmq_math','round_one','topic_algebra','269'),
  ('nsmq_math_r1_030','subj_nsmq_math','round_one','topic_trigonometry','269'),
  ('nsmq_math_sr_021','subj_nsmq_math','speed_race','topic_algebra','269'),
  ('nsmq_math_sr_022','subj_nsmq_math','speed_race','topic_nsmq_math_numeration','269'),
  ('nsmq_math_sr_023','subj_nsmq_math','speed_race','topic_algebra','269'),
  ('nsmq_math_sr_024','subj_nsmq_math','speed_race','topic_algebra','269'),
  ('nsmq_math_sr_025','subj_nsmq_math','speed_race','topic_statistics','269'),
  ('q_speed_002','subj_nsmq_math','speed_race','topic_algebra','269'),
  ('q_speed_006','subj_nsmq_math','speed_race','topic_trigonometry','269'),
  ('nsmq_math_tf_001','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_002','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_003','subj_nsmq_math','true_false','topic_geometry','269'),
  ('nsmq_math_tf_004','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_005','subj_nsmq_math','true_false','topic_calculus','269'),
  ('nsmq_math_tf_006','subj_nsmq_math','true_false','topic_geometry','269'),
  ('nsmq_math_tf_007','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_008','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_009','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_010','subj_nsmq_math','true_false','topic_geometry','269'),
  ('nsmq_math_tf_011','subj_nsmq_math','true_false','topic_statistics','269'),
  ('nsmq_math_tf_012','subj_nsmq_math','true_false','topic_trigonometry','269'),
  ('nsmq_math_tf_013','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_014','subj_nsmq_math','true_false','topic_statistics','269'),
  ('nsmq_math_tf_015','subj_nsmq_math','true_false','topic_geometry','269'),
  ('nsmq_math_tf_016','subj_nsmq_math','true_false','topic_geometry','269'),
  ('nsmq_math_tf_017','subj_nsmq_math','true_false','topic_calculus','269'),
  ('nsmq_math_tf_018','subj_nsmq_math','true_false','topic_geometry','269'),
  ('nsmq_math_tf_019','subj_nsmq_math','true_false','topic_algebra','269'),
  ('nsmq_math_tf_020','subj_nsmq_math','true_false','topic_nsmq_math_sets','269'),
  ('nsmq_phy_pod_001','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_002','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_003','subj_nsmq_physics','problem_of_day','topic_electricity','269'),
  ('nsmq_phy_pod_004','subj_nsmq_physics','problem_of_day','topic_waves','269'),
  ('nsmq_phy_pod_005','subj_nsmq_physics','problem_of_day','topic_electricity','269'),
  ('nsmq_phy_pod_006','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_007','subj_nsmq_physics','problem_of_day','topic_electricity','269'),
  ('nsmq_phy_pod_008','subj_nsmq_physics','problem_of_day','topic_waves','269'),
  ('nsmq_phy_pod_009','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_010','subj_nsmq_physics','problem_of_day','topic_electricity','269'),
  ('nsmq_phy_pod_011','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_012','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_013','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_014','subj_nsmq_physics','problem_of_day','topic_waves','269'),
  ('nsmq_phy_pod_015','subj_nsmq_physics','problem_of_day','topic_thermodynamics','269'),
  ('nsmq_phy_pod_016','subj_nsmq_physics','problem_of_day','topic_electricity','269'),
  ('nsmq_phy_pod_017','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_018','subj_nsmq_physics','problem_of_day','topic_electricity','269'),
  ('nsmq_phy_pod_019','subj_nsmq_physics','problem_of_day','topic_mechanics','269'),
  ('nsmq_phy_pod_020','subj_nsmq_physics','problem_of_day','topic_electricity','269'),
  ('nsmq_phy_rid_002','subj_nsmq_physics','riddles','topic_mechanics','269'),
  ('nsmq_phy_rid_004','subj_nsmq_physics','riddles','topic_thermodynamics','269'),
  ('nsmq_phy_rid_005','subj_nsmq_physics','riddles','topic_waves','269'),
  ('nsmq_phy_rid_006','subj_nsmq_physics','riddles','topic_mechanics','269'),
  ('nsmq_phy_rid_007','subj_nsmq_physics','riddles','topic_mechanics','269'),
  ('nsmq_phy_rid_008','subj_nsmq_physics','riddles','topic_electricity','269'),
  ('nsmq_phy_rid_009','subj_nsmq_physics','riddles','topic_modern_physics','269'),
  ('nsmq_phy_rid_010','subj_nsmq_physics','riddles','topic_mechanics','269'),
  ('nsmq_phy_rid_011','subj_nsmq_physics','riddles','topic_waves','269'),
  ('nsmq_phy_rid_013','subj_nsmq_physics','riddles','topic_electricity','269'),
  ('nsmq_phy_rid_014','subj_nsmq_physics','riddles','topic_mechanics','269'),
  ('nsmq_phy_rid_015','subj_nsmq_physics','riddles','topic_waves','269'),
  ('nsmq_phy_r1_001','subj_nsmq_physics','round_one','topic_electricity','269'),
  ('nsmq_phy_r1_002','subj_nsmq_physics','round_one','topic_waves','269'),
  ('nsmq_phy_r1_003','subj_nsmq_physics','round_one','topic_mechanics','269'),
  ('nsmq_phy_r1_004','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_005','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_006','subj_nsmq_physics','round_one','topic_modern_physics','270'),
  ('nsmq_phy_r1_007','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_008','subj_nsmq_physics','round_one','topic_electricity','270'),
  ('nsmq_phy_r1_009','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_010','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_011','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_012','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_013','subj_nsmq_physics','round_one','topic_electricity','270'),
  ('nsmq_phy_r1_014','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_015','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_016','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_017','subj_nsmq_physics','round_one','topic_electricity','270'),
  ('nsmq_phy_r1_018','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_019','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_020','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_021','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_022','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_023','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_024','subj_nsmq_physics','round_one','topic_mechanics','270'),
  ('nsmq_phy_r1_025','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_026','subj_nsmq_physics','round_one','topic_electricity','270'),
  ('nsmq_phy_r1_027','subj_nsmq_physics','round_one','topic_electricity','270'),
  ('nsmq_phy_r1_028','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_029','subj_nsmq_physics','round_one','topic_waves','270'),
  ('nsmq_phy_r1_030','subj_nsmq_physics','round_one','topic_electricity','270'),
  ('nsmq_phy_sr_001','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_002','subj_nsmq_physics','speed_race','topic_waves','270'),
  ('nsmq_phy_sr_003','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_004','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_005','subj_nsmq_physics','speed_race','topic_electricity','270'),
  ('nsmq_phy_sr_006','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_007','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_008','subj_nsmq_physics','speed_race','topic_waves','270'),
  ('nsmq_phy_sr_009','subj_nsmq_physics','speed_race','topic_thermodynamics','270'),
  ('nsmq_phy_sr_010','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_011','subj_nsmq_physics','speed_race','topic_modern_physics','270'),
  ('nsmq_phy_sr_012','subj_nsmq_physics','speed_race','topic_waves','270'),
  ('nsmq_phy_sr_013','subj_nsmq_physics','speed_race','topic_thermodynamics','270'),
  ('nsmq_phy_sr_014','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_015','subj_nsmq_physics','speed_race','topic_waves','270'),
  ('nsmq_phy_sr_016','subj_nsmq_physics','speed_race','topic_electricity','270'),
  ('nsmq_phy_sr_017','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_018','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_019','subj_nsmq_physics','speed_race','topic_electricity','270'),
  ('nsmq_phy_sr_020','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_021','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_sr_022','subj_nsmq_physics','speed_race','topic_electricity','270'),
  ('nsmq_phy_sr_023','subj_nsmq_physics','speed_race','topic_electricity','270'),
  ('nsmq_phy_sr_024','subj_nsmq_physics','speed_race','topic_electricity','270'),
  ('nsmq_phy_sr_025','subj_nsmq_physics','speed_race','topic_waves','270'),
  ('q_speed_003','subj_nsmq_physics','speed_race','topic_mechanics','270'),
  ('nsmq_phy_tf_001','subj_nsmq_physics','true_false','topic_waves','270'),
  ('nsmq_phy_tf_002','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_003','subj_nsmq_physics','true_false','topic_waves','270'),
  ('nsmq_phy_tf_004','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_005','subj_nsmq_physics','true_false','topic_electricity','270'),
  ('nsmq_phy_tf_006','subj_nsmq_physics','true_false','topic_electricity','270'),
  ('nsmq_phy_tf_007','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_008','subj_nsmq_physics','true_false','topic_waves','270'),
  ('nsmq_phy_tf_009','subj_nsmq_physics','true_false','topic_waves','270'),
  ('nsmq_phy_tf_010','subj_nsmq_physics','true_false','topic_electricity','270'),
  ('nsmq_phy_tf_011','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_012','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_013','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_014','subj_nsmq_physics','true_false','topic_waves','270'),
  ('nsmq_phy_tf_015','subj_nsmq_physics','true_false','topic_modern_physics','270'),
  ('nsmq_phy_tf_016','subj_nsmq_physics','true_false','topic_electricity','270'),
  ('nsmq_phy_tf_017','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_018','subj_nsmq_physics','true_false','topic_mechanics','270'),
  ('nsmq_phy_tf_019','subj_nsmq_physics','true_false','topic_waves','270'),
  ('nsmq_phy_tf_020','subj_nsmq_physics','true_false','topic_electricity','270');
CREATE TABLE IF NOT EXISTS _nsmq_post_exceptions(q TEXT PRIMARY KEY,s TEXT NOT NULL,r TEXT NOT NULL);
DELETE FROM _nsmq_post_exceptions;
INSERT INTO _nsmq_post_exceptions VALUES
  ('nsmq_phy_rid_001','subj_nsmq_physics','riddles'),
  ('nsmq_phy_rid_003','subj_nsmq_physics','riddles');
CREATE TABLE IF NOT EXISTS _nsmq_post_guard(valid INTEGER NOT NULL CHECK(valid=1));
DELETE FROM _nsmq_post_guard;
INSERT INTO _nsmq_post_guard(valid)
SELECT CASE WHEN
  (SELECT COUNT(*) FROM _nsmq_post_expected)=373
  AND (SELECT COUNT(*) FROM questions q JOIN _nsmq_post_expected e ON e.q=q.id WHERE q.subject_id IS e.s AND q.round_type IS e.r AND q.topic_id IS e.t)=373
  AND (SELECT COUNT(*) FROM questions q JOIN _nsmq_post_exceptions e ON e.q=q.id WHERE q.subject_id IS e.s AND q.round_type IS e.r AND q.topic_id IS NULL)=2
  AND EXISTS (SELECT 1 FROM questions WHERE id='nsmq_math_rid_012'
    AND question_text='I am a 4-digit number. All my digits are different. My first digit is 3 times my last digit. My second digit is one less than my first. My third digit is double my last digit. What numbers can I be?'
    AND correct_answer='6542 or 9863'
    AND explanation='Let the last digit be d, so the digits are 3d, 3d−1, 2d, d. The only possible last digits are 1, 2, and 3. When d=1, the digit 2 repeats, so it is invalid. When d=2, the number is 6542; when d=3, the number is 9863. Both satisfy every stated constraint.')
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_math' AND r='riddles')=15
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_physics' AND r='riddles')=15
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_biology' AND r='problem_of_day')=20
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_biology' AND r='riddles')=15
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_biology' AND r='round_one')=30
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_biology' AND r='speed_race')=1
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_biology' AND r='true_false')=20
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_chemistry' AND r='problem_of_day')=20
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_chemistry' AND r='riddles')=15
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_chemistry' AND r='round_one')=30
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_chemistry' AND r='speed_race')=1
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_chemistry' AND r='true_false')=20
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_math' AND r='problem_of_day')=20
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_math' AND r='round_one')=30
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_math' AND r='speed_race')=7
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_math' AND r='true_false')=20
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_physics' AND r='problem_of_day')=20
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_physics' AND r='round_one')=30
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_physics' AND r='speed_race')=26
  AND (SELECT COUNT(*) FROM (SELECT q,s,r FROM _nsmq_post_expected UNION ALL SELECT q,s,r FROM _nsmq_post_exceptions) x WHERE s='subj_nsmq_physics' AND r='true_false')=20
  AND (SELECT COUNT(*) FROM topics t WHERE (t.id='topic_nsmq_math_general_reasoning' AND t.subject_id='subj_nsmq_math' AND t.parent_id IS NULL AND t.name='General Reasoning' AND t.slug='general-reasoning' AND t.description='Constraint-based, logical and lateral reasoning questions assigned to Mathematics rounds.' AND t.theory_content IS NULL AND t.key_formulas IS NULL AND t.display_order=6 AND t.created_at='2026-08-26T00:00:00.000Z') OR (t.id='topic_nsmq_math_numeration' AND t.subject_id='subj_nsmq_math' AND t.parent_id IS NULL AND t.name='Numeration & Number Systems' AND t.slug='numeration-number-systems' AND t.description='Number representation, notation, bases and number-system conventions.' AND t.theory_content IS NULL AND t.key_formulas IS NULL AND t.display_order=7 AND t.created_at='2026-08-26T00:00:00.000Z') OR (t.id='topic_nsmq_math_sets' AND t.subject_id='subj_nsmq_math' AND t.parent_id IS NULL AND t.name='Sets' AND t.slug='sets' AND t.description='Set notation, membership, subsets, operations and related reasoning.' AND t.theory_content IS NULL AND t.key_formulas IS NULL AND t.display_order=8 AND t.created_at='2026-08-26T00:00:00.000Z') OR (t.id='topic_nsmq_chem_environmental' AND t.subject_id='subj_nsmq_chemistry' AND t.parent_id IS NULL AND t.name='Environmental Chemistry' AND t.slug='environmental-chemistry' AND t.description='Chemical processes and substances affecting the atmosphere and environment.' AND t.theory_content IS NULL AND t.key_formulas IS NULL AND t.display_order=7 AND t.created_at='2026-08-26T00:00:00.000Z'))=4
  AND (SELECT COUNT(*) FROM question_bank_remediation_log WHERE migration_id='267_nsmq_topic_remediation_part_1')=103
  AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _nsmq_post_expected e ON e.q=l.entity_id AND e.m=267
    WHERE l.migration_id='267_nsmq_topic_remediation_part_1' AND l.entity_type='question' AND l.field_name='topic_id' AND l.old_value IS NULL AND l.new_value IS e.t)=100
  AND (SELECT COUNT(*) FROM question_bank_remediation_log WHERE migration_id='267_nsmq_topic_remediation_part_1'
    AND entity_type='question' AND entity_id='nsmq_math_rid_012' AND (
      (field_name='question_text' AND old_value='I am a 4-digit number. All my digits are different. My first digit is 3 times my last digit. My second digit is one less than my first. My third digit is double my last digit. What number am I?' AND new_value='I am a 4-digit number. All my digits are different. My first digit is 3 times my last digit. My second digit is one less than my first. My third digit is double my last digit. What numbers can I be?')
      OR (field_name='correct_answer' AND old_value='3624' AND new_value='6542 or 9863')
      OR (field_name='explanation' AND old_value='Last=2, First=6, no wait... Let me recalculate: 3×1=3, 3-1=2, 2×1=2, last=1 → but not 4 digits. Try: 6521 (6=3×2, 5=6-1, 2=2×1, 1). Actually: 3624' AND new_value='Let the last digit be d, so the digits are 3d, 3d−1, 2d, d. The only possible last digits are 1, 2, and 3. When d=1, the digit 2 repeats, so it is invalid. When d=2, the number is 6542; when d=3, the number is 9863. Both satisfy every stated constraint.')
    ))=3
  AND (SELECT COUNT(*) FROM question_bank_remediation_log WHERE migration_id='268_nsmq_topic_remediation_part_2')=100
  AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _nsmq_post_expected e ON e.q=l.entity_id AND e.m=268
    WHERE l.migration_id='268_nsmq_topic_remediation_part_2' AND l.entity_type='question' AND l.field_name='topic_id' AND l.old_value IS NULL AND l.new_value IS e.t)=100
  AND (SELECT COUNT(*) FROM question_bank_remediation_log WHERE migration_id='269_nsmq_topic_remediation_part_3')=100
  AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _nsmq_post_expected e ON e.q=l.entity_id AND e.m=269
    WHERE l.migration_id='269_nsmq_topic_remediation_part_3' AND l.entity_type='question' AND l.field_name='topic_id' AND l.old_value IS NULL AND l.new_value IS e.t)=100
  AND (SELECT COUNT(*) FROM question_bank_remediation_log WHERE migration_id='270_nsmq_topic_remediation_part_4')=73
  AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _nsmq_post_expected e ON e.q=l.entity_id AND e.m=270
    WHERE l.migration_id='270_nsmq_topic_remediation_part_4' AND l.entity_type='question' AND l.field_name='topic_id' AND l.old_value IS NULL AND l.new_value IS e.t)=73
  AND (SELECT COUNT(*) FROM question_bank_remediation_log WHERE migration_id IN ('267_nsmq_topic_remediation_part_1','268_nsmq_topic_remediation_part_2','269_nsmq_topic_remediation_part_3','270_nsmq_topic_remediation_part_4'))=376
  AND (SELECT COUNT(*) FROM questions WHERE id IN ('q_speed_002','q_speed_006','q_speed_003','q_speed_004','q_speed_005') AND topic_id IS NOT NULL)=5
  AND NOT EXISTS (SELECT 1 FROM questions q JOIN _nsmq_post_expected e ON e.q=q.id JOIN topics t ON t.id=q.topic_id WHERE q.subject_id IS NOT t.subject_id OR e.s IS NOT t.subject_id)
THEN 1 ELSE 0 END;
SELECT 375 authoritative_rows,373 mapped_rows,2 reviewed_null_exceptions,376 exact_ledger_rows,5 live_only_rows;
PRAGMA foreign_key_check;
DROP TABLE _nsmq_post_expected;
DROP TABLE _nsmq_post_exceptions;
DROP TABLE _nsmq_post_guard;
