-- Migration 036: WASSCE Chemistry 2023 Questions (50 questions)
-- Properly linked to past_paper_id

INSERT OR IGNORE INTO questions (id, topic_id, subject_id, past_paper_id, question_text, question_type, options, correct_answer, explanation, difficulty, points, time_limit) VALUES
-- Atomic Structure (10 questions)
('q_wassce_chem_2023_01', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The atomic number of an element represents the number of:', 'multiple_choice', '["A. Neutrons", "B. Protons", "C. Electrons", "D. Nucleons"]', 'B', 'Atomic number equals the number of protons in the nucleus.', 'easy', 1, 60),
('q_wassce_chem_2023_02', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Isotopes of an element have the same number of:', 'multiple_choice', '["A. Neutrons", "B. Mass number", "C. Protons", "D. Nucleons"]', 'C', 'Isotopes have the same atomic number (protons) but different mass numbers.', 'easy', 1, 60),
('q_wassce_chem_2023_03', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The maximum number of electrons in the third shell is:', 'multiple_choice', '["A. 2", "B. 8", "C. 18", "D. 32"]', 'C', 'Third shell can hold maximum 2n² = 2(3)² = 18 electrons.', 'medium', 1, 60),
('q_wassce_chem_2023_04', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Which subatomic particle has a negative charge?', 'multiple_choice', '["A. Proton", "B. Neutron", "C. Electron", "D. Positron"]', 'C', 'Electrons carry a negative charge.', 'easy', 1, 60),
('q_wassce_chem_2023_05', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The electronic configuration of sodium (Na, Z=11) is:', 'multiple_choice', '["A. 2,8,1", "B. 2,9", "C. 2,8,2", "D. 2,7,2"]', 'A', 'Sodium has 11 electrons: 2 in first shell, 8 in second, 1 in third.', 'easy', 1, 60),
('q_wassce_chem_2023_06', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'An atom with 17 protons and 18 neutrons has a mass number of:', 'multiple_choice', '["A. 17", "B. 18", "C. 35", "D. 1"]', 'C', 'Mass number = protons + neutrons = 17 + 18 = 35.', 'easy', 1, 60),
('q_wassce_chem_2023_07', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The nucleus of an atom contains:', 'multiple_choice', '["A. Electrons only", "B. Protons and neutrons", "C. Neutrons only", "D. Electrons and protons"]', 'B', 'The nucleus contains protons and neutrons.', 'easy', 1, 60),
('q_wassce_chem_2023_08', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Elements in the same group have the same number of:', 'multiple_choice', '["A. Protons", "B. Electrons", "C. Valence electrons", "D. Neutrons"]', 'C', 'Elements in the same group have equal valence electrons.', 'medium', 1, 60),
('q_wassce_chem_2023_09', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The relative atomic mass of chlorine is 35.5 because:', 'multiple_choice', '["A. Chlorine has half a neutron", "B. It is an average of isotope masses", "C. Chlorine atoms are incomplete", "D. Measurement error"]', 'B', 'Relative atomic mass is a weighted average of isotope masses.', 'medium', 1, 90),
('q_wassce_chem_2023_10', 'topic_atomic_structure', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Which orbital has the highest energy in an atom?', 'multiple_choice', '["A. 1s", "B. 2s", "C. 2p", "D. 3s"]', 'D', 'Energy increases with principal quantum number and orbital type.', 'medium', 1, 60),

-- Chemical Bonding (10 questions)
('q_wassce_chem_2023_11', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Ionic bonds are formed by:', 'multiple_choice', '["A. Sharing of electrons", "B. Transfer of electrons", "C. Sharing of protons", "D. Transfer of neutrons"]', 'B', 'Ionic bonds form when electrons are transferred between atoms.', 'easy', 1, 60),
('q_wassce_chem_2023_12', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The bond in H₂O is:', 'multiple_choice', '["A. Ionic", "B. Metallic", "C. Covalent", "D. Hydrogen"]', 'C', 'Water molecules have covalent bonds between H and O atoms.', 'easy', 1, 60),
('q_wassce_chem_2023_13', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The shape of a methane molecule is:', 'multiple_choice', '["A. Linear", "B. Trigonal planar", "C. Tetrahedral", "D. Octahedral"]', 'C', 'CH₄ has a tetrahedral shape with 109.5° bond angles.', 'medium', 1, 60),
('q_wassce_chem_2023_14', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'A coordinate (dative) bond is formed when:', 'multiple_choice', '["A. Both electrons come from one atom", "B. Electrons are transferred", "C. Protons are shared", "D. Ions attract each other"]', 'A', 'In coordinate bonds, one atom provides both shared electrons.', 'medium', 1, 90),
('q_wassce_chem_2023_15', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Which compound has ionic bonding?', 'multiple_choice', '["A. H₂O", "B. CO₂", "C. NaCl", "D. CH₄"]', 'C', 'NaCl has ionic bonds between Na⁺ and Cl⁻ ions.', 'easy', 1, 60),
('q_wassce_chem_2023_16', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Metallic bonding involves:', 'multiple_choice', '["A. Shared electron pairs", "B. A sea of delocalized electrons", "C. Electron transfer", "D. Hydrogen bonds"]', 'B', 'Metallic bonds involve delocalized electrons moving freely.', 'easy', 1, 60),
('q_wassce_chem_2023_17', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The bond angle in water is approximately:', 'multiple_choice', '["A. 180°", "B. 109.5°", "C. 104.5°", "D. 120°"]', 'C', 'Water has a bent shape with ~104.5° bond angle due to lone pairs.', 'medium', 1, 60),
('q_wassce_chem_2023_18', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Van der Waals forces are:', 'multiple_choice', '["A. Strong covalent bonds", "B. Weak intermolecular forces", "C. Ionic bonds", "D. Nuclear forces"]', 'B', 'Van der Waals are weak forces between molecules.', 'easy', 1, 60),
('q_wassce_chem_2023_19', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Hydrogen bonding occurs in:', 'multiple_choice', '["A. CH₄", "B. CCl₄", "C. H₂O", "D. CO₂"]', 'C', 'Hydrogen bonding occurs when H is bonded to N, O, or F.', 'easy', 1, 60),
('q_wassce_chem_2023_20', 'topic_chemical_bonding', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'A double bond contains:', 'multiple_choice', '["A. 2 electrons", "B. 4 electrons", "C. 6 electrons", "D. 8 electrons"]', 'B', 'A double bond has 4 shared electrons (2 pairs).', 'easy', 1, 60),

-- Acids, Bases and Salts (10 questions)
('q_wassce_chem_2023_21', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The pH of a neutral solution is:', 'multiple_choice', '["A. 0", "B. 7", "C. 14", "D. 1"]', 'B', 'Neutral solutions have pH = 7.', 'easy', 1, 60),
('q_wassce_chem_2023_22', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'An acid produces ___ ions in water:', 'multiple_choice', '["A. OH⁻", "B. H⁺", "C. Na⁺", "D. Cl⁻"]', 'B', 'Acids release H⁺ (hydrogen) ions in aqueous solution.', 'easy', 1, 60),
('q_wassce_chem_2023_23', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The reaction between an acid and a base produces:', 'multiple_choice', '["A. Salt and water", "B. Salt only", "C. Water only", "D. Gas only"]', 'A', 'Neutralization: Acid + Base → Salt + Water.', 'easy', 1, 60),
('q_wassce_chem_2023_24', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'A strong acid is one that:', 'multiple_choice', '["A. Is concentrated", "B. Completely ionizes", "C. Has high pH", "D. Reacts slowly"]', 'B', 'Strong acids completely dissociate in water.', 'medium', 1, 60),
('q_wassce_chem_2023_25', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Which is a weak acid?', 'multiple_choice', '["A. HCl", "B. H₂SO₄", "C. CH₃COOH", "D. HNO₃"]', 'C', 'Ethanoic (acetic) acid is a weak acid that partially ionizes.', 'easy', 1, 60),
('q_wassce_chem_2023_26', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The indicator that is pink in base is:', 'multiple_choice', '["A. Methyl orange", "B. Phenolphthalein", "C. Litmus", "D. Universal indicator"]', 'B', 'Phenolphthalein is colorless in acid and pink in base.', 'easy', 1, 60),
('q_wassce_chem_2023_27', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'A buffer solution:', 'multiple_choice', '["A. Changes pH rapidly", "B. Resists pH changes", "C. Is always neutral", "D. Contains only water"]', 'B', 'Buffers resist changes in pH when small amounts of acid or base are added.', 'medium', 1, 90),
('q_wassce_chem_2023_28', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'NaOH is a:', 'multiple_choice', '["A. Weak acid", "B. Strong acid", "C. Weak base", "D. Strong base"]', 'D', 'Sodium hydroxide is a strong base.', 'easy', 1, 60),
('q_wassce_chem_2023_29', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Titration is used to determine:', 'multiple_choice', '["A. Color of solution", "B. Concentration of solution", "C. Temperature", "D. Density"]', 'B', 'Titration determines unknown concentration using a known solution.', 'easy', 1, 60),
('q_wassce_chem_2023_30', 'topic_acids_bases', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'What salt is formed when HCl reacts with NaOH?', 'multiple_choice', '["A. NaCl", "B. Na₂SO₄", "C. NaNO₃", "D. Na₂CO₃"]', 'A', 'HCl + NaOH → NaCl + H₂O.', 'easy', 1, 60),

-- Organic Chemistry (10 questions)
('q_wassce_chem_2023_31', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The general formula for alkanes is:', 'multiple_choice', '["A. CₙH₂ₙ", "B. CₙH₂ₙ₊₂", "C. CₙH₂ₙ₋₂", "D. CₙHₙ"]', 'B', 'Alkanes have the general formula CₙH₂ₙ₊₂.', 'easy', 1, 60),
('q_wassce_chem_2023_32', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The functional group of alcohols is:', 'multiple_choice', '["A. -COOH", "B. -OH", "C. -CHO", "D. -CO-"]', 'B', 'Alcohols contain the hydroxyl (-OH) group.', 'easy', 1, 60),
('q_wassce_chem_2023_33', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Isomers have the same:', 'multiple_choice', '["A. Structure", "B. Molecular formula", "C. Properties", "D. Boiling point"]', 'B', 'Isomers share the same molecular formula but different structures.', 'medium', 1, 60),
('q_wassce_chem_2023_34', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The process of cracking is used to:', 'multiple_choice', '["A. Join molecules", "B. Break large hydrocarbons", "C. Purify compounds", "D. Oxidize fuels"]', 'B', 'Cracking breaks large hydrocarbon molecules into smaller ones.', 'easy', 1, 60),
('q_wassce_chem_2023_35', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Ethene undergoes addition reactions because it has:', 'multiple_choice', '["A. Single bonds only", "B. A double bond", "C. An -OH group", "D. A benzene ring"]', 'B', 'The C=C double bond in ethene allows addition reactions.', 'medium', 1, 60),
('q_wassce_chem_2023_36', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Fermentation of glucose produces:', 'multiple_choice', '["A. Ethanol and CO₂", "B. Methanol and H₂O", "C. Ethane and O₂", "D. Propanol and CO"]', 'A', 'C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ (fermentation).', 'easy', 1, 60),
('q_wassce_chem_2023_37', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'IUPAC name of CH₃CH₂OH is:', 'multiple_choice', '["A. Methanol", "B. Ethanol", "C. Propanol", "D. Butanol"]', 'B', 'CH₃CH₂OH is ethanol (2 carbons with -OH group).', 'easy', 1, 60),
('q_wassce_chem_2023_38', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Polymerization produces:', 'multiple_choice', '["A. Small molecules", "B. Large molecules from monomers", "C. Elements", "D. Ionic compounds"]', 'B', 'Polymerization joins monomers to form large polymer molecules.', 'easy', 1, 60),
('q_wassce_chem_2023_39', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The product of complete combustion of hydrocarbons is:', 'multiple_choice', '["A. CO and H₂O", "B. CO₂ and H₂O", "C. C and H₂O", "D. CO₂ only"]', 'B', 'Complete combustion produces CO₂ and H₂O.', 'easy', 1, 60),
('q_wassce_chem_2023_40', 'topic_organic_chemistry', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Soap is made from:', 'multiple_choice', '["A. Fats and acids", "B. Fats and alkalis", "C. Proteins and acids", "D. Carbohydrates and bases"]', 'B', 'Saponification: Fats + NaOH → Soap + Glycerol.', 'medium', 1, 60),

-- Chemical Reactions (10 questions)
('q_wassce_chem_2023_41', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'A catalyst:', 'multiple_choice', '["A. Increases product amount", "B. Speeds up reaction without being used up", "C. Is always a metal", "D. Changes equilibrium position"]', 'B', 'Catalysts increase reaction rate and are regenerated.', 'easy', 1, 60),
('q_wassce_chem_2023_42', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'An exothermic reaction:', 'multiple_choice', '["A. Absorbs heat", "B. Releases heat", "C. Requires a catalyst", "D. Is always slow"]', 'B', 'Exothermic reactions release heat to surroundings.', 'easy', 1, 60),
('q_wassce_chem_2023_43', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The rate of reaction can be increased by:', 'multiple_choice', '["A. Decreasing temperature", "B. Increasing concentration", "C. Decreasing surface area", "D. Removing catalyst"]', 'B', 'Higher concentration increases collision frequency.', 'easy', 1, 60),
('q_wassce_chem_2023_44', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'In a reversible reaction at equilibrium:', 'multiple_choice', '["A. Reaction stops", "B. Forward and reverse rates are equal", "C. Products disappear", "D. Reactants disappear"]', 'B', 'At equilibrium, forward and reverse reaction rates are equal.', 'medium', 1, 90),
('q_wassce_chem_2023_45', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Oxidation involves:', 'multiple_choice', '["A. Gain of electrons", "B. Loss of electrons", "C. Gain of protons", "D. Loss of neutrons"]', 'B', 'Oxidation Is Loss of electrons (OIL RIG).', 'easy', 1, 60),
('q_wassce_chem_2023_46', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'The oxidation state of oxygen in most compounds is:', 'multiple_choice', '["A. +2", "B. -2", "C. 0", "D. -1"]', 'B', 'Oxygen usually has -2 oxidation state.', 'easy', 1, 60),
('q_wassce_chem_2023_47', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'A precipitation reaction forms:', 'multiple_choice', '["A. A gas", "B. An insoluble solid", "C. A liquid", "D. Heat only"]', 'B', 'Precipitation produces an insoluble solid (precipitate).', 'easy', 1, 60),
('q_wassce_chem_2023_48', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Electrolysis requires:', 'multiple_choice', '["A. Heat", "B. A catalyst", "C. An electric current", "D. High pressure"]', 'C', 'Electrolysis uses electricity to drive chemical reactions.', 'easy', 1, 60),
('q_wassce_chem_2023_49', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'At the cathode during electrolysis:', 'multiple_choice', '["A. Oxidation occurs", "B. Reduction occurs", "C. No reaction occurs", "D. Gases escape"]', 'B', 'Reduction (gain of electrons) occurs at the cathode.', 'medium', 1, 60),
('q_wassce_chem_2023_50', 'topic_chemical_reactions', 'subj_chemistry', 'pp_wassce_chem_2023_1', 'Rusting of iron requires:', 'multiple_choice', '["A. Oxygen only", "B. Water only", "C. Oxygen and water", "D. Carbon dioxide"]', 'C', 'Rusting requires both oxygen and moisture.', 'easy', 1, 60);
