-- Migration 041: NSMQ Speed Race Questions
-- Quick-fire questions requiring fast answers

INSERT OR REPLACE INTO questions (id, subject_id, question_text, question_type, round_type, options, correct_answer, explanation, difficulty, points, time_limit) VALUES

-- MATHEMATICS Speed Race (25 questions)
('nsmq_math_sr_001', 'subj_math', 'What is 15% of 200?', 'direct_answer', 'speed_race', NULL, '30', '15/100 × 200 = 30', 'easy', 2, 15),
('nsmq_math_sr_002', 'subj_math', 'What is the square root of 144?', 'direct_answer', 'speed_race', NULL, '12', '√144 = 12', 'easy', 2, 15),
('nsmq_math_sr_003', 'subj_math', 'What is 7³?', 'direct_answer', 'speed_race', NULL, '343', '7 × 7 × 7 = 343', 'easy', 2, 15),
('nsmq_math_sr_004', 'subj_math', 'What is the next prime number after 17?', 'direct_answer', 'speed_race', NULL, '19', '19 is the next prime after 17', 'easy', 2, 15),
('nsmq_math_sr_005', 'subj_math', 'If 2x = 14, what is x?', 'direct_answer', 'speed_race', NULL, '7', 'x = 14/2 = 7', 'easy', 2, 15),
('nsmq_math_sr_006', 'subj_math', 'What is 0.25 as a fraction in lowest terms?', 'direct_answer', 'speed_race', NULL, '1/4', '0.25 = 25/100 = 1/4', 'easy', 2, 15),
('nsmq_math_sr_007', 'subj_math', 'What is the perimeter of a square with side 9 cm?', 'direct_answer', 'speed_race', NULL, '36 cm', 'Perimeter = 4 × 9 = 36 cm', 'easy', 2, 15),
('nsmq_math_sr_008', 'subj_math', 'What is 2⁴ + 3²?', 'direct_answer', 'speed_race', NULL, '25', '16 + 9 = 25', 'easy', 2, 15),
('nsmq_math_sr_009', 'subj_math', 'How many degrees in a right angle?', 'direct_answer', 'speed_race', NULL, '90', 'A right angle = 90°', 'easy', 2, 15),
('nsmq_math_sr_010', 'subj_math', 'What is the reciprocal of 5?', 'direct_answer', 'speed_race', NULL, '1/5', 'Reciprocal of 5 is 1/5', 'easy', 2, 15),
('nsmq_math_sr_011', 'subj_math', 'Simplify: 3/4 + 1/4', 'direct_answer', 'speed_race', NULL, '1', '3/4 + 1/4 = 4/4 = 1', 'easy', 2, 15),
('nsmq_math_sr_012', 'subj_math', 'What is the GCD of 24 and 36?', 'direct_answer', 'speed_race', NULL, '12', 'GCD(24, 36) = 12', 'medium', 2, 15),
('nsmq_math_sr_013', 'subj_math', 'Convert 3/5 to a percentage.', 'direct_answer', 'speed_race', NULL, '60%', '3/5 × 100 = 60%', 'easy', 2, 15),
('nsmq_math_sr_014', 'subj_math', 'What is (-3) × (-4)?', 'direct_answer', 'speed_race', NULL, '12', 'Negative × Negative = Positive: 12', 'easy', 2, 15),
('nsmq_math_sr_015', 'subj_math', 'What is the value of π to 2 decimal places?', 'direct_answer', 'speed_race', NULL, '3.14', 'π ≈ 3.14', 'easy', 2, 15),
('nsmq_math_sr_016', 'subj_math', 'How many vertices does a cube have?', 'direct_answer', 'speed_race', NULL, '8', 'A cube has 8 vertices', 'easy', 2, 15),
('nsmq_math_sr_017', 'subj_math', 'What is 5! divided by 4!?', 'direct_answer', 'speed_race', NULL, '5', '5!/4! = 5', 'medium', 2, 15),
('nsmq_math_sr_018', 'subj_math', 'What is the supplement of 35°?', 'direct_answer', 'speed_race', NULL, '145°', '180° - 35° = 145°', 'easy', 2, 15),
('nsmq_math_sr_019', 'subj_math', 'Express 0.125 as a fraction.', 'direct_answer', 'speed_race', NULL, '1/8', '0.125 = 125/1000 = 1/8', 'medium', 2, 15),
('nsmq_math_sr_020', 'subj_math', 'What is the area of a triangle with base 10 and height 6?', 'direct_answer', 'speed_race', NULL, '30', 'Area = ½ × 10 × 6 = 30', 'easy', 2, 15),
('nsmq_math_sr_021', 'subj_math', 'What is log₁₀(100)?', 'direct_answer', 'speed_race', NULL, '2', 'log₁₀(100) = log₁₀(10²) = 2', 'easy', 2, 15),
('nsmq_math_sr_022', 'subj_math', 'What is 1000 in Roman numerals?', 'direct_answer', 'speed_race', NULL, 'M', '1000 = M in Roman numerals', 'easy', 2, 15),
('nsmq_math_sr_023', 'subj_math', 'What is the cube root of 27?', 'direct_answer', 'speed_race', NULL, '3', '∛27 = 3', 'easy', 2, 15),
('nsmq_math_sr_024', 'subj_math', 'Simplify: 2³ × 2²', 'direct_answer', 'speed_race', NULL, '32', '2³⁺² = 2⁵ = 32', 'easy', 2, 15),
('nsmq_math_sr_025', 'subj_math', 'What is the 5th Fibonacci number?', 'direct_answer', 'speed_race', NULL, '5', 'Sequence: 1, 1, 2, 3, 5', 'medium', 2, 15),

-- PHYSICS Speed Race (25 questions)
('nsmq_phy_sr_001', 'subj_physics', 'What is the SI unit of force?', 'direct_answer', 'speed_race', NULL, 'Newton', 'Force is measured in Newtons (N)', 'easy', 2, 15),
('nsmq_phy_sr_002', 'subj_physics', 'What is the speed of sound in air (approximately)?', 'direct_answer', 'speed_race', NULL, '340 m/s', 'Speed of sound in air ≈ 340 m/s', 'easy', 2, 15),
('nsmq_phy_sr_003', 'subj_physics', 'What is the formula for pressure?', 'direct_answer', 'speed_race', NULL, 'P = F/A', 'Pressure = Force/Area', 'easy', 2, 15),
('nsmq_phy_sr_004', 'subj_physics', 'How many watts in a kilowatt?', 'direct_answer', 'speed_race', NULL, '1000', '1 kW = 1000 W', 'easy', 2, 15),
('nsmq_phy_sr_005', 'subj_physics', 'What is the unit of electrical resistance?', 'direct_answer', 'speed_race', NULL, 'Ohm', 'Resistance is measured in Ohms (Ω)', 'easy', 2, 15),
('nsmq_phy_sr_006', 'subj_physics', 'What is the acceleration of a body moving at constant velocity?', 'direct_answer', 'speed_race', NULL, '0', 'Constant velocity means zero acceleration', 'easy', 2, 15),
('nsmq_phy_sr_007', 'subj_physics', 'What is the unit of energy?', 'direct_answer', 'speed_race', NULL, 'Joule', 'Energy is measured in Joules (J)', 'easy', 2, 15),
('nsmq_phy_sr_008', 'subj_physics', 'What type of mirror is used in a car''s side mirror?', 'direct_answer', 'speed_race', NULL, 'Convex', 'Convex mirrors provide wider field of view', 'easy', 2, 15),
('nsmq_phy_sr_009', 'subj_physics', 'What is the boiling point of water in Kelvin?', 'direct_answer', 'speed_race', NULL, '373 K', '100°C + 273 = 373 K', 'easy', 2, 15),
('nsmq_phy_sr_010', 'subj_physics', 'What is the formula for work done?', 'direct_answer', 'speed_race', NULL, 'W = Fd', 'Work = Force × Distance', 'easy', 2, 15),
('nsmq_phy_sr_011', 'subj_physics', 'Name the particle that carries positive charge.', 'direct_answer', 'speed_race', NULL, 'Proton', 'Protons have positive charge', 'easy', 2, 15),
('nsmq_phy_sr_012', 'subj_physics', 'What is the unit of wavelength?', 'direct_answer', 'speed_race', NULL, 'Meter', 'Wavelength is measured in meters', 'easy', 2, 15),
('nsmq_phy_sr_013', 'subj_physics', 'What is 0°C in Kelvin?', 'direct_answer', 'speed_race', NULL, '273 K', '0°C = 273 K', 'easy', 2, 15),
('nsmq_phy_sr_014', 'subj_physics', 'What is the formula for density?', 'direct_answer', 'speed_race', NULL, 'ρ = m/V', 'Density = Mass/Volume', 'easy', 2, 15),
('nsmq_phy_sr_015', 'subj_physics', 'What is the angle of incidence when light falls perpendicular to a surface?', 'direct_answer', 'speed_race', NULL, '0°', 'Perpendicular incidence = 0° angle', 'easy', 2, 15),
('nsmq_phy_sr_016', 'subj_physics', 'What is the unit of capacitance?', 'direct_answer', 'speed_race', NULL, 'Farad', 'Capacitance is measured in Farads (F)', 'medium', 2, 15),
('nsmq_phy_sr_017', 'subj_physics', 'What is the mechanical advantage of a lever if effort = 10N and load = 50N?', 'direct_answer', 'speed_race', NULL, '5', 'MA = Load/Effort = 50/10 = 5', 'medium', 2, 15),
('nsmq_phy_sr_018', 'subj_physics', 'What is the unit of pressure in SI?', 'direct_answer', 'speed_race', NULL, 'Pascal', 'Pressure is measured in Pascals (Pa)', 'easy', 2, 15),
('nsmq_phy_sr_019', 'subj_physics', 'What device converts mechanical energy to electrical energy?', 'direct_answer', 'speed_race', NULL, 'Generator', 'Generators convert mechanical to electrical energy', 'easy', 2, 15),
('nsmq_phy_sr_020', 'subj_physics', 'What is the formula for momentum?', 'direct_answer', 'speed_race', NULL, 'p = mv', 'Momentum = mass × velocity', 'easy', 2, 15),
('nsmq_phy_sr_021', 'subj_physics', 'What is the power if 100J of work is done in 5 seconds?', 'direct_answer', 'speed_race', NULL, '20 W', 'Power = Work/Time = 100/5 = 20 W', 'easy', 2, 15),
('nsmq_phy_sr_022', 'subj_physics', 'What is the charge of an electron?', 'direct_answer', 'speed_race', NULL, '1.6 × 10⁻¹⁹ C', 'Electron charge = 1.6 × 10⁻¹⁹ C (negative)', 'medium', 2, 15),
('nsmq_phy_sr_023', 'subj_physics', 'What is the unit of electric potential?', 'direct_answer', 'speed_race', NULL, 'Volt', 'Electric potential is measured in Volts (V)', 'easy', 2, 15),
('nsmq_phy_sr_024', 'subj_physics', 'What is the total resistance of 3Ω and 6Ω in parallel?', 'direct_answer', 'speed_race', NULL, '2Ω', '1/R = 1/3 + 1/6 = 3/6, R = 2Ω', 'medium', 2, 15),
('nsmq_phy_sr_025', 'subj_physics', 'What phenomenon causes a pencil in water to appear bent?', 'direct_answer', 'speed_race', NULL, 'Refraction', 'Light bends when passing between media', 'easy', 2, 15),

-- CHEMISTRY Speed Race (25 questions)
('nsmq_chem_sr_001', 'subj_chemistry', 'What is the atomic number of hydrogen?', 'direct_answer', 'speed_race', NULL, '1', 'Hydrogen has 1 proton', 'easy', 2, 15),
('nsmq_chem_sr_002', 'subj_chemistry', 'What is the chemical symbol for gold?', 'direct_answer', 'speed_race', NULL, 'Au', 'Gold = Au (from Latin Aurum)', 'easy', 2, 15),
('nsmq_chem_sr_003', 'subj_chemistry', 'How many atoms are in one molecule of H₂O?', 'direct_answer', 'speed_race', NULL, '3', '2 hydrogen + 1 oxygen = 3 atoms', 'easy', 2, 15),
('nsmq_chem_sr_004', 'subj_chemistry', 'What is the formula for carbon dioxide?', 'direct_answer', 'speed_race', NULL, 'CO₂', 'Carbon dioxide = CO₂', 'easy', 2, 15),
('nsmq_chem_sr_005', 'subj_chemistry', 'What is the molar mass of NaCl?', 'direct_answer', 'speed_race', NULL, '58.5 g/mol', 'Na(23) + Cl(35.5) = 58.5 g/mol', 'medium', 2, 15),
('nsmq_chem_sr_006', 'subj_chemistry', 'What color does litmus paper turn in acid?', 'direct_answer', 'speed_race', NULL, 'Red', 'Blue litmus turns red in acid', 'easy', 2, 15),
('nsmq_chem_sr_007', 'subj_chemistry', 'What is the charge of a hydroxide ion?', 'direct_answer', 'speed_race', NULL, '-1', 'OH⁻ has a charge of -1', 'easy', 2, 15),
('nsmq_chem_sr_008', 'subj_chemistry', 'What is the percentage of oxygen in the atmosphere?', 'direct_answer', 'speed_race', NULL, '21%', 'Atmosphere is ~21% oxygen', 'easy', 2, 15),
('nsmq_chem_sr_009', 'subj_chemistry', 'What type of bond forms between Na and Cl?', 'direct_answer', 'speed_race', NULL, 'Ionic', 'NaCl has ionic bonding', 'easy', 2, 15),
('nsmq_chem_sr_010', 'subj_chemistry', 'What is the common name for sodium bicarbonate?', 'direct_answer', 'speed_race', NULL, 'Baking soda', 'NaHCO₃ = Baking soda', 'easy', 2, 15),
('nsmq_chem_sr_011', 'subj_chemistry', 'What is the atomic mass of carbon?', 'direct_answer', 'speed_race', NULL, '12', 'Carbon has atomic mass 12', 'easy', 2, 15),
('nsmq_chem_sr_012', 'subj_chemistry', 'What is the formula for methane?', 'direct_answer', 'speed_race', NULL, 'CH₄', 'Methane = CH₄', 'easy', 2, 15),
('nsmq_chem_sr_013', 'subj_chemistry', 'What is the product when an acid reacts with a base?', 'direct_answer', 'speed_race', NULL, 'Salt and water', 'Acid + Base → Salt + Water', 'easy', 2, 15),
('nsmq_chem_sr_014', 'subj_chemistry', 'What is the valency of carbon?', 'direct_answer', 'speed_race', NULL, '4', 'Carbon has valency 4', 'easy', 2, 15),
('nsmq_chem_sr_015', 'subj_chemistry', 'What gas is produced when HCl reacts with CaCO₃?', 'direct_answer', 'speed_race', NULL, 'CO₂', 'Carbon dioxide is released', 'easy', 2, 15),
('nsmq_chem_sr_016', 'subj_chemistry', 'What is the name of NaOH?', 'direct_answer', 'speed_race', NULL, 'Sodium hydroxide', 'NaOH = Sodium hydroxide', 'easy', 2, 15),
('nsmq_chem_sr_017', 'subj_chemistry', 'How many electrons are in the outer shell of a noble gas (except He)?', 'direct_answer', 'speed_race', NULL, '8', 'Noble gases have 8 valence electrons (octet)', 'easy', 2, 15),
('nsmq_chem_sr_018', 'subj_chemistry', 'What is the chemical symbol for potassium?', 'direct_answer', 'speed_race', NULL, 'K', 'Potassium = K (from Kalium)', 'easy', 2, 15),
('nsmq_chem_sr_019', 'subj_chemistry', 'What is the name of the process of removing impurities from crude oil?', 'direct_answer', 'speed_race', NULL, 'Fractional distillation', 'Crude oil is refined by fractional distillation', 'medium', 2, 15),
('nsmq_chem_sr_020', 'subj_chemistry', 'What is the formula for sulfur dioxide?', 'direct_answer', 'speed_race', NULL, 'SO₂', 'Sulfur dioxide = SO₂', 'easy', 2, 15),
('nsmq_chem_sr_021', 'subj_chemistry', 'What is the oxidation state of oxygen in most compounds?', 'direct_answer', 'speed_race', NULL, '-2', 'Oxygen is typically -2', 'easy', 2, 15),
('nsmq_chem_sr_022', 'subj_chemistry', 'What element has the symbol Fe?', 'direct_answer', 'speed_race', NULL, 'Iron', 'Fe = Iron (from Ferrum)', 'easy', 2, 15),
('nsmq_chem_sr_023', 'subj_chemistry', 'What is the molar mass of O₂?', 'direct_answer', 'speed_race', NULL, '32 g/mol', '16 × 2 = 32 g/mol', 'easy', 2, 15),
('nsmq_chem_sr_024', 'subj_chemistry', 'What color flame does sodium produce?', 'direct_answer', 'speed_race', NULL, 'Yellow', 'Sodium burns with yellow flame', 'easy', 2, 15),
('nsmq_chem_sr_025', 'subj_chemistry', 'What is the chemical formula of rust?', 'direct_answer', 'speed_race', NULL, 'Fe₂O₃', 'Rust is iron(III) oxide = Fe₂O₃', 'medium', 2, 15),

-- BIOLOGY Speed Race (25 questions)
('nsmq_bio_sr_001', 'subj_biology', 'How many chambers does the human heart have?', 'direct_answer', 'speed_race', NULL, '4', 'Heart has 4 chambers: 2 atria, 2 ventricles', 'easy', 2, 15),
('nsmq_bio_sr_002', 'subj_biology', 'What is the pigment that gives leaves their green color?', 'direct_answer', 'speed_race', NULL, 'Chlorophyll', 'Chlorophyll absorbs light for photosynthesis', 'easy', 2, 15),
('nsmq_bio_sr_003', 'subj_biology', 'What is the name of the gas released during photosynthesis?', 'direct_answer', 'speed_race', NULL, 'Oxygen', 'O₂ is released as a byproduct', 'easy', 2, 15),
('nsmq_bio_sr_004', 'subj_biology', 'What type of blood vessel carries blood away from the heart?', 'direct_answer', 'speed_race', NULL, 'Artery', 'Arteries carry blood away from heart', 'easy', 2, 15),
('nsmq_bio_sr_005', 'subj_biology', 'How many pairs of ribs do humans have?', 'direct_answer', 'speed_race', NULL, '12', 'Humans have 12 pairs of ribs', 'easy', 2, 15),
('nsmq_bio_sr_006', 'subj_biology', 'What is the scientific name for the windpipe?', 'direct_answer', 'speed_race', NULL, 'Trachea', 'The windpipe is called the trachea', 'easy', 2, 15),
('nsmq_bio_sr_007', 'subj_biology', 'What is the term for animals that eat only plants?', 'direct_answer', 'speed_race', NULL, 'Herbivore', 'Herbivores are plant-eaters', 'easy', 2, 15),
('nsmq_bio_sr_008', 'subj_biology', 'What structure in the eye controls the amount of light entering?', 'direct_answer', 'speed_race', NULL, 'Iris', 'The iris controls pupil size', 'easy', 2, 15),
('nsmq_bio_sr_009', 'subj_biology', 'What is the normal body temperature in Celsius?', 'direct_answer', 'speed_race', NULL, '37°C', 'Normal body temperature is 37°C', 'easy', 2, 15),
('nsmq_bio_sr_010', 'subj_biology', 'What is the main organ of the excretory system?', 'direct_answer', 'speed_race', NULL, 'Kidney', 'Kidneys filter blood and produce urine', 'easy', 2, 15),
('nsmq_bio_sr_011', 'subj_biology', 'What connects muscle to bone?', 'direct_answer', 'speed_race', NULL, 'Tendon', 'Tendons connect muscles to bones', 'easy', 2, 15),
('nsmq_bio_sr_012', 'subj_biology', 'What is the name of the process by which cells divide?', 'direct_answer', 'speed_race', NULL, 'Mitosis', 'Mitosis is cell division for growth', 'easy', 2, 15),
('nsmq_bio_sr_013', 'subj_biology', 'What type of joint is the knee?', 'direct_answer', 'speed_race', NULL, 'Hinge joint', 'The knee is a hinge joint', 'easy', 2, 15),
('nsmq_bio_sr_014', 'subj_biology', 'What is the longest bone in the human body?', 'direct_answer', 'speed_race', NULL, 'Femur', 'The thigh bone (femur) is the longest', 'easy', 2, 15),
('nsmq_bio_sr_015', 'subj_biology', 'What is the term for the protective covering of nerve fibers?', 'direct_answer', 'speed_race', NULL, 'Myelin sheath', 'Myelin sheath insulates nerve fibers', 'medium', 2, 15),
('nsmq_bio_sr_016', 'subj_biology', 'What organelle is responsible for protein synthesis?', 'direct_answer', 'speed_race', NULL, 'Ribosome', 'Ribosomes synthesize proteins', 'easy', 2, 15),
('nsmq_bio_sr_017', 'subj_biology', 'What is the main function of the large intestine?', 'direct_answer', 'speed_race', NULL, 'Water absorption', 'Large intestine absorbs water from waste', 'easy', 2, 15),
('nsmq_bio_sr_018', 'subj_biology', 'How many bones are in the adult human body?', 'direct_answer', 'speed_race', NULL, '206', 'Adults have 206 bones', 'easy', 2, 15),
('nsmq_bio_sr_019', 'subj_biology', 'What is the liquid part of blood called?', 'direct_answer', 'speed_race', NULL, 'Plasma', 'Plasma is the liquid component of blood', 'easy', 2, 15),
('nsmq_bio_sr_020', 'subj_biology', 'What connects bone to bone?', 'direct_answer', 'speed_race', NULL, 'Ligament', 'Ligaments connect bones at joints', 'easy', 2, 15),
('nsmq_bio_sr_021', 'subj_biology', 'What is the male reproductive cell called?', 'direct_answer', 'speed_race', NULL, 'Sperm', 'Sperm is the male gamete', 'easy', 2, 15),
('nsmq_bio_sr_022', 'subj_biology', 'What is the main function of the liver?', 'direct_answer', 'speed_race', NULL, 'Detoxification', 'Liver detoxifies blood and produces bile', 'medium', 2, 15),
('nsmq_bio_sr_023', 'subj_biology', 'What is the scientific term for the collarbone?', 'direct_answer', 'speed_race', NULL, 'Clavicle', 'Collarbone = Clavicle', 'easy', 2, 15),
('nsmq_bio_sr_024', 'subj_biology', 'What is the outermost layer of the skin called?', 'direct_answer', 'speed_race', NULL, 'Epidermis', 'Epidermis is the outer skin layer', 'easy', 2, 15),
('nsmq_bio_sr_025', 'subj_biology', 'What is the term for an organism that lives on or in another organism?', 'direct_answer', 'speed_race', NULL, 'Parasite', 'Parasites depend on host organisms', 'easy', 2, 15);
