-- 119: BrillaPrep WASSCE beta blueprint specifications for IRS and transitional Applied Electricity.
-- These are internal evidence blueprints, not official WAEC specification records.
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO exam_boards (id, name, code, full_name, region, website_url, is_active, display_order) VALUES ('board_waec', 'WAEC', 'WAEC', 'West African Examinations Council', 'West Africa', 'https://waecgh.org/', 1, 1);
INSERT OR IGNORE INTO subject_specifications (id, exam_board_id, subject_id, exam_type_id, syllabus_code, syllabus_name, specification_year, valid_from, syllabus_pdf_url, total_papers, assessment_info, is_active, display_order) VALUES ('spec_wassce_irs_brilla_b001', 'board_waec', 'subj_wassce_irs', 'exam_wassce', 'BRILLA-WASSCE-IRS-BETA-001', 'BrillaPrep IRS beta content blueprint', NULL, NULL, 'https://waecgh.org/home/wassce-school/', 0, 'Internal BrillaPrep evidence blueprint for a current WASSCE subject. It does not claim an official syllabus code, validity date or paper structure.', 1, 1);
INSERT OR IGNORE INTO subject_specifications (id, exam_board_id, subject_id, exam_type_id, syllabus_code, syllabus_name, specification_year, valid_from, syllabus_pdf_url, total_papers, assessment_info, is_active, display_order) VALUES ('spec_wassce_elect_app_brilla_b001', 'board_waec', 'subj_wassce_elect_app', 'exam_wassce', 'BRILLA-WASSCE-AEL-BETA-001', 'BrillaPrep transitional Applied Electricity beta content blueprint', NULL, NULL, 'https://waecgh.org/wp-content/uploads/2026/03/FINAL-TIMETABLE-FOR-WASSCE-SC-2026-GHANA-ONLY-NEW-TAD.pdf', 0, 'Internal BrillaPrep evidence blueprint for the outgoing Applied Electricity track examined during Ghana curriculum transition. New-curriculum learners use Applied Technology III (Electrical and Electronic Technology).', 1, 1);
CREATE TABLE IF NOT EXISTS _migration_119_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _migration_119_guard;
INSERT INTO _migration_119_guard(valid) SELECT CASE WHEN EXISTS (SELECT 1 FROM subject_specifications WHERE id = 'spec_wassce_irs_brilla_b001' AND exam_board_id IS 'board_waec' AND subject_id IS 'subj_wassce_irs' AND exam_type_id IS 'exam_wassce' AND syllabus_code IS 'BRILLA-WASSCE-IRS-BETA-001' AND syllabus_name IS 'BrillaPrep IRS beta content blueprint' AND specification_year IS NULL AND valid_from IS NULL AND syllabus_pdf_url IS 'https://waecgh.org/home/wassce-school/' AND total_papers IS 0 AND assessment_info IS 'Internal BrillaPrep evidence blueprint for a current WASSCE subject. It does not claim an official syllabus code, validity date or paper structure.' AND is_active IS 1) THEN 1 ELSE 0 END;
INSERT INTO _migration_119_guard(valid) SELECT CASE WHEN EXISTS (SELECT 1 FROM subject_specifications WHERE id = 'spec_wassce_elect_app_brilla_b001' AND exam_board_id IS 'board_waec' AND subject_id IS 'subj_wassce_elect_app' AND exam_type_id IS 'exam_wassce' AND syllabus_code IS 'BRILLA-WASSCE-AEL-BETA-001' AND syllabus_name IS 'BrillaPrep transitional Applied Electricity beta content blueprint' AND specification_year IS NULL AND valid_from IS NULL AND syllabus_pdf_url IS 'https://waecgh.org/wp-content/uploads/2026/03/FINAL-TIMETABLE-FOR-WASSCE-SC-2026-GHANA-ONLY-NEW-TAD.pdf' AND total_papers IS 0 AND assessment_info IS 'Internal BrillaPrep evidence blueprint for the outgoing Applied Electricity track examined during Ghana curriculum transition. New-curriculum learners use Applied Technology III (Electrical and Electronic Technology).' AND is_active IS 1) THEN 1 ELSE 0 END;
DROP TABLE _migration_119_guard;
