-- 246: Original BrillaPrep BECE gap beta questions, subj_bece_science, part 2.
-- Curriculum-blueprint-aligned practice; not official WAEC or NaCCA examination material.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS _expected_246 (question_id TEXT PRIMARY KEY, topic_id TEXT NOT NULL, subject_id TEXT NOT NULL, exam_type_id TEXT NOT NULL, question_text TEXT NOT NULL, question_type TEXT NOT NULL, options TEXT NOT NULL, correct_answer TEXT NOT NULL, explanation TEXT NOT NULL, difficulty TEXT NOT NULL, points INTEGER NOT NULL, marks INTEGER NOT NULL, time_limit INTEGER NOT NULL, command_word TEXT NOT NULL, assessment_objective TEXT NOT NULL);
DELETE FROM _expected_246;
INSERT INTO _expected_246(question_id,topic_id,subject_id,exam_type_id,question_text,question_type,options,correct_answer,explanation,difficulty,points,marks,time_limit,command_word,assessment_objective) VALUES
  ('q_bece_science_agric_b001_011','topic_bece_science_agric','subj_bece_science','exam_bece','Why are seedlings hardened before transplanting?','multiple_choice','["A. To stop all future growth","B. To prepare them gradually for harsher field conditions","C. To remove their roots","D. To make watering impossible"]','B','Gradual exposure to lower water, greater light and wind reduces transplant shock when protected seedlings move to the field. Therefore the correct answer is B: To prepare them gradually for harsher field conditions.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_science_agric_b001_012','topic_bece_science_agric','subj_bece_science','exam_bece','Which irrigation method delivers water near individual plant roots through small outlets?','multiple_choice','["A. Broadcast burning","B. Drip irrigation","C. Wind erosion","D. Dry threshing"]','B','Drip systems apply controlled amounts near root zones, reducing evaporation and runoff when designed and maintained correctly. Therefore the correct answer is B: Drip irrigation.','easy',1,1,90,'Identify','AO1'),
  ('q_bece_science_agric_b001_013','topic_bece_science_agric','subj_bece_science','exam_bece','Why is field drainage important after heavy rain?','multiple_choice','["A. It prevents prolonged waterlogging and root oxygen shortage","B. It keeps roots permanently submerged","C. It removes every nutrient instantly","D. It guarantees drought"]','A','Excess water fills soil pores and restricts oxygen needed for root respiration, so drainage protects many crops from waterlogging. Therefore the correct answer is A: It prevents prolonged waterlogging and root oxygen shortage.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_science_agric_b001_014','topic_bece_science_agric','subj_bece_science','exam_bece','Why should weeds be controlled early?','multiple_choice','["A. They always improve crop yield","B. They prevent every disease","C. They compete with young crops for light, water and nutrients","D. They manufacture fertiliser"]','C','Young crops are vulnerable to competition; early control helps the intended plants establish before weeds capture limited resources. Therefore the correct answer is C: They compete with young crops for light, water and nutrients.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_science_agric_b001_015','topic_bece_science_agric','subj_bece_science','exam_bece','Monitoring shows a few leaf-eating insects but damage remains below the action threshold. What fits integrated pest management?','multiple_choice','["A. Apply the highest pesticide dose immediately","B. Destroy beneficial insects around the crop","C. Ignore future changes in pest numbers","D. Continue monitoring and avoid an unnecessary pesticide treatment"]','D','Integrated pest management uses monitoring and action thresholds so control is applied only when justified, conserving beneficial organisms and avoiding needless pesticide exposure. Therefore the correct answer is D: Continue monitoring and avoid an unnecessary pesticide treatment.','hard',1,1,90,'Apply','AO3'),
  ('q_bece_science_agric_b001_016','topic_bece_science_agric','subj_bece_science','exam_bece','Which practice is safest when applying an approved pesticide?','multiple_choice','["A. Mix with bare hands","B. Spray against strong wind","C. Follow the label and use specified protective equipment","D. Store it in a drink bottle"]','C','The label defines dose, protection, timing and disposal requirements that reduce exposure, residues and environmental harm. Therefore the correct answer is C: Follow the label and use specified protective equipment.','hard',1,1,90,'Apply','AO3'),
  ('q_bece_science_agric_b001_017','topic_bece_science_agric','subj_bece_science','exam_bece','Which tool is most suitable for loosening soil around established plants?','multiple_choice','["A. A thermometer","B. A measuring cylinder","C. A soldering iron","D. A hand fork"]','D','A hand fork loosens and aerates small soil areas with controlled movement, reducing the chance of severe root damage. Therefore the correct answer is D: A hand fork.','easy',1,1,90,'Select','AO1'),
  ('q_bece_science_agric_b001_018','topic_bece_science_agric','subj_bece_science','exam_bece','Why should farm tools be cleaned and dried after use?','multiple_choice','["A. To reduce corrosion, contamination and premature wear","B. To make blades permanently blunt","C. To increase soil on metal","D. To avoid safe storage"]','A','Removing soil and moisture limits rust and transfer of pests, while inspection after cleaning reveals damage needing repair. Therefore the correct answer is A: To reduce corrosion, contamination and premature wear.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_science_agric_b001_019','topic_bece_science_agric','subj_bece_science','exam_bece','A farmer feeds growing chicks only crushed maize. Which change would make the ration more balanced?','multiple_choice','["A. Remove water so the maize is concentrated","B. Add suitable protein, mineral and vitamin sources and provide clean water","C. Use the same maize-only ration for every production stage","D. Choose ingredients only by their colour"]','B','Maize supplies much of the energy but growing chicks also need adequate protein, minerals, vitamins and water in proportions suited to their age and production needs. Therefore the correct answer is B: Add suitable protein, mineral and vitamin sources and provide clean water.','medium',1,1,90,'Apply','AO2'),
  ('q_bece_science_agric_b001_020','topic_bece_science_agric','subj_bece_science','exam_bece','Why must livestock housing be ventilated?','multiple_choice','["A. To remove excess heat, moisture and harmful gases","B. To create permanent darkness","C. To stop all air movement","D. To increase ammonia buildup"]','A','Ventilation supplies fresh air and reduces heat, humidity and gases that can stress animals and promote respiratory disease. Therefore the correct answer is A: To remove excess heat, moisture and harmful gases.','medium',1,1,90,'Explain','AO2');
CREATE TABLE IF NOT EXISTS _migration_246_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _migration_246_guard;
INSERT INTO _migration_246_guard(valid) SELECT CASE WHEN
  (SELECT COUNT(*) FROM _expected_246) = 10
  AND NOT EXISTS (SELECT 1 FROM _expected_246 e LEFT JOIN topics t ON t.id=e.topic_id LEFT JOIN subjects s ON s.id=t.subject_id WHERE t.id IS NULL OR t.subject_id IS NOT e.subject_id OR s.exam_type_id IS NOT e.exam_type_id)
  AND NOT EXISTS (SELECT 1 FROM questions q JOIN _expected_246 e ON e.question_id=q.id WHERE NOT (q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective))
  AND NOT EXISTS (SELECT 1 FROM question_content_releases r JOIN _expected_246 e ON e.question_id=r.question_id WHERE NOT (r.batch_id IS 'bece-science-agric-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1))
  AND NOT EXISTS (SELECT 1 FROM question_bank_remediation_log l JOIN _expected_246 e ON e.question_id=l.entity_id WHERE l.migration_id='246_bece_science_agric_beta_part_2' AND NOT (l.migration_id IS '246_bece_science_agric_beta_part_2' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-science-agric-beta-001'))
  AND (((SELECT COUNT(*) FROM questions q JOIN _expected_246 e ON e.question_id=q.id)=0 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_246 e ON e.question_id=r.question_id)=0 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_246 e ON e.question_id=l.entity_id WHERE l.migration_id='246_bece_science_agric_beta_part_2') IN (0,10))
    OR ((SELECT COUNT(*) FROM questions q JOIN _expected_246 e ON e.question_id=q.id WHERE q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective)=10 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_246 e ON e.question_id=r.question_id WHERE r.batch_id IS 'bece-science-agric-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1)=10 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_246 e ON e.question_id=l.entity_id WHERE l.migration_id IS '246_bece_science_agric_beta_part_2' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-science-agric-beta-001')=10))
THEN 1 ELSE 0 END;
INSERT OR IGNORE INTO questions (id,topic_id,subject_id,exam_type_id,question_text,question_type,options,correct_answer,explanation,difficulty,points,marks,time_limit,command_word,assessment_objective) SELECT question_id,topic_id,subject_id,exam_type_id,question_text,question_type,options,correct_answer,explanation,difficulty,points,marks,time_limit,command_word,assessment_objective FROM _expected_246;
INSERT OR IGNORE INTO question_content_releases (question_id,batch_id,quality_assurance,release_channel,content_label,source_url,official_exam_board_content,feedback_enabled) SELECT q.id,'bece-science-agric-beta-001','automated_beta','beta','Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.','https://nacca.gov.gh/common-core-programme-ccp/',0,1 FROM questions q JOIN _expected_246 e ON e.question_id=q.id;
INSERT OR IGNORE INTO question_bank_remediation_log (migration_id,entity_type,entity_id,field_name,old_value,new_value) SELECT '246_bece_science_agric_beta_part_2','question',q.id,'insert',NULL,'bece-science-agric-beta-001' FROM questions q JOIN _expected_246 e ON e.question_id=q.id;
INSERT INTO _migration_246_guard(valid) SELECT CASE WHEN
  (SELECT COUNT(*) FROM questions q JOIN _expected_246 e ON e.question_id=q.id WHERE q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective)=10
  AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_246 e ON e.question_id=r.question_id WHERE r.batch_id IS 'bece-science-agric-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1)=10
  AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_246 e ON e.question_id=l.entity_id WHERE l.migration_id IS '246_bece_science_agric_beta_part_2' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-science-agric-beta-001')=10
  AND NOT EXISTS (SELECT 1 FROM questions q JOIN _expected_246 e ON e.question_id=q.id JOIN questions other ON other.id IS NOT q.id AND lower(trim(other.question_text))=lower(trim(q.question_text)))
THEN 1 ELSE 0 END;
DROP TABLE _expected_246;
DROP TABLE _migration_246_guard;
