-- 381: Original BrillaPrep flashcards, batch flashcards-beta-001, part 1 of 5.
-- Curriculum-aligned revision content; not official WAEC or NaCCA examination material.
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_01', 'deck_sys_topic_algebra', 'What is a variable in algebra?', 'A symbol (usually a letter such as x or y) that represents an unknown or changeable numerical value.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_02', 'deck_sys_topic_algebra', 'What are like terms?', 'Terms that have exactly the same variable(s) raised to the same power(s); only like terms can be combined by adding or subtracting their coefficients, e.g. 3x² and 5x².', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_03', 'deck_sys_topic_algebra', 'Expand (a + b)².', 'a² + 2ab + b²', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_04', 'deck_sys_topic_algebra', 'Expand (a − b)².', 'a² − 2ab + b²', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_05', 'deck_sys_topic_algebra', 'Factorise a² − b².', '(a + b)(a − b) — the difference of two squares.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_06', 'deck_sys_topic_algebra', 'Solve for x: ax + b = c.', 'x = (c − b)/a, provided a ≠ 0. Subtract b from both sides, then divide by a.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_07', 'deck_sys_topic_algebra', 'What is a polynomial?', 'An algebraic expression consisting of variables and coefficients combined using only addition, subtraction, multiplication and non-negative integer exponents, e.g. 3x² − 2x + 5.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_08', 'deck_sys_topic_algebra', 'What is the degree of a polynomial?', 'The highest power (exponent) of the variable in the polynomial; for example, 4x³ + x − 7 has degree 3.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_09', 'deck_sys_topic_algebra', 'What is a function?', 'A relation that assigns exactly one output value to each input value; written f(x), where x is the input (argument).', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_algebra_10', 'deck_sys_topic_algebra', 'Solve: 2(x − 3) = 10.', 'x = 8. Divide both sides by 2 to get x − 3 = 5, then add 3 to both sides.', NULL, 'Clear the bracket first.', 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_01', 'deck_sys_topic_trigonometry', 'In a right-angled triangle, how is sin θ defined?', 'sin θ = opposite / hypotenuse.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_02', 'deck_sys_topic_trigonometry', 'In a right-angled triangle, how is cos θ defined?', 'cos θ = adjacent / hypotenuse.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_03', 'deck_sys_topic_trigonometry', 'In a right-angled triangle, how is tan θ defined?', 'tan θ = opposite / adjacent, which equals sin θ / cos θ.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_04', 'deck_sys_topic_trigonometry', 'State the identity linking sin θ and cos θ.', 'sin²θ + cos²θ = 1 for every angle θ (the Pythagorean identity).', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_05', 'deck_sys_topic_trigonometry', 'What is the double-angle formula for sin 2θ?', 'sin 2θ = 2 sin θ cos θ.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_06', 'deck_sys_topic_trigonometry', 'What is the double-angle formula for cos 2θ?', 'cos 2θ = cos²θ − sin²θ, equivalently 2cos²θ − 1 or 1 − 2sin²θ.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_07', 'deck_sys_topic_trigonometry', 'Convert 60° to radians.', 'π/3 radians, since 180° = π radians, so 60° = 60π/180 = π/3.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_08', 'deck_sys_topic_trigonometry', 'State the sine rule for any triangle.', 'a/sin A = b/sin B = c/sin C, where side a is opposite angle A, and so on.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_09', 'deck_sys_topic_trigonometry', 'State the cosine rule for any triangle.', 'a² = b² + c² − 2bc cos A, where side a is opposite angle A.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_trigonometry_10', 'deck_sys_topic_trigonometry', 'What is the period of y = sin θ?', '360° (2π radians): the sine graph repeats one full wave every 360°.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_mechanics_01', 'deck_sys_topic_mechanics', 'State Newton’s first law of motion.', 'A body remains at rest or continues in uniform motion in a straight line unless acted upon by a resultant external force (the law of inertia).', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_mechanics_02', 'deck_sys_topic_mechanics', 'State Newton’s second law of motion.', 'The resultant force on a body equals the rate of change of its momentum; for constant mass this reduces to F = ma.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_mechanics_03', 'deck_sys_topic_mechanics', 'State Newton’s third law of motion.', 'For every action there is an equal and opposite reaction: the forces two bodies exert on each other are equal in magnitude and opposite in direction.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b001_mechanics_04', 'deck_sys_topic_mechanics', 'In v = u + at, what does each symbol represent?', 'u = initial velocity, v = final velocity, a = constant acceleration, t = time taken. The equation gives the velocity after accelerating for time t.', NULL, NULL, 1);
