-- 465: Original BrillaPrep WASSCE Integrated Science Ecosystems practice questions (batch wassce-int-science-sprint2-001).
-- Curriculum-aligned practice content; not official WAEC examination material.
PRAGMA foreign_keys = ON;
CREATE TABLE _migration_465_expected (id TEXT PRIMARY KEY, topic_id TEXT, subject_id TEXT, exam_type_id TEXT, paper_type_id TEXT, past_paper_id TEXT, question_text TEXT, question_type TEXT, round_type TEXT, options TEXT, correct_answer TEXT, explanation TEXT, difficulty TEXT, points INTEGER, marks INTEGER, time_limit INTEGER, question_number INTEGER, section TEXT, is_compulsory INTEGER, image_url TEXT, syllabus_topic_id TEXT, command_word TEXT, assessment_objective TEXT, source_paper_code TEXT, source_question_number TEXT, exam_board_id TEXT);
INSERT INTO _migration_465_expected (id, topic_id, subject_id, exam_type_id, paper_type_id, past_paper_id, question_text, question_type, round_type, options, correct_answer, explanation, difficulty, points, marks, time_limit, question_number, section, is_compulsory, image_url, syllabus_topic_id, command_word, assessment_objective, source_paper_code, source_question_number, exam_board_id) VALUES ('q_wisc_eco_b002_001', 'topic_wassce_p2_sci_eco', 'subj_wassce_int_science', 'exam_wassce', NULL, NULL, 'In the food chain grass to grasscutter to hawk, only about 10% of the energy passes from one level to the next mainly because', 'multiple_choice', NULL, '["A. most of the energy is lost as heat in respiration and in undigested remains at each level","B. hawks refuse to eat weak grasscutters","C. grass uses up all the sunlight before animals can graze","D. energy increases as it moves up the food chain"]', 'A', 'At each trophic level organisms use most of their energy in respiration, movement and reproduction, and some energy is lost in faeces and unconsumed parts; only roughly 10% is stored as biomass that the next level can eat, which is why food chains rarely exceed four or five levels. Therefore the correct answer is A: most of the energy is lost as heat in respiration and in undigested remains at each level.', 'hard', '3', '1', '45', NULL, NULL, '1', NULL, NULL, 'Explain', 'AO3', NULL, NULL, NULL),
('q_wisc_eco_b002_002', 'topic_wassce_p2_sci_eco', 'subj_wassce_int_science', 'exam_wassce', NULL, NULL, 'Decomposers such as fungi and bacteria are essential to an ecosystem because they', 'multiple_choice', NULL, '["A. produce oxygen for animals by photosynthesis","B. release nutrients from dead organisms back into the soil for producers to absorb","C. control the population of hawks and other top predators","D. convert sunlight directly into chemical energy"]', 'B', 'Decomposers break down dead plants and animals and mineralise the organic matter, returning nitrates, phosphates and other ions to the soil where producers absorb them again; without decomposers, nutrients would stay locked in corpses and the nutrient cycle would halt. They neither photosynthesise nor control predators. Therefore the correct answer is B: release nutrients from dead organisms back into the soil for producers to absorb.', 'hard', '3', '1', '45', NULL, NULL, '1', NULL, NULL, 'Explain', 'AO3', NULL, NULL, NULL);
CREATE TABLE _migration_465_expected_parts (id TEXT PRIMARY KEY, question_id TEXT NOT NULL, part_label TEXT NOT NULL, part_text TEXT NOT NULL, marks INTEGER NOT NULL, correct_answer TEXT NOT NULL, display_order INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS _migration_465_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _migration_465_guard;
INSERT INTO _migration_465_guard(valid) SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM _migration_465_expected e JOIN questions q ON q.id = e.id WHERE NOT (q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.paper_type_id IS e.paper_type_id AND q.past_paper_id IS e.past_paper_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.round_type IS e.round_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.question_number IS e.question_number AND q.section IS e.section AND q.is_compulsory IS e.is_compulsory AND q.image_url IS e.image_url AND q.syllabus_topic_id IS e.syllabus_topic_id AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective AND q.source_paper_code IS e.source_paper_code AND q.source_question_number IS e.source_question_number AND q.exam_board_id IS e.exam_board_id)) AND NOT EXISTS (SELECT 1 FROM _migration_465_expected e JOIN question_content_releases r ON r.question_id = e.id WHERE NOT (r.batch_id IS 'wassce-int-science-sprint2-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep curriculum-aligned WASSCE Integrated Science practice; not official WAEC examination material.' AND r.source_url IS 'https://nacca.gov.gh/secondary-education-curriculum/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1)) THEN 1 ELSE 0 END;
INSERT INTO questions (id, topic_id, subject_id, exam_type_id, paper_type_id, past_paper_id, question_text, question_type, round_type, options, correct_answer, explanation, difficulty, points, marks, time_limit, question_number, section, is_compulsory, image_url, syllabus_topic_id, command_word, assessment_objective, source_paper_code, source_question_number, exam_board_id) SELECT id, topic_id, subject_id, exam_type_id, paper_type_id, past_paper_id, question_text, question_type, round_type, options, correct_answer, explanation, difficulty, points, marks, time_limit, question_number, section, is_compulsory, image_url, syllabus_topic_id, command_word, assessment_objective, source_paper_code, source_question_number, exam_board_id FROM _migration_465_expected e WHERE NOT EXISTS (SELECT 1 FROM questions q WHERE q.id = e.id);
INSERT INTO question_content_releases (question_id, batch_id, quality_assurance, release_channel, content_label, source_url, official_exam_board_content, feedback_enabled) SELECT e.id, 'wassce-int-science-sprint2-001', 'automated_beta', 'beta', 'Original BrillaPrep curriculum-aligned WASSCE Integrated Science practice; not official WAEC examination material.', 'https://nacca.gov.gh/secondary-education-curriculum/', 0, 1 FROM _migration_465_expected e WHERE NOT EXISTS (SELECT 1 FROM question_content_releases r WHERE r.question_id = e.id);
DELETE FROM _migration_465_guard;
INSERT INTO _migration_465_guard(valid) SELECT CASE WHEN (SELECT COUNT(*) FROM questions q JOIN _migration_465_expected e ON e.id = q.id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.paper_type_id IS e.paper_type_id AND q.past_paper_id IS e.past_paper_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.round_type IS e.round_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.question_number IS e.question_number AND q.section IS e.section AND q.is_compulsory IS e.is_compulsory AND q.image_url IS e.image_url AND q.syllabus_topic_id IS e.syllabus_topic_id AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective AND q.source_paper_code IS e.source_paper_code AND q.source_question_number IS e.source_question_number AND q.exam_board_id IS e.exam_board_id) = 2 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _migration_465_expected e ON e.id = r.question_id WHERE r.batch_id IS 'wassce-int-science-sprint2-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep curriculum-aligned WASSCE Integrated Science practice; not official WAEC examination material.' AND r.source_url IS 'https://nacca.gov.gh/secondary-education-curriculum/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1) = 2 AND (SELECT COUNT(*) FROM questions q JOIN topics t ON t.id = q.topic_id AND t.subject_id = q.subject_id JOIN _migration_465_expected e ON e.id = q.id) = 2 AND (SELECT COUNT(*) FROM structured_question_parts sp JOIN _migration_465_expected_parts p ON p.id = sp.id AND sp.id IS p.id AND sp.question_id IS p.question_id AND sp.part_label IS p.part_label AND sp.part_text IS p.part_text AND sp.marks IS p.marks AND sp.correct_answer IS p.correct_answer AND sp.display_order IS p.display_order) = 0 THEN 1 ELSE 0 END;
DROP TABLE _migration_465_guard;
DROP TABLE _migration_465_expected;
DROP TABLE _migration_465_expected_parts;
