-- 466: Original BrillaPrep WASSCE Integrated Science Matter and mixtures practice questions (batch wassce-int-science-sprint2-001).
-- Curriculum-aligned practice content; not official WAEC examination material.
PRAGMA foreign_keys = ON;
CREATE TABLE _migration_466_expected (id TEXT PRIMARY KEY, topic_id TEXT, subject_id TEXT, exam_type_id TEXT, paper_type_id TEXT, past_paper_id TEXT, question_text TEXT, question_type TEXT, round_type TEXT, options TEXT, correct_answer TEXT, explanation TEXT, difficulty TEXT, points INTEGER, marks INTEGER, time_limit INTEGER, question_number INTEGER, section TEXT, is_compulsory INTEGER, image_url TEXT, syllabus_topic_id TEXT, command_word TEXT, assessment_objective TEXT, source_paper_code TEXT, source_question_number TEXT, exam_board_id TEXT);
INSERT INTO _migration_466_expected (id, topic_id, subject_id, exam_type_id, paper_type_id, past_paper_id, question_text, question_type, round_type, options, correct_answer, explanation, difficulty, points, marks, time_limit, question_number, section, is_compulsory, image_url, syllabus_topic_id, command_word, assessment_objective, source_paper_code, source_question_number, exam_board_id) VALUES ('q_wisc_mat_b002_001', 'topic_wassce_p2_sci_mat', 'subj_wassce_int_science', 'exam_wassce', NULL, NULL, 'The best method for separating a mixture of ethanol (boiling point 78 degrees Celsius) and water is', 'multiple_choice', NULL, '["A. paper filtration","B. evaporation to dryness","C. fractional distillation","D. paper chromatography"]', 'C', 'Ethanol and water are miscible liquids with different but close boiling points, so a fractionating column is used to separate them cleanly as their vapours condense at different heights; filtration cannot separate dissolved or miscible components, evaporation to dryness loses both liquids, and chromatography suits small samples of coloured mixtures, not bulk liquids. Therefore the correct answer is C: fractional distillation.', 'hard', '3', '1', '45', NULL, NULL, '1', NULL, NULL, 'Select', 'AO3', NULL, NULL, NULL),
('q_wisc_mat_b002_002', 'topic_wassce_p2_sci_mat', 'subj_wassce_int_science', 'exam_wassce', NULL, NULL, 'In paper chromatography, a component of a mixture moves furthest up the paper when it', 'multiple_choice', NULL, '["A. has the largest and heaviest molecules in the mixture","B. is the most abundant component of the mixture","C. has the deepest colour of all the components","D. is most soluble in the solvent and least strongly adsorbed onto the paper"]', 'D', 'Each component partitions between the moving solvent and the stationary paper: a substance that dissolves readily in the solvent and clings weakly to the paper travels furthest. Molecular size alone, abundance and colour depth do not determine the distance moved. Therefore the correct answer is D: is most soluble in the solvent and least strongly adsorbed onto the paper.', 'hard', '3', '1', '45', NULL, NULL, '1', NULL, NULL, 'Explain', 'AO3', NULL, NULL, NULL);
CREATE TABLE _migration_466_expected_parts (id TEXT PRIMARY KEY, question_id TEXT NOT NULL, part_label TEXT NOT NULL, part_text TEXT NOT NULL, marks INTEGER NOT NULL, correct_answer TEXT NOT NULL, display_order INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS _migration_466_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _migration_466_guard;
INSERT INTO _migration_466_guard(valid) SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM _migration_466_expected e JOIN questions q ON q.id = e.id WHERE NOT (q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.paper_type_id IS e.paper_type_id AND q.past_paper_id IS e.past_paper_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.round_type IS e.round_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.question_number IS e.question_number AND q.section IS e.section AND q.is_compulsory IS e.is_compulsory AND q.image_url IS e.image_url AND q.syllabus_topic_id IS e.syllabus_topic_id AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective AND q.source_paper_code IS e.source_paper_code AND q.source_question_number IS e.source_question_number AND q.exam_board_id IS e.exam_board_id)) AND NOT EXISTS (SELECT 1 FROM _migration_466_expected e JOIN question_content_releases r ON r.question_id = e.id WHERE NOT (r.batch_id IS 'wassce-int-science-sprint2-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep curriculum-aligned WASSCE Integrated Science practice; not official WAEC examination material.' AND r.source_url IS 'https://nacca.gov.gh/secondary-education-curriculum/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1)) THEN 1 ELSE 0 END;
INSERT INTO questions (id, topic_id, subject_id, exam_type_id, paper_type_id, past_paper_id, question_text, question_type, round_type, options, correct_answer, explanation, difficulty, points, marks, time_limit, question_number, section, is_compulsory, image_url, syllabus_topic_id, command_word, assessment_objective, source_paper_code, source_question_number, exam_board_id) SELECT id, topic_id, subject_id, exam_type_id, paper_type_id, past_paper_id, question_text, question_type, round_type, options, correct_answer, explanation, difficulty, points, marks, time_limit, question_number, section, is_compulsory, image_url, syllabus_topic_id, command_word, assessment_objective, source_paper_code, source_question_number, exam_board_id FROM _migration_466_expected e WHERE NOT EXISTS (SELECT 1 FROM questions q WHERE q.id = e.id);
INSERT INTO question_content_releases (question_id, batch_id, quality_assurance, release_channel, content_label, source_url, official_exam_board_content, feedback_enabled) SELECT e.id, 'wassce-int-science-sprint2-001', 'automated_beta', 'beta', 'Original BrillaPrep curriculum-aligned WASSCE Integrated Science practice; not official WAEC examination material.', 'https://nacca.gov.gh/secondary-education-curriculum/', 0, 1 FROM _migration_466_expected e WHERE NOT EXISTS (SELECT 1 FROM question_content_releases r WHERE r.question_id = e.id);
DELETE FROM _migration_466_guard;
INSERT INTO _migration_466_guard(valid) SELECT CASE WHEN (SELECT COUNT(*) FROM questions q JOIN _migration_466_expected e ON e.id = q.id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.paper_type_id IS e.paper_type_id AND q.past_paper_id IS e.past_paper_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.round_type IS e.round_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.question_number IS e.question_number AND q.section IS e.section AND q.is_compulsory IS e.is_compulsory AND q.image_url IS e.image_url AND q.syllabus_topic_id IS e.syllabus_topic_id AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective AND q.source_paper_code IS e.source_paper_code AND q.source_question_number IS e.source_question_number AND q.exam_board_id IS e.exam_board_id) = 2 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _migration_466_expected e ON e.id = r.question_id WHERE r.batch_id IS 'wassce-int-science-sprint2-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep curriculum-aligned WASSCE Integrated Science practice; not official WAEC examination material.' AND r.source_url IS 'https://nacca.gov.gh/secondary-education-curriculum/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1) = 2 AND (SELECT COUNT(*) FROM questions q JOIN topics t ON t.id = q.topic_id AND t.subject_id = q.subject_id JOIN _migration_466_expected e ON e.id = q.id) = 2 AND (SELECT COUNT(*) FROM structured_question_parts sp JOIN _migration_466_expected_parts p ON p.id = sp.id AND sp.id IS p.id AND sp.question_id IS p.question_id AND sp.part_label IS p.part_label AND sp.part_text IS p.part_text AND sp.marks IS p.marks AND sp.correct_answer IS p.correct_answer AND sp.display_order IS p.display_order) = 0 THEN 1 ELSE 0 END;
DROP TABLE _migration_466_guard;
DROP TABLE _migration_466_expected;
DROP TABLE _migration_466_expected_parts;
