-- 532: Original BrillaPrep flashcards, batch flashcards-beta-002, part 1 of 5.
-- Curriculum-aligned revision content; not official WAEC, NaCCA or NSMQ material.
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_01', 'deck_sys_topic_geometry', 'State the angle in a semicircle theorem.', 'The angle subtended at the circumference by a diameter is a right angle: any angle inscribed in a semicircle equals 90°.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_02', 'deck_sys_topic_geometry', 'What is the relationship between a tangent to a circle and the radius drawn to the point of contact?', 'They are perpendicular: the tangent meets the radius at exactly 90° at the point of contact.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_03', 'deck_sys_topic_geometry', 'State the alternate segment theorem.', 'The angle between a tangent and a chord drawn through the point of contact equals the angle subtended by that chord in the alternate segment of the circle.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_04', 'deck_sys_topic_geometry', 'What do the opposite angles of a cyclic quadrilateral add up to?', '180° — opposite angles of a cyclic quadrilateral are supplementary, since each pair subtends arcs that together make the whole circle.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_05', 'deck_sys_topic_geometry', 'State the angle at the centre theorem.', 'The angle subtended by an arc at the centre of a circle is twice the angle subtended by the same arc at the circumference.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_06', 'deck_sys_topic_geometry', 'Write the formula for the circumference of a circle of radius r.', 'C = 2πr (equivalently C = πd, where d = 2r is the diameter).', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_07', 'deck_sys_topic_geometry', 'Write the formula for the volume of a cylinder of radius r and height h.', 'V = πr²h — the base area (πr²) multiplied by the height.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_08', 'deck_sys_topic_geometry', 'Write the formula for the volume of a cone of base radius r and perpendicular height h.', 'V = ⅓πr²h — one third of the volume of the cylinder with the same base and height.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_09', 'deck_sys_topic_geometry', 'What is the sum of the interior angles of an n-sided polygon?', '(n − 2) × 180°. Each exterior angle of a regular n-gon is 360°/n, and the interior angle is 180° − 360°/n.', NULL, 'Split the polygon into triangles from one vertex.', 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_geometry_10', 'deck_sys_topic_geometry', 'What can be said about angles in the same segment of a circle?', 'They are equal: angles subtended by the same arc (or chord) in the same segment of a circle are identical.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_01', 'deck_sys_topic_quadratic', 'Write the standard form of a quadratic equation.', 'ax² + bx + c = 0, where a, b and c are constants and a ≠ 0 (if a = 0 the equation is linear, not quadratic).', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_02', 'deck_sys_topic_quadratic', 'For ax² + bx + c = 0 with a ≠ 0, write the formula that gives the roots in terms of a, b and c.', 'x = (−b ± √(b² − 4ac)) / 2a — obtained by completing the square on the standard form.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_03', 'deck_sys_topic_quadratic', 'What is the discriminant of a quadratic, and what does each sign of it tell you?', 'Δ = b² − 4ac. If Δ > 0 there are two distinct real roots; if Δ = 0 there is one repeated real root; if Δ < 0 there are no real roots (a complex conjugate pair).', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_04', 'deck_sys_topic_quadratic', 'What is the sum of the roots of ax² + bx + c = 0?', '−b/a. This follows from writing the equation as a(x − α)(x − β) = 0 and comparing coefficients of x.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_05', 'deck_sys_topic_quadratic', 'What is the product of the roots of ax² + bx + c = 0?', 'c/a, from the constant term of a(x − α)(x − β) = a[x² − (α + β)x + αβ].', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_06', 'deck_sys_topic_quadratic', 'Solve x² − 5x + 6 = 0 by factorising.', 'x² − 5x + 6 = (x − 2)(x − 3) = 0, so x = 2 or x = 3. The factors come from the pair of numbers with sum −5 and product +6.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_07', 'deck_sys_topic_quadratic', 'What is the axis of symmetry of the parabola y = ax² + bx + c?', 'The vertical line x = −b/2a. The vertex (turning point) of the parabola lies on this line.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_08', 'deck_sys_topic_quadratic', 'Complete the square for x² + 6x + 5.', 'x² + 6x + 5 = (x + 3)² − 9 + 5 = (x + 3)² − 4. Hence the minimum value is −4 at x = −3, and the roots are x = −1 and x = −5.', NULL, 'Halve the coefficient of x to build the bracket.', 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_09', 'deck_sys_topic_quadratic', 'How does the sign of a affect the graph of y = ax² + bx + c?', 'If a > 0 the parabola opens upward and has a minimum point; if a < 0 it opens downward and has a maximum point.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_quadratic_10', 'deck_sys_topic_quadratic', 'Form a quadratic equation with integer coefficients whose roots are 3 and −4.', 'Sum of roots = −1 and product = −12, so the equation is x² − (sum)x + product = 0, i.e. x² + x − 12 = 0.', NULL, 'Use x² − (α + β)x + αβ = 0.', 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_statistics_01', 'deck_sys_topic_statistics', 'Define the mean of a set of n observations.', 'The arithmetic average: mean = Σx/n, the sum of all values divided by the number of values.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_statistics_02', 'deck_sys_topic_statistics', 'Define the median of a data set.', 'The middle value when the data are arranged in order of size; for an even number of observations it is the average of the two middle values.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_statistics_03', 'deck_sys_topic_statistics', 'Define the mode of a data set.', 'The value that occurs most frequently. A data set may have one mode, more than one mode (bimodal), or no mode at all.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_statistics_04', 'deck_sys_topic_statistics', 'What is the range of a data set?', 'The difference between the largest and smallest values: range = maximum − minimum. It is the simplest measure of spread.', NULL, NULL, 1);
