-- 534: Original BrillaPrep flashcards, batch flashcards-beta-002, part 3 of 5.
-- Curriculum-aligned revision content; not official WAEC, NaCCA or NSMQ material.
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_waves_09', 'deck_sys_topic_waves', 'Define the critical angle and give its relation to refractive index.', 'The critical angle θc is the angle of incidence in the denser medium for which the angle of refraction is 90°; sin θc = n₂/n₁ where n₁ > n₂ (for a medium into air, sin θc = 1/n).', NULL, NULL, 4);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_waves_10', 'deck_sys_topic_waves', 'State the thin lens formula.', '1/f = 1/u + 1/v, where f is the focal length, u the object distance and v the image distance, using a consistent sign convention.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_01', 'deck_sys_topic_modern_physics', 'What is the energy of a photon of frequency f?', 'E = hf, where h is Planck’s constant, 6.63 × 10⁻³⁴ J·s. Higher-frequency radiation (e.g. ultraviolet) carries more energy per photon than lower-frequency radiation (e.g. red light).', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_02', 'deck_sys_topic_modern_physics', 'What is the photoelectric effect?', 'The emission of electrons from a metal surface when electromagnetic radiation of sufficiently high frequency falls on it; no electrons are emitted below the threshold frequency, however intense the light.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_03', 'deck_sys_topic_modern_physics', 'Write Einstein’s photoelectric equation.', 'hf = φ + ½mv²max: the photon energy hf equals the work function φ plus the maximum kinetic energy of the emitted photoelectrons.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_04', 'deck_sys_topic_modern_physics', 'Define the work function of a metal.', 'The minimum energy needed to liberate an electron from the metal surface: φ = hf₀, where f₀ is the threshold frequency.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_05', 'deck_sys_topic_modern_physics', 'State the mass–energy equivalence relation.', 'E = mc²: a mass m is equivalent to energy E, with c the speed of light; because c² is huge, a small mass converts into an enormous amount of energy (as in nuclear reactions).', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_06', 'deck_sys_topic_modern_physics', 'Define the half-life of a radioactive isotope.', 'The time taken for half of the radioactive nuclei in a sample to decay — equivalently, for the activity (count rate) to fall to half its initial value.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_07', 'deck_sys_topic_modern_physics', 'State the Heisenberg uncertainty principle.', 'The position and momentum of a particle cannot both be known exactly at the same time: Δx·Δp ≥ ℏ/2, where ℏ = h/2π. The more precisely one is measured, the less precisely the other is known.', NULL, NULL, 4);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_08', 'deck_sys_topic_modern_physics', 'What is meant by wave–particle duality?', 'Matter and radiation exhibit both wave-like behaviour (interference, diffraction) and particle-like behaviour (photoelectric effect, electron diffraction showing the wave nature of particles).', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_09', 'deck_sys_topic_modern_physics', 'Name the three common types of radioactive emission and identify each.', 'Alpha particles — helium nuclei (⁴₂He), strongly ionising, easily stopped; beta particles — fast electrons, moderately penetrating; gamma rays — high-energy electromagnetic radiation, very penetrating.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_modern_physics_10', 'deck_sys_topic_modern_physics', 'What happens to the nucleus of an atom when it undergoes alpha decay?', 'It emits an alpha particle (⁴₂He), so its atomic number decreases by 2 and its mass number decreases by 4, producing a nucleus of a different element.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_01', 'deck_sys_topic_bonding', 'What is an ionic bond?', 'The strong electrostatic attraction between oppositely charged ions, formed when one atom transfers electron(s) to another — typically metal to non-metal, as in NaCl.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_02', 'deck_sys_topic_bonding', 'What is a covalent bond?', 'A shared pair of electrons between two atoms, each atom (usually) contributing one electron — typical between non-metal atoms, as in H₂, Cl₂ and CH₄.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_03', 'deck_sys_topic_bonding', 'What is a metallic bond?', 'The attraction between a lattice of positive metal ions and the sea of delocalised electrons surrounding them; it holds metal atoms together and explains metallic properties.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_04', 'deck_sys_topic_bonding', 'How does the electronegativity difference between two atoms predict the bond type?', 'A large difference (roughly above 1.7) gives an ionic bond; a small or zero difference gives a non-polar covalent bond; an intermediate difference gives a polar covalent bond.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_05', 'deck_sys_topic_bonding', 'Give three characteristic properties of ionic compounds.', 'High melting and boiling points; conduct electricity when molten or in aqueous solution but not when solid; usually soluble in water and brittle as solids.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_06', 'deck_sys_topic_bonding', 'Give two characteristic properties of simple molecular covalent substances.', 'Low melting and boiling points (weak intermolecular forces only), and they do not conduct electricity because they contain no free ions or electrons.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_07', 'deck_sys_topic_bonding', 'What is a coordinate (dative covalent) bond? Give one example.', 'A covalent bond in which both shared electrons are donated by the same atom — for example, the N→H bond in the ammonium ion NH₄⁺ or the O→H bond in H₃O⁺.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_08', 'deck_sys_topic_bonding', 'What is hydrogen bonding, and which elements must be involved?', 'A strong dipole–dipole attraction between a hydrogen atom covalently bonded to nitrogen, oxygen or fluorine and a lone pair on N, O or F of a neighbouring molecule; it explains the unusually high boiling point of water.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_09', 'deck_sys_topic_bonding', 'Why do metals conduct electricity?', 'Their delocalised electrons are free to move through the lattice of positive ions, carrying charge when a potential difference is applied.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_bonding_10', 'deck_sys_topic_bonding', 'What are van der Waals forces?', 'Weak, short-range intermolecular attractions arising from temporary, fluctuating dipoles; present between all molecules and growing stronger as molecular size (number of electrons) increases.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_01', 'deck_sys_topic_organic', 'Write the general formula of the alkanes and name the simplest member.', 'CₙH₂ₙ₊₂; the simplest member is methane, CH₄ (n = 1). Alkanes are saturated hydrocarbons containing only single bonds.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_02', 'deck_sys_topic_organic', 'Write the general formula of the alkenes.', 'CₙH₂ₙ; alkenes are unsaturated hydrocarbons containing one carbon–carbon double bond, e.g. ethene C₂H₄.', NULL, NULL, 1);
