-- 535: Original BrillaPrep flashcards, batch flashcards-beta-002, part 4 of 5.
-- Curriculum-aligned revision content; not official WAEC, NaCCA or NSMQ material.
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_03', 'deck_sys_topic_organic', 'What is a homologous series?', 'A family of organic compounds with the same functional group and general formula, in which successive members differ by CH₂ and show a gradual trend in physical properties and similar chemical behaviour.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_04', 'deck_sys_topic_organic', 'What is a functional group? Give two examples.', 'The atom or group of atoms responsible for the characteristic chemical reactions of a compound — for example, the hydroxyl group −OH in alcohols, the carboxyl group −COOH in carboxylic acids, or the C=C double bond in alkenes.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_05', 'deck_sys_topic_organic', 'What are structural isomers?', 'Compounds that have the same molecular formula but different structural arrangements of atoms — for example, butane and 2-methylpropane are both C₄H₁₀.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_06', 'deck_sys_topic_organic', 'Name the compound CH₃CH₂CH₂OH.', 'Propan-1-ol: a three-carbon chain (propan-) with the hydroxyl group on carbon 1, making it a primary alcohol.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_07', 'deck_sys_topic_organic', 'Describe the chemical test for carbon–carbon unsaturation.', 'Add bromine water: alkenes and alkynes decolourise it (orange-brown to colourless) as Br₂ adds across the multiple bond; saturated compounds give no change.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_08', 'deck_sys_topic_organic', 'What is esterification?', 'The reaction of a carboxylic acid with an alcohol in the presence of an acid catalyst to form an ester and water — for example, ethanoic acid + ethanol → ethyl ethanoate + water.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_09', 'deck_sys_topic_organic', 'What is addition polymerisation? Give one example.', 'The joining of many unsaturated monomer molecules to form a long-chain polymer with no small molecule eliminated — for example, ethene polymerising to poly(ethene).', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_organic_10', 'deck_sys_topic_organic', 'What is cracking in petroleum chemistry?', 'The thermal or catalytic breaking of long-chain alkanes into shorter, more useful alkanes and alkenes; it converts heavy fractions into petrol-range fuels and feedstock alkenes.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_01', 'deck_sys_topic_ecology', 'Define an ecosystem.', 'A community of living organisms together with the non-living (abiotic) components of their environment, interacting as a functional unit — for example, a pond or a savanna.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_02', 'deck_sys_topic_ecology', 'What is a food chain?', 'A linear sequence of organisms through which energy is transferred by feeding, starting with a producer (green plant) and passing through primary, secondary and tertiary consumers.', NULL, NULL, 1);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_03', 'deck_sys_topic_ecology', 'What is a trophic level?', 'A feeding level in a food chain or web: producers occupy the first trophic level, herbivores the second, and successive carnivores the higher levels.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_04', 'deck_sys_topic_ecology', 'State the 10% rule of energy transfer in ecosystems.', 'Only about 10% of the energy at one trophic level is passed on to the next; the rest is lost as heat from respiration, in waste and in uneaten remains — which is why food chains are short.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_05', 'deck_sys_topic_ecology', 'Distinguish between a population and a community.', 'A population is all the individuals of one species living in an area; a community is all the populations of different species living and interacting in that area.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_06', 'deck_sys_topic_ecology', 'What is an ecological niche?', 'The role and position of a species within its ecosystem — its habitat, what it eats, how it obtains energy and how it interacts with other organisms.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_07', 'deck_sys_topic_ecology', 'Define the carrying capacity of an environment.', 'The maximum population size of a species that the environment can sustain indefinitely, given the available food, water, space and other resources.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_08', 'deck_sys_topic_ecology', 'What is the role of decomposers in nutrient cycling?', 'Bacteria and fungi break down dead organisms and waste, releasing mineral nutrients (such as nitrates and phosphates) back into the soil for producers to reuse.', NULL, NULL, 2);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_09', 'deck_sys_topic_ecology', 'What is ecological succession?', 'The orderly, directional change in the species composition of a community over time, from pioneer species through intermediate stages to a stable climax community.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_ecology_10', 'deck_sys_topic_ecology', 'Name the three main types of symbiosis and describe each briefly.', 'Mutualism — both species benefit (e.g. bees and flowering plants); commensalism — one benefits and the other is unaffected; parasitism — one benefits at the expense of the host (e.g. tapeworm in the gut).', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_physiology_01', 'deck_sys_topic_physiology', 'What is the cardiac cycle?', 'The sequence of events making up one heartbeat: atrial systole (atria contract, filling the ventricles), ventricular systole (ventricles contract, pumping blood to lungs and body) and diastole (the heart relaxes and refills); it lasts about 0.8 s at rest.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_physiology_02', 'deck_sys_topic_physiology', 'Describe how a nerve impulse crosses a synapse.', 'The arriving impulse causes vesicles to release neurotransmitter into the synaptic cleft; the transmitter diffuses across, binds to receptors on the post-synaptic membrane and triggers a new impulse there.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_physiology_03', 'deck_sys_topic_physiology', 'Outline the pathway of a reflex arc.', 'Receptor → sensory neurone → relay neurone in the spinal cord → motor neurone → effector (muscle or gland). The response is fast and involuntary because it does not involve the conscious brain.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_physiology_04', 'deck_sys_topic_physiology', 'What is the functional unit of the kidney, and what two processes occur in it?', 'The nephron. Ultrafiltration of blood occurs at the glomerulus into the Bowman’s capsule, then selective reabsorption of useful substances (glucose, some water and salts) occurs along the tubule.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_physiology_05', 'deck_sys_topic_physiology', 'Distinguish between nervous and hormonal control.', 'Nervous control uses electrical impulses along neurones and is fast, short-lived and targeted; hormonal control uses chemical messengers carried in the blood and is slower, longer-lasting and more widespread.', NULL, NULL, 3);
INSERT OR IGNORE INTO flashcards (id, deck_id, front, back, image_url, hint, difficulty) VALUES ('fc_b002_physiology_06', 'deck_sys_topic_physiology', 'Which hormone lowers blood glucose, and which organ secretes it?', 'Insulin, secreted by the islets of Langerhans in the pancreas; it stimulates liver and muscle cells to take up glucose and store it as glycogen. (Glucagon, from the same organ, raises blood glucose.)', NULL, NULL, 2);
