-- 538: Foundation guard for WASSCE Core Mathematics sprint 3 beta batch (wassce-core-math-sprint3-001).
-- Original BrillaPrep practice content; not official WAEC examination material.
-- Re-asserts the prod-canonical topic rows for subj_wassce_core_math on scratch
-- baselines; INSERT OR IGNORE no-ops on prod and on fresh baselines where the
-- rows already exist (prod patches 095/096 and migrations 252-266/364).
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO exam_boards (id, name, code, full_name, region, website_url, is_active, display_order) VALUES ('board_waec', 'WAEC', 'WAEC', 'West African Examinations Council', 'West Africa', 'https://waecgh.org/', 1, 1);
CREATE TABLE IF NOT EXISTS question_content_releases (
    question_id TEXT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    batch_id TEXT NOT NULL,
    quality_assurance TEXT NOT NULL CHECK (quality_assurance IN ('automated_beta', 'human_reviewed')),
    release_channel TEXT NOT NULL CHECK (release_channel IN ('beta', 'production')),
    content_label TEXT NOT NULL,
    source_url TEXT NOT NULL,
    official_exam_board_content INTEGER NOT NULL DEFAULT 0 CHECK (official_exam_board_content IN (0, 1)),
    feedback_enabled INTEGER NOT NULL DEFAULT 1 CHECK (feedback_enabled IN (0, 1)),
    released_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
CREATE INDEX IF NOT EXISTS idx_question_content_releases_batch ON question_content_releases(batch_id);
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_p2_math_alg', 'subj_wassce_core_math', NULL, 'Algebraic processes', 'wassce-p2-math-alg', 'Manipulate linear and simultaneous equations and change the subject of a formula accurately.', 'Algebraic processes covers simplifying and expanding expressions, solving linear and simultaneous equations, factorisation and changing the subject of a formula.', '["ax + b = c → x = (c − b)/a", "(a + b)² = a² + 2ab + b²", "a² − b² = (a − b)(a + b)"]', 21, '2026-08-04T00:00:00.000Z');
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_p2_math_geo', 'subj_wassce_core_math', NULL, 'Plane geometry', 'wassce-p2-math-geo', 'Apply angle, triangle, polygon and circle properties to calculate unknown measures.', 'Plane geometry covers angles at a point and on a straight line, properties of triangles and polygons, parallel-line angle relationships and circle theorems.', '["Angles in a triangle sum to 180°", "Angles on a straight line sum to 180°", "Exterior angles of a polygon sum to 360°", "Interior-angle sum = (n − 2) × 180°"]', 22, '2026-08-04T00:00:00.000Z');
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_p2_math_sta', 'subj_wassce_core_math', NULL, 'Statistics', 'wassce-p2-math-sta', 'Summarise data with measures of central tendency and spread.', 'Statistics summarises data using the mean, median, mode and range, including frequency tables and simple data interpretation.', '["Mean = Σx/n", "Median = middle value of ordered data", "Range = largest − smallest"]', 23, '2026-08-04T00:00:00.000Z');
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_p2_math_qdr', 'subj_wassce_core_math', NULL, 'Quadratic functions', 'wassce-p2-math-qdr', 'Factorise and solve quadratic equations and analyse their roots and graphs.', 'Quadratic functions are solved by factorisation, completing the square or the formula; the discriminant b² − 4ac determines the nature of the roots and the graph is a parabola with a line of symmetry.', '["x = (−b ± √(b² − 4ac))/2a", "sum of roots = −b/a", "product of roots = c/a", "y = (x − h)² + k has vertex (h, k)"]', 24, '2026-08-04T00:00:00.000Z');
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_p2_math_trg', 'subj_wassce_core_math', NULL, 'Trigonometry', 'wassce-p2-math-trg', 'Use trigonometric ratios and Pythagoras to solve right-angled triangle problems.', 'Trigonometry relates the sides and angles of right-angled triangles through sine, cosine and tangent, with applications to angles of elevation and depression.', '["sin θ = opposite/hypotenuse", "cos θ = adjacent/hypotenuse", "tan θ = opposite/adjacent", "a² + b² = c²"]', 25, '2026-08-04T00:00:00.000Z');
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_p2_math_ine', 'subj_wassce_core_math', NULL, 'Inequalities', 'wassce-p2-math-ine', 'Solve linear inequalities, represent them on a number line and state extreme integer solutions.', 'Linear inequalities are solved like equations, except that multiplying or dividing both sides by a negative number reverses the inequality sign.', '["a < b ⇒ a + c < b + c", "a < b and c > 0 ⇒ ac < bc", "a < b and c < 0 ⇒ ac > bc"]', 26, '2026-08-04T00:00:00.000Z');
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_core_math_algebra', 'subj_wassce_core_math', NULL, 'Algebraic Reasoning', 'wassce-core-math-algebra', 'Use symbols and relationships to model and solve everyday algebraic problems.', 'Algebraic reasoning builds fluency with variables: forming expressions and equations from real situations, solving them and interpreting the solutions in context.', '["Consecutive even numbers: n, n + 2, n + 4", "Model a real situation with an equation and solve it"]', 27, '2026-08-04T00:00:00.000Z');
INSERT OR IGNORE INTO topics (id, subject_id, parent_id, name, slug, description, theory_content, key_formulas, display_order, created_at) VALUES ('topic_wassce_core_math_numbers', 'subj_wassce_core_math', NULL, 'Numbers for Everyday Life', 'wassce-core-math-numbers', 'Apply number operations, percentages and financial mathematics to everyday life.', 'Numbers for everyday life covers fractions, decimals, percentages, ratio and commercial arithmetic such as successive percentage changes, profit, loss and interest.', '["a% of N = (a/100) × N", "Successive changes multiply: × (1 + r₁)(1 + r₂)", "Simple interest = PRT/100"]', 28, '2026-08-04T00:00:00.000Z');
CREATE TABLE IF NOT EXISTS _migration_538_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _migration_538_guard;
INSERT INTO _migration_538_guard(valid) SELECT CASE WHEN EXISTS (SELECT 1 FROM exam_types WHERE id = 'exam_wassce') AND EXISTS (SELECT 1 FROM exam_boards WHERE id = 'board_waec') AND EXISTS (SELECT 1 FROM subjects WHERE id = 'subj_wassce_core_math' AND exam_type_id = 'exam_wassce') AND (SELECT COUNT(*) FROM topics t JOIN subjects s ON s.id = t.subject_id WHERE t.id IN ('topic_wassce_p2_math_alg', 'topic_wassce_p2_math_geo', 'topic_wassce_p2_math_sta', 'topic_wassce_p2_math_qdr', 'topic_wassce_p2_math_trg', 'topic_wassce_p2_math_ine', 'topic_wassce_core_math_algebra', 'topic_wassce_core_math_numbers') AND t.subject_id = 'subj_wassce_core_math' AND s.exam_type_id = 'exam_wassce') = 8 THEN 1 ELSE 0 END;
DROP TABLE _migration_538_guard;
