-- Rollback 239: remove the ten inserted BECE beta questions; preserve remediation history.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS _expected_239 (question_id TEXT PRIMARY KEY, topic_id TEXT NOT NULL, subject_id TEXT NOT NULL, exam_type_id TEXT NOT NULL, question_text TEXT NOT NULL, question_type TEXT NOT NULL, options TEXT NOT NULL, correct_answer TEXT NOT NULL, explanation TEXT NOT NULL, difficulty TEXT NOT NULL, points INTEGER NOT NULL, marks INTEGER NOT NULL, time_limit INTEGER NOT NULL, command_word TEXT NOT NULL, assessment_objective TEXT NOT NULL);
DELETE FROM _expected_239;
INSERT INTO _expected_239(question_id,topic_id,subject_id,exam_type_id,question_text,question_type,options,correct_answer,explanation,difficulty,points,marks,time_limit,command_word,assessment_objective) VALUES
  ('q_bece_bdt_gap_b001_021','topic_bece_bdt_electricals','subj_bece_bdt','exam_bece','A wall switch is off but a tester still detects voltage at the fitting. What should the learner conclude?','multiple_choice','["A. The circuit must be isolated at the supply and proved dead before any work","B. The wall switch alone guarantees safe isolation","C. Wet hands will remove the remaining voltage","D. A larger breaker will make the fitting safe"]','A','A local switch may be wired incorrectly or may not isolate every live conductor, so safe work requires supply isolation and verification with a suitable tester. Therefore the correct answer is A: The circuit must be isolated at the supply and proved dead before any work.','medium',1,1,90,'Apply','AO2'),
  ('q_bece_bdt_gap_b001_022','topic_bece_bdt_electricals','subj_bece_bdt','exam_bece','What shows an intentional conductor junction in a circuit drawing?','multiple_choice','["A. A north arrow","B. A roof triangle","C. A solid dot at the conductor intersection","D. A broken dimension line"]','C','A solid junction dot distinguishes a true electrical connection from crossing conductors that pass without joining. Therefore the correct answer is C: A solid dot at the conductor intersection.','easy',1,1,90,'Identify','AO1'),
  ('q_bece_bdt_gap_b001_023','topic_bece_bdt_electricals','subj_bece_bdt','exam_bece','Why should electrical work never be done with wet hands?','multiple_choice','["A. Water turns off the grid","B. Wet hands thicken insulation","C. Moisture stops current","D. Moisture can lower skin resistance and increase shock current"]','D','Moisture can reduce the body’s resistance, allowing a larger and more dangerous current through a person contacting a live part. Therefore the correct answer is D: Moisture can lower skin resistance and increase shock current.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_bdt_gap_b001_024','topic_bece_bdt_electricals','subj_bece_bdt','exam_bece','What does a circuit breaker do after detecting serious overcurrent?','multiple_choice','["A. Generate extra current","B. Join live and neutral","C. Open the circuit automatically; it can be reset after the fault is cleared","D. Hide damaged insulation"]','C','A breaker trips to disconnect unsafe current and can normally be reset only after the underlying fault has been corrected. Therefore the correct answer is C: Open the circuit automatically; it can be reset after the fault is cleared.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_bdt_gap_b001_025','topic_bece_bdt_electricals','subj_bece_bdt','exam_bece','Which action reduces electrical energy waste in a classroom?','multiple_choice','["A. Leave idle chargers powered","B. Keep damaged cables","C. Block equipment ventilation","D. Switch off unused lights and equipment at the source"]','D','Turning unused loads off prevents unnecessary consumption and reduces avoidable heat, operating cost and equipment wear. Therefore the correct answer is D: Switch off unused lights and equipment at the source.','medium',1,1,90,'Apply','AO2'),
  ('q_bece_bdt_gap_b001_026','topic_bece_bdt_electricals','subj_bece_bdt','exam_bece','A person is receiving an electric shock. What is the safest first response?','multiple_choice','["A. Disconnect electricity without directly touching the person","B. Pull them with wet hands","C. Pour water on the appliance","D. Hold the bare conductor"]','A','The supply should be isolated before contact because touching the casualty while current flows can shock the rescuer too. Therefore the correct answer is A: Disconnect electricity without directly touching the person.','hard',1,1,90,'Apply','AO3'),
  ('q_bece_bdt_gap_b001_027','topic_bece_bdt_electricals','subj_bece_bdt','exam_bece','What matters most when selecting a replacement fuse?','multiple_choice','["A. The wall colour","B. The circuit’s specified current rating and fuse type","C. The owner’s age","D. The appliance name length"]','B','A replacement must match the protective design so it carries normal current but interrupts a fault before equipment exceeds safe limits. Therefore the correct answer is B: The circuit’s specified current rating and fuse type.','medium',1,1,90,'Select','AO2'),
  ('q_bece_bdt_gap_b001_028','topic_bece_bdt_entrepreneurship','subj_bece_bdt','exam_bece','Why conduct market research before producing an item for sale?','multiple_choice','["A. To learn what customers need, value and will buy","B. To guarantee sales at any price","C. To avoid competitors","D. To replace costs with guesses"]','A','Market research supplies evidence about customers, alternatives, prices and demand, helping design an offer with a realistic chance of sale. Therefore the correct answer is A: To learn what customers need, value and will buy.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_bdt_gap_b001_029','topic_bece_bdt_entrepreneurship','subj_bece_bdt','exam_bece','Which cost changes most when a craft business makes more units?','multiple_choice','["A. Annual registration already paid","B. Material used for the additional units","C. Fixed monthly rent","D. A permanent workbench"]','B','Material consumption rises with output and is a variable cost, while rent and long-lived equipment do not change unit by unit. Therefore the correct answer is B: Material used for the additional units.','medium',1,1,90,'Explain','AO2'),
  ('q_bece_bdt_gap_b001_030','topic_bece_bdt_entrepreneurship','subj_bece_bdt','exam_bece','How is profit calculated for a small production period?','multiple_choice','["A. Add costs to borrowing","B. Subtract revenue from customers","C. Multiply price by owner age","D. Subtract total costs from sales revenue"]','D','Profit is the amount remaining after relevant costs are deducted from revenue, so incomplete cost records give a misleading result. Therefore the correct answer is D: Subtract total costs from sales revenue.','easy',1,1,90,'Calculate','AO1');
CREATE TABLE IF NOT EXISTS _rollback_239_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _rollback_239_guard;
INSERT INTO _rollback_239_guard(valid) SELECT CASE WHEN
  NOT EXISTS (SELECT 1 FROM questions q JOIN _expected_239 e ON e.question_id=q.id WHERE NOT (q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective))
  AND NOT EXISTS (SELECT 1 FROM question_content_releases r JOIN _expected_239 e ON e.question_id=r.question_id WHERE NOT (r.batch_id IS 'bece-bdt-gap-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1))
  AND NOT EXISTS (SELECT 1 FROM question_bank_remediation_log l JOIN _expected_239 e ON e.question_id=l.entity_id WHERE l.migration_id='239_bece_bdt_gap_beta_part_3' AND NOT (l.migration_id IS '239_bece_bdt_gap_beta_part_3' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-bdt-gap-beta-001'))
  AND (((SELECT COUNT(*) FROM questions q JOIN _expected_239 e ON e.question_id=q.id WHERE q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective)=10 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_239 e ON e.question_id=r.question_id WHERE r.batch_id IS 'bece-bdt-gap-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1)=10 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_239 e ON e.question_id=l.entity_id WHERE l.migration_id IS '239_bece_bdt_gap_beta_part_3' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-bdt-gap-beta-001')=10)
    OR ((SELECT COUNT(*) FROM questions q JOIN _expected_239 e ON e.question_id=q.id)=0 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_239 e ON e.question_id=r.question_id)=0 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_239 e ON e.question_id=l.entity_id WHERE l.migration_id='239_bece_bdt_gap_beta_part_3') IN (0,10)))
THEN 1 ELSE 0 END;
DELETE FROM questions WHERE id IN (SELECT question_id FROM _expected_239);
INSERT INTO _rollback_239_guard(valid) SELECT CASE WHEN (SELECT COUNT(*) FROM questions q JOIN _expected_239 e ON e.question_id=q.id)=0 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_239 e ON e.question_id=r.question_id)=0 THEN 1 ELSE 0 END;
DROP TABLE _expected_239;
DROP TABLE _rollback_239_guard;
