-- Rollback 241: remove the ten inserted BECE beta questions; preserve remediation history.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS _expected_241 (question_id TEXT PRIMARY KEY, topic_id TEXT NOT NULL, subject_id TEXT NOT NULL, exam_type_id TEXT NOT NULL, question_text TEXT NOT NULL, question_type TEXT NOT NULL, options TEXT NOT NULL, correct_answer TEXT NOT NULL, explanation TEXT NOT NULL, difficulty TEXT NOT NULL, points INTEGER NOT NULL, marks INTEGER NOT NULL, time_limit INTEGER NOT NULL, command_word TEXT NOT NULL, assessment_objective TEXT NOT NULL);
DELETE FROM _expected_241;
INSERT INTO _expected_241(question_id,topic_id,subject_id,exam_type_id,question_text,question_type,options,correct_answer,explanation,difficulty,points,marks,time_limit,command_word,assessment_objective) VALUES
  ('q_bece_math_sets_b001_001','topic_bece_math_sets','subj_bece_math','exam_bece','Which notation states that 5 is an element of set A?','multiple_choice','["A. 5 ∈ A","B. 5 ⊂ A","C. 5 ∉ A","D. A ∈ 5"]','A','The symbol ∈ means “is an element of,” so 5 ∈ A states that the object 5 belongs to the collection called set A. Therefore the correct answer is A: 5 ∈ A.','easy',1,1,90,'Identify','AO1'),
  ('q_bece_math_sets_b001_002','topic_bece_math_sets','subj_bece_math','exam_bece','If B = {2, 4, 6, 8}, what is n(B)?','multiple_choice','["A. 2","B. 8","C. 20","D. 4"]','D','Cardinality n(B) counts distinct elements. The listed elements are 2, 4, 6 and 8, so the set contains four elements. Therefore the correct answer is D: 4.','easy',1,1,90,'Calculate','AO1'),
  ('q_bece_math_sets_b001_003','topic_bece_math_sets','subj_bece_math','exam_bece','Which roster lists odd whole numbers below 10?','multiple_choice','["A. {2, 4, 6, 8}","B. {1, 3, 5, 7, 9}","C. {1, 2, 3, 4, 5}","D. {3, 6, 9}"]','B','Odd whole numbers are not divisible by 2. Below 10 they are exactly 1, 3, 5, 7 and 9. Therefore the correct answer is B: {1, 3, 5, 7, 9}.','easy',1,1,90,'Identify','AO1'),
  ('q_bece_math_sets_b001_004','topic_bece_math_sets','subj_bece_math','exam_bece','What is the empty set?','multiple_choice','["A. A set containing zero","B. A set containing no elements","C. A set containing everything","D. A set with duplicate entries"]','B','The empty set has cardinality zero and is written ∅ or { }. The set {0} differs because it contains one element. Therefore the correct answer is B: A set containing no elements.','easy',1,1,90,'Define','AO1'),
  ('q_bece_math_sets_b001_005','topic_bece_math_sets','subj_bece_math','exam_bece','Given A = {1, 2} and B = {1, 2, 3}, which is true?','multiple_choice','["A. B is a subset of A","B. A and B are disjoint","C. A has more elements","D. A is a proper subset of B"]','D','Every element of A occurs in B and B has the additional element 3, so A is a proper subset of B. Therefore the correct answer is D: A is a proper subset of B.','medium',1,1,90,'Determine','AO2'),
  ('q_bece_math_sets_b001_006','topic_bece_math_sets','subj_bece_math','exam_bece','What is the intersection of P = {a, b, c} and Q = {b, c, d}?','multiple_choice','["A. {b, c}","B. {a, d}","C. {a, b, c, d}","D. {b, c, d}"]','A','Intersection contains elements common to both sets. Only b and c appear in both P and Q. Therefore the correct answer is A: {b, c}.','easy',1,1,90,'Determine','AO1'),
  ('q_bece_math_sets_b001_007','topic_bece_math_sets','subj_bece_math','exam_bece','What is the union of P = {a, b, c} and Q = {b, c, d}?','multiple_choice','["A. {b, c}","B. {a, d}","C. {a, b, c, d}","D. {a, b, c, b, c, d}"]','C','Union includes every distinct element appearing in either set, with repeated elements written only once. Therefore the correct answer is C: {a, b, c, d}.','easy',1,1,90,'Determine','AO1'),
  ('q_bece_math_sets_b001_008','topic_bece_math_sets','subj_bece_math','exam_bece','Two sets have no common element. How are they described?','multiple_choice','["A. Equivalent fractions","B. Universal sets","C. Improper subsets","D. Disjoint sets"]','D','Disjoint sets have an empty intersection, written A ∩ B = ∅, because no object belongs to both sets. Therefore the correct answer is D: Disjoint sets.','easy',1,1,90,'Identify','AO1'),
  ('q_bece_math_sets_b001_009','topic_bece_math_sets','subj_bece_math','exam_bece','Let U = {1, 2, 3, 4, 5} and A = {2, 4}. What is A′?','multiple_choice','["A. {2, 4}","B. {1, 2, 3, 4, 5}","C. {1, 3, 5}","D. {3, 5}"]','C','The complement contains elements of U not in A. Removing 2 and 4 leaves 1, 3 and 5. Therefore the correct answer is C: {1, 3, 5}.','medium',1,1,90,'Determine','AO2'),
  ('q_bece_math_sets_b001_010','topic_bece_math_sets','subj_bece_math','exam_bece','What role does a universal set play?','multiple_choice','["A. It contains one element","B. It defines all elements considered in that context","C. It equals the empty set","D. It excludes named sets"]','B','The universal set gives the complete domain, so complements and regions outside named subsets are interpreted relative to it. Therefore the correct answer is B: It defines all elements considered in that context.','medium',1,1,90,'Explain','AO2');
CREATE TABLE IF NOT EXISTS _rollback_241_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _rollback_241_guard;
INSERT INTO _rollback_241_guard(valid) SELECT CASE WHEN
  NOT EXISTS (SELECT 1 FROM questions q JOIN _expected_241 e ON e.question_id=q.id WHERE NOT (q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective))
  AND NOT EXISTS (SELECT 1 FROM question_content_releases r JOIN _expected_241 e ON e.question_id=r.question_id WHERE NOT (r.batch_id IS 'bece-math-sets-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1))
  AND NOT EXISTS (SELECT 1 FROM question_bank_remediation_log l JOIN _expected_241 e ON e.question_id=l.entity_id WHERE l.migration_id='241_bece_math_sets_beta_part_1' AND NOT (l.migration_id IS '241_bece_math_sets_beta_part_1' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-math-sets-beta-001'))
  AND (((SELECT COUNT(*) FROM questions q JOIN _expected_241 e ON e.question_id=q.id WHERE q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective)=10 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_241 e ON e.question_id=r.question_id WHERE r.batch_id IS 'bece-math-sets-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1)=10 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_241 e ON e.question_id=l.entity_id WHERE l.migration_id IS '241_bece_math_sets_beta_part_1' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-math-sets-beta-001')=10)
    OR ((SELECT COUNT(*) FROM questions q JOIN _expected_241 e ON e.question_id=q.id)=0 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_241 e ON e.question_id=r.question_id)=0 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_241 e ON e.question_id=l.entity_id WHERE l.migration_id='241_bece_math_sets_beta_part_1') IN (0,10)))
THEN 1 ELSE 0 END;
DELETE FROM questions WHERE id IN (SELECT question_id FROM _expected_241);
INSERT INTO _rollback_241_guard(valid) SELECT CASE WHEN (SELECT COUNT(*) FROM questions q JOIN _expected_241 e ON e.question_id=q.id)=0 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_241 e ON e.question_id=r.question_id)=0 THEN 1 ELSE 0 END;
DROP TABLE _expected_241;
DROP TABLE _rollback_241_guard;
