-- Rollback 248: remove the ten inserted BECE beta questions; preserve remediation history.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS _expected_248 (question_id TEXT PRIMARY KEY, topic_id TEXT NOT NULL, subject_id TEXT NOT NULL, exam_type_id TEXT NOT NULL, question_text TEXT NOT NULL, question_type TEXT NOT NULL, options TEXT NOT NULL, correct_answer TEXT NOT NULL, explanation TEXT NOT NULL, difficulty TEXT NOT NULL, points INTEGER NOT NULL, marks INTEGER NOT NULL, time_limit INTEGER NOT NULL, command_word TEXT NOT NULL, assessment_objective TEXT NOT NULL);
DELETE FROM _expected_248;
INSERT INTO _expected_248(question_id,topic_id,subject_id,exam_type_id,question_text,question_type,options,correct_answer,explanation,difficulty,points,marks,time_limit,command_word,assessment_objective) VALUES
  ('q_bece_science_agric_b001_031','topic_bece_science_agric','subj_bece_science','exam_bece','Which storage condition best protects dry maize grain?','multiple_choice','["A. An open wet floor","B. A leaking roof","C. A warm pile mixed with refuse","D. A clean, dry, pest-resistant container"]','D','Dry grain in a clean sealed or pest-resistant store is less vulnerable to mould, insects, rodents and re-wetting. Therefore the correct answer is D: A clean, dry, pest-resistant container.','medium',1,1,90,'Select','AO2'),
  ('q_bece_science_agric_b001_032','topic_bece_science_agric','subj_bece_science','exam_bece','Which description correctly defines compost?','multiple_choice','["A. Fresh plastic waste","B. Pure table salt","C. Decomposed organic material used to improve soil","D. Crushed glass fertiliser"]','C','Controlled decomposition converts plant and suitable animal residues into stable organic matter that can improve soil properties. Therefore the correct answer is C: Decomposed organic material used to improve soil.','easy',1,1,90,'Define','AO1'),
  ('q_bece_science_agric_b001_033','topic_bece_science_agric','subj_bece_science','exam_bece','Why should fresh manure be managed before application near food crops?','multiple_choice','["A. It may carry pathogens and release nutrients unpredictably","B. It contains no nutrients","C. It is always dry and sterile","D. It cannot affect water quality"]','A','Proper composting and timing reduce pathogen risk and nutrient losses while making manure safer and more useful to crops. Therefore the correct answer is A: It may carry pathogens and release nutrients unpredictably.','hard',1,1,90,'Evaluate','AO3'),
  ('q_bece_science_agric_b001_034','topic_bece_science_agric','subj_bece_science','exam_bece','A dry, windy farm needs soil protection without heavily shading its food crops. Which agroforestry design is most suitable?','multiple_choice','["A. Plant dense tall trees throughout every crop row without pruning","B. Remove all woody plants and leave the soil exposed","C. Choose tree positions without considering wind direction","D. Place suitable windbreak trees at planned spacing and manage their crowns"]','D','A planned windbreak reduces wind speed and erosion, while suitable spacing and crown management limit competition and excessive shade on the crop area. Therefore the correct answer is D: Place suitable windbreak trees at planned spacing and manage their crowns.','hard',1,1,90,'Explain','AO3'),
  ('q_bece_science_agric_b001_035','topic_bece_science_agric','subj_bece_science','exam_bece','Why avoid overstocking a fish pond?','multiple_choice','["A. It creates unlimited food","B. Too many fish can reduce oxygen and worsen water quality","C. It prevents waste buildup","D. It guarantees faster growth"]','B','Excess biomass increases respiration, waste and competition, so stocking density must match pond volume and management capacity. Therefore the correct answer is B: Too many fish can reduce oxygen and worsen water quality.','hard',1,1,90,'Explain','AO3'),
  ('q_bece_science_agric_b001_036','topic_bece_science_agric','subj_bece_science','exam_bece','What is one purpose of crop rotation beyond soil fertility?','multiple_choice','["A. To keep the same host continuously","B. To eliminate rainfall needs","C. To interrupt pests and diseases dependent on one crop","D. To make records useless"]','C','Changing crop families can break life cycles of organisms that multiply when a susceptible host is grown repeatedly. Therefore the correct answer is C: To interrupt pests and diseases dependent on one crop.','hard',1,1,90,'Explain','AO3'),
  ('q_bece_science_agric_b001_037','topic_bece_science_agric','subj_bece_science','exam_bece','A farmer used 8 bags of fertiliser to harvest 24 crates, then 10 bags to harvest 25 crates. What can the records help the farmer investigate?','multiple_choice','["A. Whether the extra input produced enough additional output to justify its cost","B. Whether record keeping can guarantee next season’s rainfall","C. Whether field inspection is no longer needed","D. Whether the lower yield should be hidden"]','A','Linked input, cost and harvest records allow the farmer to compare marginal output and value, investigate other causes and decide whether the extra input was efficient. Therefore the correct answer is A: Whether the extra input produced enough additional output to justify its cost.','medium',1,1,90,'Interpret','AO2'),
  ('q_bece_science_agric_b001_038','topic_bece_science_agric','subj_bece_science','exam_bece','Which practice supports sustainable soil fertility?','multiple_choice','["A. Apply fertiliser without measurement","B. Burn all residues yearly","C. Leave soil bare","D. Combine tested nutrient inputs with organic matter and erosion control"]','D','Integrated fertility management matches crop needs while building soil condition and limiting nutrient and topsoil losses. Therefore the correct answer is D: Combine tested nutrient inputs with organic matter and erosion control.','hard',1,1,90,'Evaluate','AO3'),
  ('q_bece_science_agric_b001_039','topic_bece_science_agric','subj_bece_science','exam_bece','Vegetables must travel several hours to market without refrigeration. Which harvest plan best protects quality?','multiple_choice','["A. Harvest at midday and leave produce in direct sun","B. Harvest in the cool morning, keep produce shaded and begin transport promptly","C. Pile bruised and sound produce together overnight","D. Wash with unsafe water and seal while hot"]','B','Cool-morning harvest, shade and prompt transport limit field heat and moisture loss during the period before controlled cooling is available. Therefore the correct answer is B: Harvest in the cool morning, keep produce shaded and begin transport promptly.','hard',1,1,90,'Explain','AO3'),
  ('q_bece_science_agric_b001_040','topic_bece_science_agric','subj_bece_science','exam_bece','What makes a farming practice climate-resilient?','multiple_choice','["A. It guarantees weather","B. It reduces exposure or helps production recover from climate stress","C. It ignores local evidence","D. It removes every risk"]','B','Resilient practices such as water conservation and crop diversity reduce vulnerability without pretending that climate uncertainty disappears. Therefore the correct answer is B: It reduces exposure or helps production recover from climate stress.','medium',1,1,90,'Explain','AO2');
CREATE TABLE IF NOT EXISTS _rollback_248_guard (valid INTEGER NOT NULL CHECK (valid = 1));
DELETE FROM _rollback_248_guard;
INSERT INTO _rollback_248_guard(valid) SELECT CASE WHEN
  NOT EXISTS (SELECT 1 FROM questions q JOIN _expected_248 e ON e.question_id=q.id WHERE NOT (q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective))
  AND NOT EXISTS (SELECT 1 FROM question_content_releases r JOIN _expected_248 e ON e.question_id=r.question_id WHERE NOT (r.batch_id IS 'bece-science-agric-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1))
  AND NOT EXISTS (SELECT 1 FROM question_bank_remediation_log l JOIN _expected_248 e ON e.question_id=l.entity_id WHERE l.migration_id='248_bece_science_agric_beta_part_4' AND NOT (l.migration_id IS '248_bece_science_agric_beta_part_4' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-science-agric-beta-001'))
  AND (((SELECT COUNT(*) FROM questions q JOIN _expected_248 e ON e.question_id=q.id WHERE q.id IS e.question_id AND q.topic_id IS e.topic_id AND q.subject_id IS e.subject_id AND q.exam_type_id IS e.exam_type_id AND q.question_text IS e.question_text AND q.question_type IS e.question_type AND q.options IS e.options AND q.correct_answer IS e.correct_answer AND q.explanation IS e.explanation AND q.difficulty IS e.difficulty AND q.points IS e.points AND q.marks IS e.marks AND q.time_limit IS e.time_limit AND q.command_word IS e.command_word AND q.assessment_objective IS e.assessment_objective)=10 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_248 e ON e.question_id=r.question_id WHERE r.batch_id IS 'bece-science-agric-beta-001' AND r.quality_assurance IS 'automated_beta' AND r.release_channel IS 'beta' AND r.content_label IS 'Original BrillaPrep practice content aligned to Ghana’s published NaCCA Common Core Programme curricula; not official WAEC or NaCCA examination material.' AND r.source_url IS 'https://nacca.gov.gh/common-core-programme-ccp/' AND r.official_exam_board_content IS 0 AND r.feedback_enabled IS 1)=10 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_248 e ON e.question_id=l.entity_id WHERE l.migration_id IS '248_bece_science_agric_beta_part_4' AND l.entity_type IS 'question' AND l.field_name IS 'insert' AND l.old_value IS NULL AND l.new_value IS 'bece-science-agric-beta-001')=10)
    OR ((SELECT COUNT(*) FROM questions q JOIN _expected_248 e ON e.question_id=q.id)=0 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_248 e ON e.question_id=r.question_id)=0 AND (SELECT COUNT(*) FROM question_bank_remediation_log l JOIN _expected_248 e ON e.question_id=l.entity_id WHERE l.migration_id='248_bece_science_agric_beta_part_4') IN (0,10)))
THEN 1 ELSE 0 END;
DELETE FROM questions WHERE id IN (SELECT question_id FROM _expected_248);
INSERT INTO _rollback_248_guard(valid) SELECT CASE WHEN (SELECT COUNT(*) FROM questions q JOIN _expected_248 e ON e.question_id=q.id)=0 AND (SELECT COUNT(*) FROM question_content_releases r JOIN _expected_248 e ON e.question_id=r.question_id)=0 THEN 1 ELSE 0 END;
DROP TABLE _expected_248;
DROP TABLE _rollback_248_guard;
