import type { Experiment } from './lab-grading';

// =============================================
// LAB GUIDANCE — student-facing help per step
// =============================================
// Plain-language help for every procedure step, keyed by experiment slug and
// stepNumber. Lives outside experiments.ts so the content corpus can grow
// without touching apparatus/grading definitions. The grader never reads this.
//
// hint: what to do and what to watch for, plus the classic mistake — written
//       for the weakest reader (max 2 short sentences).
// why:  one sentence linking the step to the quality of the final result.

export interface StepGuidance {
  hint: string;
  why: string;
}

export type LabGuidance = Record<string, Record<number, StepGuidance>>;

export const labGuidance: LabGuidance = {
  'acid-base-titration': {
    1: { hint: "First rinse the burette with a little distilled water, then rinse it with a little of the NaOH solution, letting each wash run out through the tap. Many students forget the NaOH rinse, and that loses marks.", why: "Rinsing with the NaOH solution stops leftover water in the burette from diluting your base and shifting your titre." },
    2: { hint: "Fill the burette with NaOH above the zero mark, then open the tap to bring the level down to the mark and make sure there are no air bubbles in the tip. Read the burette at eye level at the bottom of the meniscus, and write down the initial reading before you do anything else.", why: "Removing air bubbles and recording a correct initial reading makes sure the volume you subtract at the end is the true volume of NaOH that entered the flask." },
    3: { hint: "Use the pipette to draw HCl up past the 25ml mark, then let it drain slowly until the bottom of the liquid sits exactly on the mark, and empty it into the conical flask. Never blow out the last drop in the pipette tip; it is meant to stay there.", why: "An exactly measured 25ml of acid is the fixed quantity your whole calculation depends on, so any error here spoils the final concentration." },
    4: { hint: "Add only 2 to 3 drops of methyl orange to the flask and watch the solution turn pink or red. Do not pour in extra indicator thinking more is better.", why: "Too much indicator uses up some of the base itself and makes the colour change harder to judge, so a few drops give the sharpest end point." },
    5: { hint: "Drag the white tile under the burette and place the conical flask on it, directly below the burette tap. Make sure the burette tip is inside the mouth of the flask so no drops splash out.", why: "The white tile makes the first small colour change easy to see, and positioning the flask under the tap stops you from losing any NaOH to splashing." },
    6: { hint: "Run in the NaOH quickly at first while swirling the flask, then add it drop by drop as the pink colour starts fading where the drops land. The classic mistake is rushing past the end point, so slow down the moment the colour lingers.", why: "Swirling mixes the solutions evenly, and adding dropwise near the end point lets you stop at exactly one drop too many instead of overshooting." },
    7: { hint: "Stop the tap as soon as the pink colour turns permanently to orange or yellow, then read the burette at eye level at the bottom of the meniscus and record the final reading. Remember the burette numbers increase downward, so read carefully.", why: "Stopping at the first permanent colour change and reading the final volume correctly gives you the exact titre, the number your concentration calculation rests on." },
    8: { hint: "Repeat the whole titration at least twice more and record each titre, keeping only values that agree within 0.1ml of each other. Do not average in your first rough titre; use it only as a guide for when to slow down.", why: "Repeating until your titres agree within 0.1ml proves your result is reliable and not the result of one lucky or careless run." },
  },
  'crystal-preparation': {
    1: { hint: "Use the Add water button to pour 50ml of distilled water into the 250ml beaker, then heat it and watch the thermometer until it reads about 60°C. Do not boil the water; many students heat past 60°C and must restart, so stop heating as soon as the thermometer reaches 60°C.", why: "Heating the water only to about 60°C helps the copper sulfate dissolve faster without splashing hot solution or evaporating water before the salt is added." },
    2: { hint: "Add the copper sulfate powder a little at a time and stir with the glass rod after each small portion. Keep adding until some solid stays at the bottom and will not dissolve; do not dump all 30g in at once, because undissolved lumps can be mistaken for saturation.", why: "Adding slowly while stirring makes sure the solution is truly saturated, so the maximum amount of copper sulfate is dissolved and plenty of crystals can form later." },
    3: { hint: "Filter the hot saturated solution into the evaporating dish while it is still hot. A common mistake is letting the solution cool first, which makes crystals form early and get stuck in the filter paper.", why: "Filtering while hot removes the undissolved solid before the solution cools, so your final crystals are pure and none are lost in the filter paper." },
    4: { hint: "Heat the evaporating dish gently on the tripod stand and watch the level of the solution until it falls to about half the original volume. Use gentle heat, because strong boiling splashes the solution out of the dish and loses some of your salt.", why: "Gently evaporating half the water concentrates the solution toward the crystallization point without losing copper sulfate through splashing." },
    5: { hint: "Dip the end of the glass rod into the solution, take it out, and let it cool for a moment. If a thin layer of crystals forms on the rod, the solution is ready; if not, keep heating a little more and test again.", why: "Testing with the glass rod tells you exactly when the solution is saturated enough, so you stop heating at the right point and do not dry the salt out completely." },
    6: { hint: "Turn off the Bunsen burner and leave the evaporating dish in a safe place to cool slowly without touching or shaking it. Do not rush the cooling with cold water, because fast cooling gives only small, poor crystals.", why: "Slow undisturbed cooling lets the copper sulfate molecules arrange themselves into large, well-shaped crystals instead of a mass of tiny grains." },
    7: { hint: "Watch the dish carefully as it cools and record what you see: blue crystals slowly growing in the solution. Do not stir or move the dish while the crystals are forming, as this breaks them up.", why: "Careful observation without disturbance lets the crystals grow properly and gives you accurate observations to report in your exam." },
    8: { hint: "Filter off the crystals, wash them with only a small amount of cold distilled water, then press them gently between two pieces of filter paper to dry. Use very little water, because too much water will dissolve your crystals and shrink your yield.", why: "Washing with a little cold water removes impurity solution from the crystal surfaces without dissolving the crystals, and drying between filter papers keeps them clean and intact." },
    9: { hint: "Look closely at your dry crystals and record their colour, shape, and whether they are transparent. Write exactly what you see, for example blue and glassy; never copy a textbook answer that does not match your own crystals.", why: "Recording the true colour, shape, and transparency of your crystals proves you actually observed your product and earns marks for accurate observation." },
  },
  'electrolysis-brine': {
    1: { hint: "Drag the electrolysis cell into the workspace, then insert the two carbon electrodes so both are dipped into the brine. Do not let the electrodes touch each other, and make sure the liquid covers the ends of both.", why: "If the electrodes are not fully immersed or touch each other, the circuit will not work properly and you will get no gases or wrong results." },
    2: { hint: "Connect the positive (+) terminal of the DC power supply to the anode and the negative (-) terminal to the cathode. The classic exam mistake is swapping them or forgetting to say which electrode is the anode (the positive one).", why: "Connecting the wrong way round puts chlorine at the wrong electrode and makes every observation and equation you write afterwards wrong." },
    3: { hint: "Drag a gas jar over each electrode, filled with brine and placed upside down so no air is trapped inside. In the exam, students lose marks by leaving a big air space at the top of the jar.", why: "Air trapped in the jar mixes with the gas you collect and makes your gas tests give unclear or false results." },
    4: { hint: "Set the power supply to 6V and switch it on, then watch both electrodes for bubbles. Use DC (direct current), not AC, and do not turn the voltage too high.", why: "A steady low DC voltage drives the reaction at a safe rate so gases collect slowly enough for you to observe and test them." },
    5: { hint: "Wait patiently until a good amount of gas has collected in each jar before testing; watch the jars filling up in the simulation. Do not rush to test a tiny bubble of gas.", why: "Testing too little gas makes the litmus and splint tests too weak to see clearly, so you could record the wrong observation." },
    6: { hint: "Bring damp blue litmus paper to the gas from the positive electrode (anode). Watch it turn red first, then get bleached white; many students forget the paper must be damp, and dry paper shows nothing.", why: "Damp litmus lets the chlorine dissolve and show its bleaching action, which is the proof that the anode gas is chlorine and not oxygen." },
    7: { hint: "Bring a burning splint to the mouth of the jar over the negative electrode (cathode). Listen for a squeaky pop, and use a lighted splint, not a glowing one, because students often mix the two tests up.", why: "A squeaky pop with a lighted splint is the standard test that proves the cathode gas is hydrogen." },
    8: { hint: "Add universal indicator to the solution around the cathode and watch the colour change to blue or purple. Test near the cathode itself, not just anywhere in the cell.", why: "The blue or purple colour shows the solution near the cathode is now alkaline, proving sodium hydroxide is formed there." },
    9: { hint: "Write the anode equation, the cathode equation, and the overall equation, balancing the number of electrons on both sides. Remember chlorine is Cl2 and hydrogen is H2, never single atoms, and always state which electrode each equation belongs to.", why: "Balanced half equations at the correct electrodes show the examiner you understand where each product comes from, which carries most of the marks." },
  },
  'enzyme-activity': {
    1: { hint: "Set the five water baths to 20, 37, 50, 60 and 80 degrees Celsius using the temperature controls. Check each bath with the thermometer before moving on; do not trust the label alone, because a bath that is a few degrees off will spoil your whole table.", why: "Checking each bath with the thermometer makes sure the only thing changing between your tubes is temperature, so your results truly show the effect of temperature." },
    2: { hint: "Put one small drop of iodine in each hollow of the spotting tile, enough for every sample you plan to take. A common mistake is to use too few spots, so prepare extra before you start the reaction.", why: "Having the iodine spots ready before you mix means you can test quickly at each 30-second mark without letting the reaction run too long between samples." },
    3: { hint: "Measure exactly 5ml of starch and 1ml of amylase into the test tube, then place the tube in the 20 degree Celsius water bath. Do not swap the volumes, because too much enzyme makes the starch finish too fast to time well.", why: "Using the same measured volumes in every tube keeps the test fair, so any difference in digestion time comes from temperature alone." },
    4: { hint: "Start the stopwatch the moment the enzyme touches the starch, then at every 30 seconds take one drop from the tube and add it to an iodine spot. Watch each spot: blue-black means starch is still present, and brown or yellow means the starch is gone.", why: "Testing at fixed 30-second intervals gives you steady, comparable readings, so the time you record is a true measure of how fast the enzyme worked." },
    5: { hint: "Write down the exact stopwatch time when a drop first stays brown or yellow and does not turn blue-black. Do not round the time or stop testing early, because the exam expects the first time starch is fully gone.", why: "Recording the exact time the colour change stops gives you an accurate digestion time, which is the raw number your whole rate calculation depends on." },
    6: { hint: "Repeat the mixing, timing and iodine testing at 37, 50, 60 and 80 degrees Celsius with a fresh tube and fresh solutions each time. Use a new test tube for every temperature, because leftover mixture from a previous run changes your result.", why: "Repeating the full test at every temperature with clean apparatus gives you a complete and fair set of results you can compare and plot." },
    7: { hint: "For each temperature, divide 1 by your digestion time to get the rate, and write the answers to the same number of decimal places. Many students forget to flip time into rate, and a slow tube (long time) must give a small rate.", why: "Converting time into rate (1 over time) turns your raw readings into values that rise and fall with enzyme speed, which is what your graph and conclusion are based on." },
    8: { hint: "Plot temperature on the x-axis and rate of reaction on the y-axis, label both axes with units, and join the points with a smooth curve. Do not force the line through every dot or through the origin; the shape should rise to a peak and then fall.", why: "A correctly labelled, smooth curve lets you and the examiner see the pattern in your data and read the optimum temperature accurately." },
    9: { hint: "Read the temperature at the very top of your curve, the peak where the rate is highest, and state it with the unit degrees Celsius. Do not just write 37 because the textbook says so; read it from your own graph, which should peak near 37 degrees Celsius.", why: "The peak of your curve is the true optimum temperature for amylase from your data, and reading it from the graph shows you can interpret your own results." },
    10: { hint: "Explain that high heat changes the shape of the enzyme, so its active site no longer fits the starch, and say that this damage is permanent and called denaturation. Do not write that the enzyme is killed, because enzymes are not alive; the word examiners want is denatured.", why: "Correctly naming denaturation and the loss of the active site shape shows you understand why the rate falls at high temperatures, which earns the explanation marks." },
  },
  'food-tests': {
    1: { hint: "Tap each test tube and give it a clear label: A for starch, B for protein, C for fat. Write the labels before you add anything, because the classic mistake is mixing up the tubes once reagents are inside and recording results under the wrong food.", why: "Labelling the tubes first stops you from mixing up the samples, which would make every result you record afterwards wrong." },
    2: { hint: "Put a small piece of bread in tube A, then use the dropper to add a few drops of iodine solution and watch the colour. Do not add too much iodine; a few drops are enough, and the common mistake is saying the colour is black only when the correct answer is blue-black.", why: "Using only a small sample and a few drops of iodine keeps the blue-black colour clear and easy to judge, so your starch result is accurate." },
    3: { hint: "Write down exactly the colour you see in tube A, such as blue-black, and state what it means: starch is present. Never write just positive or negative without the colour, because examiners give marks for the actual observation.", why: "Recording the exact colour while it is fresh in your eyes proves you really observed it and protects your observation marks." },
    4: { hint: "Add egg white and a little water to tube B, then add the Biuret reagent in the right order: sodium hydroxide (NaOH) first, then copper sulphate (CuSO4). The mistake many students make is swapping the order or using only one part, which gives no purple colour even though protein is there.", why: "Adding NaOH before CuSO4 creates the correct alkaline condition for the Biuret reaction, so a true purple colour appears only when protein is present." },
    5: { hint: "Record the colour you see in tube B, purple or violet, and write your conclusion that protein is present. Check that you are writing beside tube B in your table, not beside the starch row.", why: "Writing the protein result in the correct row keeps your results table valid and prevents losing marks through careless recording." },
    6: { hint: "Add a few drops of oil to tube C, add ethanol, shake the tube well, then add water and look for a cloudy white mixture. The common mistake is forgetting to shake, because the oil must dissolve in the ethanol first before the water is added.", why: "Shaking dissolves the fat in the ethanol so that adding water produces a true white emulsion, giving a reliable fat test result." },
    7: { hint: "As a second check, add Sudan III to a fat sample and look for a red or orange stained layer on top. Do not confuse this with the white emulsion; Sudan III stains the fat itself red.", why: "Confirming the fat result with Sudan III gives a second independent positive test, which makes your conclusion stronger and earns the extra marks." },
    8: { hint: "Fill the results table with all three tests: name of test, the colour you saw, and your conclusion for each food. Leave no blank boxes, because empty rows in a results table cost marks even when your experiment was correct.", why: "Completing the full table ties every observation to a conclusion, which is what the examiner marks when judging whether your results are valid." },
  },
  'gas-tests': {
    1: { hint: "Use the pour action to add the zinc granules and the dilute HCl into the test tube, then watch for bubbles of gas. Do not bring any flame near the tube yet, hydrogen catches fire easily.", why: "Collecting the gas safely and away from flames protects you and makes sure you have pure hydrogen to test in the next step." },
    2: { hint: "Drag the burning splint to the mouth of the tube and listen carefully for a squeaky pop sound. A common exam mistake is writing pop without saying it is squeaky, so describe the sound exactly.", why: "The squeaky pop is the only sound that proves the gas is hydrogen, so listening carefully and recording it correctly confirms your result." },
    3: { hint: "Pour the hydrogen peroxide onto the manganese dioxide in the test tube and collect the gas in the gas jar. Manganese dioxide only speeds up the reaction, so do not expect it to disappear or dissolve.", why: "Adding the manganese dioxide makes oxygen fast enough to collect, giving you a full gas jar for a clear glowing splint test." },
    4: { hint: "Light the splint, then blow out the flame so it is only glowing red at the tip before you insert it into the gas jar. A common exam mistake is using a burning splint instead of a glowing one.", why: "Only a glowing splint can relight in oxygen, so using the correct splint state is what makes this test valid." },
    5: { hint: "Pour the dilute HCl onto the marble chips, connect the delivery tube, and pass the gas into the lime water while you watch it closely. Look for the clear lime water turning milky, like chalk mixed in water.", why: "Lime water turning milky is the proof of carbon dioxide, so passing the gas through it properly gives you a result you can trust." },
    6: { hint: "Keep passing the carbon dioxide and watch the milky lime water until it goes clear again, then record this. Many students stop too early and miss that the milkiness disappears when excess CO2 is passed.", why: "Recording that excess carbon dioxide turns the mixture clear again shows full understanding and prevents a false reading in a real test." },
    7: { hint: "Add the ammonium chloride and the sodium hydroxide solution to the test tube, then heat gently with the Bunsen burner. Gentle heating is enough, do not boil the mixture hard, and never put your nose over the tube to smell the gas directly.", why: "Gentle heating releases ammonia steadily without splashing hot chemicals, keeping you safe while producing enough gas to test." },
    8: { hint: "Hold the damp red litmus paper at the mouth of the tube, not inside it, and watch for it to turn blue. The paper must be damp, because dry litmus paper will not show the change well.", why: "Damp red litmus turning blue is the standard proof of an alkaline gas, so this step confirms the gas is ammonia." },
    9: { hint: "Fill in the summary table with the test, what you saw, and your conclusion for every gas: hydrogen, oxygen, carbon dioxide, and ammonia. Write the observation you actually saw, not what you think should happen, and never leave a box empty.", why: "A complete and honest summary table is where you show the examiner your evidence, and it carries marks for every correct observation and conclusion." },
  },
  'hookes-law': {
    1: { hint: "In the simulation, drag a spring so it hangs straight down from the support stand, then attach the pointer to its lower end. Check the spring is vertical, not slanting, before you move on.", why: "A spring that hangs vertically stretches only by the load you add, so every extension you measure later is caused by the mass and not by a crooked setup." },
    2: { hint: "Drag the ruler in the simulation so it stands right beside the spring with its markings level with the pointer, and write down the pointer position with no mass on the spring. Do not skip this first reading; many students forget it and then every extension they calculate is wrong.", why: "Recording the starting position gives you the zero point you subtract from every later reading, so your extensions are true extensions and not total lengths." },
    3: { hint: "Drag one 50g mass onto the hook and wait until the spring stops bouncing before you read the pointer. Extension equals this new reading minus your starting reading; never read while the spring is still moving up and down.", why: "Waiting for the spring to settle gives the true position of the pointer, so your first extension value is accurate and not shifted by the spring still vibrating." },
    4: { hint: "Keep adding masses 50g at a time, waiting for the spring to settle each time, and record the pointer position until you have at least 6 readings. Do not hang several masses at once or use very heavy masses, because that can stretch the spring past its elastic limit.", why: "Many evenly spaced readings give a reliable graph, and staying below the elastic limit keeps the spring obeying Hooke's law so your results stay valid." },
    5: { hint: "On graph paper, put load F on the bottom axis and extension e on the side axis, label both axes with units, and choose a scale that spreads your points over more than half the page. Draw one best-fit straight line through the points and the origin; do not join the dots one by one.", why: "A best-fit straight line through the origin smooths out small reading errors and confirms Hooke's law, that extension is directly proportional to load." },
    6: { hint: "Pick two points on your drawn line that are far apart, not your raw data points, and use k equals F divided by e from those points. Convert grams to newtons (50g is about 0.5 N) and centimetres to metres before you calculate, or your answer will be in the wrong unit.", why: "Using two widely spaced points on the best-fit line and converting to SI units gives a spring constant in N per metre that is accurate and free from single-reading errors." },
  },
  'lens-formula': {
    1: { hint: "In the simulation, drag the object (the arrow) to the far end of the optical bench track. Make sure the object, the lens position, and the screen all sit on the same straight line on the track.", why: "Setting the object, lens and screen in one straight line on the bench keeps every light ray on the optical axis so your image distances are measured correctly." },
    2: { hint: "Drag the convex lens onto the track and place it at a distance you can easily read from the object. Use the ruler tool in the simulation to measure u from the object to the middle of the lens, not to the lens edge.", why: "Measuring u from the centre of the lens is what the lens formula assumes, so reading to the lens edge instead would shift every u and spoil your final focal length." },
    3: { hint: "Drag the screen onto the track on the opposite side of the lens from the object. Leave the screen free to slide because you will need to move it to catch the image.", why: "The screen must be on the far side of the lens so the real image formed by the convex lens can actually land on it and be measured." },
    4: { hint: "Slide the screen slowly back and forth until the image on it is at its sharpest point, then stop. Measure v from the middle of the lens to the screen, and write down both u and v in your table before moving anything.", why: "Recording v only when the image is at its sharpest point avoids the common mistake of reading a half-blurred position, which directly falsifies your focal length result." },
    5: { hint: "Move the object or lens to a new distance and refocus the screen each time, collecting at least 5 pairs of u and v. Spread your values widely, for example 20cm, 25cm, 30cm, 35cm and 40cm, and do not bunch them together.", why: "Using several widely spaced distances gives points spread across your graph, so the straight line and its intercept are reliable instead of depending on one lucky reading." },
    6: { hint: "For each row, work out 1/u and 1/v with your calculator and write them to at least 3 decimal places. A common mistake is dividing by the number instead of using the 1/x button, so check one answer by hand.", why: "Working in accurate reciprocals is the heart of this method because the graph of 1/v against 1/u only gives a true straight line when each reciprocal is correct." },
    7: { hint: "Plot 1/v on the vertical axis against 1/u on the horizontal axis, and draw one straight line of best fit through the middle of your points. Do not join the points dot to dot; the line should balance the points on both sides.", why: "The lens formula says 1/v plus 1/u is constant, so a best-fit straight line with a negative slope confirms the law and cancels out small random reading errors." },
    8: { hint: "Extend your best-fit line until it touches the vertical axis and read the intercept there; then f equals 1 divided by that intercept. Check your answer is near 15cm, and do not forget to give f in centimetres.", why: "When 1/u is zero the equation reduces to 1/v equals 1/f, so reading the vertical intercept turns your graph directly into the focal length with no extra guesswork." },
  },
  'microscope-use': {
    1: { hint: "Drag the microscope onto the flat work surface and turn it so the curved arm faces you. In a real exam, carry it with two hands, one under the base and one on the arm; carrying it with one hand loses you handling marks.", why: "Setting the microscope on a flat surface with the arm facing you keeps it stable and stops it from toppling, so the delicate lenses stay safe and your setup stays steady for the whole experiment." },
    2: { hint: "Use the lens cleaning action to wipe the eyepiece and objective lenses with lens paper before you start. Never wipe lenses with your fingers or ordinary cloth, that is the classic mistake that scratches or smears the lens.", why: "Cleaning the lenses with lens paper removes dust and oil so the light passes through cleanly and you see a sharp, true image of the specimen instead of blur." },
    3: { hint: "Rotate the nosepiece until the lowest power objective, marked x4 or x10, clicks into place over the hole in the stage. A common exam mistake is starting on high power, which makes the specimen almost impossible to find.", why: "Starting on the lowest power gives you the widest view and the most working space, so you can locate the specimen easily without the lens crashing into the slide." },
    4: { hint: "Drag the slide onto the stage and clip it down, then move it so the specimen sits exactly over the small hole (the aperture) where the light comes through. Students often forget the clips and the slide drifts out of view.", why: "Securing the slide with the specimen over the aperture makes sure light passes through the part you want to see and keeps the slide from moving while you focus." },
    5: { hint: "Adjust the mirror or lamp control until the view is bright and even. Too little light leaves the field dark, and too much glare washes out a thin specimen, so aim for comfortable brightness.", why: "Good illumination lets light pass evenly through the specimen, which is what makes the details visible and your observations accurate." },
    6: { hint: "Watch the microscope from the side, not through the eyepiece, and lower the objective until it is almost touching the slide. Lowering it while looking through the eyepiece is the classic way students crack the slide and break the lens.", why: "Lowering the objective while watching from the side stops the lens from smashing into the slide, protecting the equipment and keeping your specimen intact." },
    7: { hint: "Now look through the eyepiece and turn the coarse focus knob slowly to raise the objective until the specimen appears. Turn gently and be patient, turning fast sends you straight past the focus point.", why: "Raising the objective away from the slide while viewing can never hit the slide, and the slow coarse adjustment brings the specimen into clear view for a valid observation." },
    8: { hint: "Use the fine focus knob to make the image sharp, then switch to high power for detail. On high power use only the fine focus knob, never the coarse knob, because the high power lens sits very close to the slide.", why: "Using only the fine focus on high power sharpens the image without risking the long lens hitting the slide, giving you a clear and safe detailed view." },
    9: { hint: "Multiply the eyepiece magnification by the objective magnification and record the answer, for example x10 eyepiece times x40 objective gives x400. The common mistake is adding the two numbers instead of multiplying them.", why: "Total magnification is the product of the eyepiece and objective powers, so multiplying them gives the correct value the examiner expects for a magnified image of x400." },
  },
  'ohms-law': {
    1: { hint: "Set up the circuit with the battery, switch, ammeter and resistor in one single loop (in series), with the ammeter in the same path as the resistor. A classic mistake is putting the ammeter across the resistor, which is wrong because an ammeter must always carry the current it measures.", why: "A series circuit makes the same current flow through the ammeter and the resistor, so your current reading truly matches the resistor." },
    2: { hint: "Connect the voltmeter across the resistor so its two leads touch the two ends of the resistor (in parallel). Do not put the voltmeter in series, because in the exam that is the most common connection error and it makes your voltage reading meaningless.", why: "Only a voltmeter connected in parallel measures the true potential difference across the resistor, so your V readings are valid for Ohm's law." },
    3: { hint: "Close the switch so current flows, then read the current I from the ammeter in amperes (A) and the voltage V from the voltmeter in volts (V). Write down both values with their units before you change anything, because students often lose marks for forgetting units.", why: "Recording I and V at the same moment with correct units gives you a valid pair of readings for plotting." },
    4: { hint: "In the simulation, drag the voltage slider to different values and record at least 5 pairs of I and V, spreading them from low to high voltage. Do not repeat nearly the same values, because widely spaced readings make your graph and gradient far more accurate.", why: "Five well-spread pairs of readings let you see the pattern clearly and make the line of best fit reliable." },
    5: { hint: "Plot voltage V on the vertical axis against current I on the horizontal axis, choose scales that fill most of the page, and draw one straight line of best fit through the points and the origin. Do not join the points with short straight segments, because examiners expect a single best straight line.", why: "A straight line through the origin is the signature of Ohm's law, so a correct line of best fit proves the law holds for your resistor." },
    6: { hint: "Pick two points far apart on your line of best fit (not necessarily your data points), find the change in V and the change in I, and divide: R = change in V divided by change in I. A common error is dividing one random V by one I instead of using the gradient of the line.", why: "Using the gradient over a large span averages out small reading errors, so the resistance you report is close to the true value (about 5 ohms)." },
  },
  'osmosis-cells': {
    1: { hint: "Use the scalpel to cut 6 potato strips, each about 5cm long and 1cm by 1cm thick, and check every strip with the meter rule. A common exam mistake is cutting strips of different sizes, because bigger strips gain or lose more water and spoil the comparison.", why: "Strips of equal size give every solution the same surface area to act on, so any mass change is caused only by the sucrose concentration." },
    2: { hint: "Place each strip on the balance one at a time and write down its initial mass before it touches any solution. Do not guess or copy one mass for all strips, because the strips will never weigh exactly the same.", why: "You need the true starting mass of each strip so the percentage change you calculate later is based on real numbers, not guesses." },
    3: { hint: "Put one strip into each petri dish, matching each strip to one concentration from 0M up to 1M, and keep track of which strip is in which dish. A classic mistake is mixing up the dishes, so label or note each one as you go.", why: "Keeping each strip in its own labelled concentration is what lets you link each mass change to the correct solution at the end." },
    4: { hint: "Wait the full 30 minutes, then take the strips out, blot them dry, and weigh each one again on the balance. Do not skip the blotting, because drops of solution left on the outside add extra mass that is not real water gain.", why: "Blotting removes surface liquid so the balance measures only the water that actually moved into or out of the potato cells." },
    5: { hint: "For each strip, work out ((final mass minus initial mass) divided by initial mass) times 100, and write a minus sign if the mass went down. Many students forget the minus sign or divide by the final mass, so check your formula twice.", why: "Percentage change puts all six strips on the same scale, so strips that started at different masses can still be compared fairly." },
    6: { hint: "Plot sucrose concentration on the x-axis and percentage change in mass on the y-axis, mark each point clearly, and draw a smooth best-fit line. Do not join the dots with straight ruler lines, and make sure the line crosses zero somewhere near 0.4M to 0.5M.", why: "The point where your line crosses zero change shows the concentration where the potato cells neither gained nor lost water, which is the isotonic point of the tissue." },
    7: { hint: "Peel a very thin, see-through layer of onion epidermis with the scalpel, place it flat in a drop of distilled water on the slide, and lower the cover slip gently. A common mistake is a thick or folded peel, which blocks the light and gives a blurry view.", why: "A thin single layer of cells mounted in water lets light pass through and keeps the cells fully turgid as your healthy starting point." },
    8: { hint: "Look through the microscope, start on low power, and draw one turgid cell large and clear with sharp pencil lines. Do not shade your diagram or draw from a textbook, draw only what you actually see.", why: "This turgid cell is your before picture, and examiners award marks for drawings that match your real observation with clean unshaded lines." },
    9: { hint: "Add the concentrated salt solution at the edge of the cover slip and watch the cells through the microscope as the change happens. Watch for the cell membrane pulling away from the cell wall, because that gap is the sign of plasmolysis.", why: "Adding salt at the slide edge lets the strong solution flow under the cover slip while you watch, so you can see water leaving the cells in real time." },
    10: { hint: "Draw one plasmolysed cell and label three parts: the cell wall, the cell membrane pulled inwards, and the shrunken cytoplasm. Use label lines that touch the exact part, because labels pointing to empty space lose marks.", why: "A correctly labelled plasmolysed cell proves to the examiner that you understood water left the cell by osmosis and shrank the contents away from the wall." },
  },
  'photosynthesis': {
    1: { hint: "Drag the cover onto part of the leaf, making sure some of the leaf stays uncovered and exposed to light. A common mistake is covering the whole leaf, which leaves you no exposed part to compare with.", why: "Covering only part of the leaf gives you a built-in control, so any difference in starch between the covered and uncovered parts can only be due to light." },
    2: { hint: "Drag the forceps to remove the leaf and take off the foil, then record exactly which areas were covered. Many students forget to note the covered regions, so they cannot match their results to the correct part later.", why: "Recording which parts were covered before you treat the leaf ensures your final colour observations are linked to the right light conditions." },
    3: { hint: "Light the Bunsen burner and boil the leaf in the beaker of water for the full 1 to 2 minutes. A common mistake is boiling for too short a time, so the cells are not fully killed and reactions continue.", why: "Boiling kills the leaf cells and stops all chemical reactions, so any starch you detect afterwards was made during the light exposure, not afterwards." },
    4: { hint: "Put the leaf into the ethanol in the test tube standing in the hot water bath, and watch until the green colour leaves the leaf. Never heat ethanol directly over the flame, because ethanol catches fire easily.", why: "Heating ethanol in a water bath removes the chlorophyll safely without a naked flame, and decolorizing the leaf lets you see the iodine colour change clearly." },
    5: { hint: "Pour warm water over the leaf to rinse off the ethanol and soften it, then spread it flat on the white tile. Students often skip this rinse and the leaf stays stiff and brittle, making it hard to spread without tearing.", why: "Rinsing in warm water removes the ethanol that made the leaf brittle, so it spreads flat on the tile and the iodine can reach every part evenly." },
    6: { hint: "Pour iodine solution over the whole leaf and watch the colour of each area carefully. A classic mistake is adding too little iodine so only part of the leaf is tested.", why: "Covering the entire leaf with iodine makes sure every area, covered and uncovered, is tested for starch so your comparison is valid." },
    7: { hint: "Record blue-black where starch is present and brown or yellow where there is no starch, area by area. Do not write the result you expect; write the colour you actually see on each part of the leaf.", why: "Writing down the true observed colours keeps your results honest, and honest data is the only valid basis for your conclusion." },
    8: { hint: "Repeat the iodine test with the variegated leaf and compare the green areas with the white areas. Many students only compare covered and uncovered and forget this leaf tests for chlorophyll, not light.", why: "Testing a variegated leaf separates the role of chlorophyll from the role of light, showing that only green parts with chlorophyll made starch." },
    9: { hint: "Draw clear diagrams of both leaves and shade or label the parts that turned blue-black. A common mistake is drawing without labels, and examiners award no marks for unlabelled diagrams.", why: "Labelled diagrams give visual evidence of exactly where starch was found, which supports your observations and earns marks for recording." },
    10: { hint: "Write that light and chlorophyll are both needed for photosynthesis, and point to your results as proof. Weak answers just state the theory without referring to the blue-black and brown results from your own leaves.", why: "Linking your conclusion to your own observations shows the examiner you understand the experiment, not just memorized the textbook." },
  },
  'principle-of-moments': {
    1: { hint: "Drag the pivot so it sits under the 50cm mark, which is the middle of the meter rule. Check the rule rests level with nothing hanging on it before you move on.", why: "Balancing the empty rule at its center of gravity removes the rule's own weight from your moments so only the masses you hang will affect the balance." },
    2: { hint: "Drag the 100g mass and hang it exactly at the 20cm mark, which is 30cm from the pivot at 50cm. A common exam mistake is measuring distance from the end of the rule instead of from the pivot.", why: "Placing the known mass at an exact mark gives you an accurate distance, and every moment calculation depends on measuring distance from the pivot." },
    3: { hint: "Hang the 50g mass on the other side of the pivot and slide it slowly until the rule is level again, then read its position on the scale. Use m1 x d1 = m2 x d2 to guess the position first, then fine tune with small drags.", why: "Sliding the mass gently until the rule is exactly level ensures you record the true balance position instead of a rough guess." },
    4: { hint: "Calculate d from 100g x 30cm = 50g x d, so d should be 60cm. Compare this with the distance you measured in the simulation and write down any small difference.", why: "Comparing your calculated distance with the measured one confirms the principle of moments holds and catches any wrong readings before you continue." },
    5: { hint: "Clear the masses, then try new pairs like 200g against 100g and 150g against 75g, recording both masses and both distances in a table each time. Do not reuse old readings, as mixing results from different setups is a classic way to lose marks.", why: "Repeating with different mass combinations shows the principle works in general, not just once, and gives you several results to average for a more reliable conclusion." },
    6: { hint: "Hang the unknown mass on one side and a known mass on the other, then slide until the rule balances and record both distances from the pivot. Use m_unknown = m_known x d_known divided by d_unknown to work out the unknown mass.", why: "Balancing the unknown mass against a known one lets you turn two measured distances into a calculated mass without ever weighing it directly." },
    7: { hint: "Weigh the unknown mass on the balance and compare it with your calculated value, aiming for a difference within 5 percent. If the difference is large, go back and recheck your distances from the pivot.", why: "Weighing the unknown mass on a balance checks your final answer against the true value and proves your moments method was accurate." },
  },
  'qualitative-analysis': {
    1: { hint: "Look carefully at the salt sample in the test tube and press the observe and record buttons. Write down both the colour and the shape of the crystals, not just one, because students often lose marks by writing only the colour.", why: "Recording the appearance first gives you a clue about the salt before any chemical test, and examiners award marks for a complete observation." },
    2: { hint: "Dip the wire loop into the salt, then hold it in the blue part of the Bunsen flame and press the heat button. Watch the flame colour closely, and do not say it is orange just because every Bunsen flame looks yellowish at first.", why: "A clean wire in a hot flame shows the true colour of the metal ion, which is strong evidence for identifying the cation." },
    3: { hint: "Use the pour button to add dilute NaOH to the salt solution, then look for a solid (precipitate) forming and note its colour. If nothing appears, heat gently as the step says; many students add too much NaOH at once and miss whether the precipitate dissolves again.", why: "The colour of the precipitate with NaOH, and whether it dissolves in excess, is the standard exam test for telling metal ions apart." },
    4: { hint: "First add dilute HNO3, then add AgNO3 solution using the pour buttons, in that exact order. A white precipitate after AgNO3 shows chloride is present; a common mistake is skipping the acid, which lets other ions give a false white precipitate.", why: "Adding dilute HNO3 first removes carbonate and other interfering ions so that only chloride can form the white silver chloride precipitate." },
    5: { hint: "Add dilute HCl first, then BaCl2 solution, using the pour buttons in that order. A white precipitate after BaCl2 means sulphate is present; do not reverse the order, because BaCl2 alone can give misleading results with other ions.", why: "The dilute HCl step destroys carbonate ions first, so a white barium sulphate precipitate can only come from a true sulphate." },
    6: { hint: "Add dilute HCl to the salt and watch for bubbles (effervescence) of gas. Then pass the gas into lime water and watch it turn milky, because students often claim a carbonate from bubbles alone without doing the lime water test.", why: "Only a gas that turns lime water milky proves carbon dioxide, and carbon dioxide proves the salt contains a carbonate." },
    7: { hint: "Look back at all your recorded observations and match them to the correct ions, then press the record button to state the cation and anion. Do not guess the salt before checking every test result, since one ignored observation can lead to the wrong answer.", why: "Basing your conclusion on the full set of observations, not a single test, is what makes the identification valid and earns the final marks." },
  },
  'rate-of-reaction': {
    1: { hint: "Drag the paper with the black cross onto the white tile, then drag the conical flask to sit directly on top of the cross. Make sure the cross is exactly under the centre of the flask, because if it is off to one side you may not see it disappear evenly.", why: "Placing the cross directly under the flask gives you a clear, fair target so the timing for the cross to disappear is the same standard for every run." },
    2: { hint: "Use the measuring cylinder action to measure exactly 50ml of the sodium thiosulfate solution, then pour it into the flask. Check the reading at the bottom of the curve of the liquid, because many students misread the cylinder and start with the wrong volume.", why: "Measuring the thiosulfate exactly keeps its amount the same for this run, so any change in time later is caused by concentration and not by sloppy measuring." },
    3: { hint: "Add the 5ml of dilute HCl with the pour action and press the stopwatch at the very same moment the acid goes in, then swirl gently once. A classic mistake is adding the acid first and starting the timer a few seconds late, which gives a time that is too short.", why: "Starting the stopwatch at the exact moment of mixing makes sure you time the whole reaction, so your measured time truly matches how fast the reaction went." },
    4: { hint: "Look straight down through the flask and keep your eyes on the cross the whole time. Stop the stopwatch the very moment the cross is fully hidden by the milky white sulfur, not when the solution just starts to look cloudy.", why: "Stopping the timer only when the cross is fully invisible keeps the end point the same for every run, so the times you compare were all judged by one fair rule." },
    5: { hint: "Repeat the whole reaction for each new mixture: 40ml thiosulfate with 10ml water, then 30ml with 20ml water, then 20ml with 30ml water, then 10ml with 40ml water, keeping the total volume at 50ml and adding 5ml HCl each time. Write every time down at once in a table so you do not mix up which result belongs to which dilution.", why: "Keeping the total volume at 50ml and changing only the thiosulfate amount means concentration is the only thing that changes, so the difference in times is a valid test of the rate." },
    6: { hint: "For each mixture, divide 1 by the time you recorded, for example a time of 40 seconds gives 1 divided by 40, which is 0.025 per second. Do not skip this and try to graph the raw time, because rate is 1 over time, not time itself.", why: "Converting time to 1 over time turns your readings into relative rates, which is the quantity that should relate directly to concentration." },
    7: { hint: "Plot 1 over time (rate) on the y-axis, the upright one, and concentration of thiosulfate on the x-axis, using the volume of thiosulfate as the concentration. Give your axes labels and units and draw a best fit straight line, because examiners take marks off for missing labels.", why: "Plotting rate against concentration with a best fit line lets you see the true pattern in your data and filters out small timing errors from single runs." },
    8: { hint: "Write your conclusion in one clear sentence: as the concentration of thiosulfate increases, the rate of reaction increases, and they are directly proportional if your line passes through the origin. Do not just say the time decreased, because that is about time, not rate.", why: "Stating the relationship between concentration and rate itself shows you understood the aim of the experiment and links your graph back to the science." },
  },
  'refraction-snells-law': {
    1: { hint: "In the simulation, drag the glass block so its bottom edge sits flat on the boundary line, and picture tracing its outline on paper. A common exam mistake is letting the block move after tracing, so note its position before you touch anything else.", why: "A fixed, clearly traced outline gives you a reference edge, so every angle you measure later starts from the same surface." },
    2: { hint: "Use the protractor tool in the sim to draw or imagine a normal line at 90 degrees to the surface, exactly where the light ray will enter. Many students measure angles from the surface instead of the normal, and that ruins every result.", why: "All angles in refraction are measured from the normal, so a correct normal line keeps every later angle accurate." },
    3: { hint: "Drag the laser or its angle control until the protractor shows an angle of incidence i = 20 degrees, measured from the normal. Check the reading twice before moving on, because a small slip here carries into your graph.", why: "Setting the incidence angle precisely makes the first pair of readings trustworthy and anchors the straight line you will plot." },
    4: { hint: "Watch the bright incoming ray in the sim and mark two points on it, as if placing pins P1 and P2 far apart on that line. Points close together give a wobbly line, so spread them out.", why: "Two well-spaced points fix the exact direction of the incident ray so your angle measurement is not guessed." },
    5: { hint: "Look at the ray that comes out the other side of the block and mark two points on it, like placing pins P3 and P4 in line with the emergent ray. Do not confuse the weak reflected ray with the ray that passes through the glass.", why: "Locating the true emergent ray lets you join it back to the entry point and find the real path of light inside the block." },
    6: { hint: "Trace the full path of the ray: the incoming line, the bent line inside the glass, and the outgoing line, using the sim's ray display as your guide. Notice the ray bends towards the normal when entering glass and away when leaving.", why: "Drawing the complete ray path shows where the bending happens, which is exactly where you must measure the angle of refraction." },
    7: { hint: "Drag the protractor to the point where the ray enters the glass and measure angle r between the refracted ray and the normal inside the block, not outside. Students often read the angle from the surface, so double check you are using the normal.", why: "Measuring r from the normal inside the glass gives the correct value that Snell's law pairs with your angle of incidence." },
    8: { hint: "Change the laser angle to 30, 40, 50, 60 and 70 degrees, and record each i with its matching r in a neat table before moving to the next angle. Never leave gaps to fill in later, because mixing up pairs is a classic way to lose marks.", why: "Several honest i and r pairs spread across a wide range make your graph reliable and smooth out small reading errors." },
    9: { hint: "Work out sin i and sin r for each row with your calculator in degree mode, then plot sin i on the y-axis against sin r on the x-axis and draw the best straight line through the origin. A common mistake is plotting i against r directly, which does not give a straight line.", why: "Plotting sin i against sin r turns Snell's law into a straight line whose gradient is the refractive index you need." },
    10: { hint: "Pick two points far apart on your drawn line, not from your data table, and divide the rise by the run to get the gradient n = sin i / sin r. Your answer for glass should be near 1.5, and n has no units, so do not write any.", why: "Using the gradient of the best fit line averages out small measurement errors and gives the most accurate refractive index." },
  },
  'resistance-wire-length': {
    1: { hint: "Connect the battery, switch, ammeter and resistance wire in one single loop, in that order. A common exam mistake is leaving a gap in the loop, so check that every join is complete and the switch is open before you go on.", why: "A series loop makes sure the same current flows through every part, so your ammeter reading truly is the current in the wire." },
    2: { hint: "Connect the voltmeter across only the length of wire you are measuring, using the jockey contact. Do not put the voltmeter in series in the main loop, that is the classic mistake that loses marks.", why: "A voltmeter in parallel measures the voltage across just that piece of wire, which is exactly what you need for R = V/I." },
    3: { hint: "Drag the jockey so it touches the wire exactly at the 20 cm mark, then close the switch and read the ammeter and voltmeter. Read both meters carefully and write down I and V at once before moving anything.", why: "Measuring at the exact mark with the switch only closed briefly keeps the wire cool, so its resistance stays steady and your readings are true." },
    4: { hint: "Divide V by I to get R, for example 2.0 volts divided by 0.5 amps gives 4 ohms. Keep at least two decimal places and write the unit, ohms, every time.", why: "R = V/I turns your raw meter readings into the resistance value the whole experiment and graph depend on." },
    5: { hint: "Move the jockey to 30, 40, 50, 60, 70 and 80 cm, and at each length record I, V and your calculated R in a neat table. Open the switch between readings and do not skip any length, examiners check for a full set.", why: "Many readings over a wide range of lengths give a reliable pattern, and opening the switch between readings stops the wire heating up and changing its resistance." },
    6: { hint: "Put Length on the x-axis and Resistance on the y-axis, label both axes with units, and choose a scale that spreads your points across the page. Draw the best straight line through the points, it should pass through the origin.", why: "A straight line through the origin proves resistance is directly proportional to length, which is the result this experiment is testing." },
    7: { hint: "Pick two points on your drawn line, not your raw data points, that are far apart, and divide the rise in R by the run in L. Show the working clearly and include the unit, ohms per metre.", why: "The gradient of the R against L line equals resistivity divided by area, so a correct gradient is the bridge to finding the resistivity." },
    8: { hint: "Multiply the gradient by the cross-sectional area A of the wire, using A = pi times radius squared, to get resistivity rho. Convert the diameter from millimetres to metres first, forgetting that conversion is the most common error here.", why: "Using rho = RA/L with all lengths in metres gives the resistivity in ohm metres, which you can compare with the true value for constantan of about 4.9 x 10^-7 ohm metres." },
  },
  'simple-pendulum': {
    1: { hint: "In the PhET pendulum simulation, open the lab screen and place the pendulum on the stand so it hangs freely without touching anything. Check that the pendulum hangs straight down at rest before you touch anything else.", why: "A stable, freely hanging pendulum swings in one clean plane, so your timing measurements are not disturbed by bumps or leaning." },
    2: { hint: "Attach the bob to the end of the string and make sure the string is firmly held at the top. In the sim, use the mass slider to choose a bob and confirm it swings without slipping off.", why: "A firmly attached bob keeps the length of the pendulum fixed during the swing, so the period you measure truly belongs to that length." },
    3: { hint: "Use the ruler tool in the sim to measure from the pivot point at the top to the centre (middle) of the bob, and set the length to 100 cm with the length slider. Many students wrongly measure to the top or bottom of the bob instead of its centre.", why: "The length of a pendulum is defined from the point of support to the centre of the bob, and measuring anywhere else gives a false L that shifts your value of g." },
    4: { hint: "Drag the bob to one side by only a small angle, about 5 to 10 degrees, then let it go without pushing it. Do not throw the bob or pull it out too far, as a big swing breaks the simple pendulum rules.", why: "The formula linking period to gravity only works for small swings, so a small release keeps the motion simple and your calculated g accurate." },
    5: { hint: "Let the bob swing a few times first, then start the stopwatch exactly as the bob passes the lowest middle point and stop it after 20 complete to-and-fro swings. Counting from the middle is best because the bob moves fastest there and is easiest to judge.", why: "Timing 20 full oscillations from the fast middle point reduces the error from your reaction time and makes each period measurement more accurate." },
    6: { hint: "Repeat the 20-swing timing at least once more with the same 100 cm length and write down both times. Find the average of your two times before moving on, and do not just use your first attempt.", why: "Repeating and averaging the times cancels out random stopwatch errors, giving a fairer and more reliable value for the period." },
    7: { hint: "Divide your average time by 20 to get the period T, which is the time for one swing. A common exam mistake is forgetting to divide and using the time for 20 swings as the period.", why: "The period is the time for one complete oscillation, and the graph and the formula for g only work with this single-swing time." },
    8: { hint: "Use the length slider to reduce the length by 10 cm each time (90, 80, 70, 60 cm) and repeat the timing for each length until you have at least 5 readings. Record each length with its time in a neat table as you go.", why: "Several readings at different lengths let you plot T squared against L, and the straight-line gradient of that graph is what gives you an accurate value of g." },
  },
  'specific-heat-capacity': {
    1: { hint: "Place the dry metal block on the balance and tap the measure button, then record the mass in grams. Make sure the block is dry before weighing, because water drops add false mass.", why: "Every later calculation uses this mass, so a wrong value here makes your final specific heat capacity wrong." },
    2: { hint: "Weigh the empty, dry calorimeter on the balance and write down the mass before adding anything. Students often forget this step and later guess the mass, which loses easy marks.", why: "The calorimeter itself absorbs some heat, so you need its exact mass to account for that heat in your equation." },
    3: { hint: "Pour about 100ml of cold water into the calorimeter, then weigh the calorimeter with the water inside. To find the mass of the water alone, subtract the empty calorimeter mass from this new mass.", why: "The exact mass of water decides how much heat it absorbs, and using a rough guess like 100g instead of measuring spoils your result." },
    4: { hint: "Put the thermometer in the water, wait until the reading stops moving, then read it at eye level. Record this starting temperature before you do any heating.", why: "This starting temperature is your baseline, and reading it too early while it is still settling gives a wrong temperature rise at the end." },
    5: { hint: "Tie the string firmly to the block, lower it into the boiling water with the string, and start timing 5 full minutes. Do not let the block touch the bottom of the beaker, and never hold it with your bare hands.", why: "Five minutes in boiling water makes sure the whole block reaches the boiling temperature inside and out, not just on its surface." },
    6: { hint: "Read the thermometer in the boiling water at eye level and record it as the temperature of the hot metal. Do not assume it is exactly 100 degrees, read the actual value the thermometer shows.", why: "The block has the same temperature as the boiling water, so recording the true value instead of guessing 100 degrees keeps your heat calculation honest." },
    7: { hint: "Lift the block out with the string and drag it into the calorimeter as fast as you safely can, then stir gently with the thermometer. Slow transfer is the classic mistake here, because the block cools in the air before it reaches the water.", why: "A quick transfer stops the hot block from losing heat to the air, heat that must go into the water for your answer to be correct." },
    8: { hint: "Watch the thermometer while you stir and record the highest reading it reaches before it starts to fall. Many students stop watching too soon and record a temperature that is not the true maximum.", why: "The highest temperature is the point where the metal and water share heat fully, and missing it means your measured temperature rise is too small." },
    9: { hint: "Put your recorded values into the equation m_s x c_s x (theta_s - theta_2) = (m_w x c_w + m_c x c_c) x (theta_2 - theta_1) and solve for c_s, using c_w = 4200 and the calorimeter constant given. Do not forget the calorimeter term m_c x c_c on the right side, that omission is the most common exam error.", why: "Including every mass and temperature you measured makes the heat lost by the metal equal the heat gained by water plus calorimeter, which is the whole principle of the method." },
  },
  'transpiration': {
    1: { hint: "Tap the fill action to pour water into the potometer tube until it is full, then use the observe action to look closely along the tube. Do not move on until you can see no air bubbles trapped anywhere inside.", why: "Air bubbles left in the tube break the continuous water column, so the shoot cannot pull water smoothly and your bubble will not move correctly." },
    2: { hint: "Use the scalpel action to cut the stem underwater at a slant, not straight across, then connect the shoot into the potometer quickly before the cut end dries. The classic exam mistake is cutting in air, which lets an air lock enter the stem and kills the experiment.", why: "Cutting underwater at an angle stops air from entering the xylem vessels and gives a larger surface for water uptake, keeping the water column unbroken." },
    3: { hint: "Drag to apply vaseline all the way around the joint where the shoot enters the potometer, covering every gap. Check the seal from all sides, because even a tiny hole lets air leak in.", why: "An airtight seal makes sure the only way air can enter is through the bubble you will measure, so the bubble movement truly shows water uptake by the shoot." },
    4: { hint: "Use the observe action and simply wait the full 5 minutes without touching the apparatus. Do not rush this step even though nothing seems to be happening.", why: "Equilibrating lets the shoot settle to a steady rate after the shock of cutting, so your first reading is not falsely high or low." },
    5: { hint: "Use the adjust action to lift the end of the tube out of the water for just a moment, then put it back so one small air bubble enters. Lift it briefly only, because a very large bubble is hard to time accurately.", why: "The air bubble acts as a marker that moves as the shoot takes up water, giving you something visible to measure." },
    6: { hint: "With no lamp, fan, or bag, start the stopwatch the moment the bubble crosses your zero mark on the meter rule and stop it exactly when it reaches 5cm. Record the time straight away, and do not start the watch early or late, the most common timing error in this practical.", why: "This normal-conditions measurement is your control, and every later condition is compared against it, so an error here spoils the whole comparison." },
    7: { hint: "First reset the bubble back to zero with the adjust action, then place the lamp shining on the leaves and time the bubble over 5cm again. Record the new time and expect it to be shorter than the normal reading.", why: "Bright light opens the stomata wider so more water evaporates from the leaves, and keeping the same 5cm distance makes this result fairly comparable with the control." },
    8: { hint: "Reset the bubble first, then point the fan directly at the leaves and repeat the 5cm timing. Do not forget the reset, because starting from where the old bubble stopped mixes two experiments together.", why: "Wind blows away the moist air around the leaves so water evaporates faster, and resetting the bubble keeps each trial starting from the same point." },
    9: { hint: "Reset the bubble, then drag the plastic bag over the leaves and time the bubble over 5cm one more time. Expect the longest time of all, because damp air around the leaves slows water loss.", why: "The bag traps humid air around the leaves, which reduces the difference in water concentration between the leaf and the air and slows transpiration." },
    10: { hint: "For each condition divide 5cm by the time you recorded to get the rate, then write down which condition was fastest and slowest and explain why. A common mistake is writing conclusions without showing the calculated rates, so always show your working.", why: "Calculating rates turns your raw timings into numbers you can compare fairly, and explaining them shows the examiner you understand how light, wind, and humidity change transpiration." },
  },
  'virtual-dissection': {
    1: { hint: "Drag the fish onto the dissecting board with its belly (ventral side) facing up, then drag the pins to fix the head and tail. Students often place the fish on its back by mistake, so check that the mouth and anus face you before pinning.", why: "Pinning the fish belly-up keeps it steady and gives you clear access to the part you will cut open." },
    2: { hint: "Use the observe button to find the mouth, eyes, nostrils, operculum (the hard flap covering the gills), and the lateral line running along the side. Record each label as you find it, because students often confuse the nostrils with the eyes or miss the thin lateral line.", why: "Naming the outside features first gives you landmarks that guide every later cut and label." },
    3: { hint: "Find all five fins: dorsal on the back, caudal at the tail, anal near the anus, and the paired pelvic and pectoral fins on the lower sides. A common mistake is swapping the pelvic and pectoral fins, so remember pectoral is nearer the head.", why: "Correctly placing each fin shows you understand the fish's body plan, which the diagram marks depend on." },
    4: { hint: "Drag the forceps to gently lift the operculum, then observe and count the gill arches and note the soft red gill filaments. Do not skip the counting step, because examiners expect a number, not just the word gills.", why: "Counting the gill arches and noting the filaments proves you actually examined the breathing organ instead of guessing." },
    5: { hint: "Drag the scissors to cut along the belly from the anus up to the lower jaw, cutting only through the thin body wall. The classic mistake is cutting too deep and slicing the intestine, so keep the cut shallow.", why: "A shallow cut opens the body without damaging the organs you still have to identify and draw." },
    6: { hint: "Make the side cuts with the scissors, fold the flaps of body wall outward, and drag pins to hold them open. If the flaps keep falling back, it means you have not pinned both sides, which blocks your view of the organs.", why: "Folding and pinning the wall aside gives a clear, open view so no organ is hidden during identification." },
    7: { hint: "Follow the food path with your eyes from the mouth: oesophagus (short food pipe), stomach (thicker bag), long coiled intestine, the large reddish liver over it, and the anus. Record each label; students often wrongly call the intestine the stomach, so check the order.", why: "Tracing the digestive organs in order from mouth to anus stops you from mislabelling one organ for another." },
    8: { hint: "Look just behind and below the gills for the small heart, then observe its two chambers: the thin-walled atrium that receives blood and the thicker ventricle that pumps it out. Do not expect four chambers like a human heart; a fish heart has only two.", why: "Finding both chambers shows you understand the simple two-chambered fish heart that the exam asks about." },
    9: { hint: "Look high in the body cavity, above the gut, for a silvery air-filled sac; that is the swim bladder. When you record its function, write that it controls buoyancy, which means it helps the fish float at different depths.", why: "Linking the swim bladder to buoyancy control turns simple observation into the understanding the marking scheme rewards." },
    10: { hint: "Draw a large, clear diagram in pencil with neat lines, and label the external features and internal organs you found using straight label lines that touch each part. Marks are lost when labels are missing or lines cross, so label everything from steps 2 to 9.", why: "A fully labelled, accurate diagram is the written evidence of your whole dissection and carries the most marks." },
  },
};

/**
 * Merge authored guidance over a procedure step. Inline `hint`/`why` on the
 * experiment definition win when present, so the corpus never clobbers a
 * hand-tuned step.
 */
export function getStepGuidance(
  experiment: Experiment,
  stepNumber: number,
): StepGuidance | null {
  const step = experiment.procedure.find((s) => s.stepNumber === stepNumber);
  const authored = labGuidance[experiment.slug]?.[stepNumber];
  const hint = step?.hint ?? authored?.hint;
  const why = step?.why ?? authored?.why;
  if (!hint && !why) return null;
  return { hint: hint ?? '', why: why ?? '' };
}
